---
title: "Untitled"
author: "Annabel Dang"
date: "2024-05-15"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
# load packages
library(here)
library(tidyverse)
library(qualtRics)

# specify directory structure
i_am("NC_PooledAnalyses.Rmd")

# allow for Type III Sums of Square
options(contrasts = c('contr.sum', 'contr.poly'))
```

# Open study 2 and 3
```{r}
# study 2
s2.DF <- read.csv(here("Study 2 Code", 
                       "Gratitude_Interventions_Study_2.csv")) %>% 
  filter(consent == 1,
         Progress > 95,
         condition != 4,
         condition != 10)
  

# study 3
## Dangs API credential at UCSD
qualtrics_api_credentials(
  api_key = 'urh7PtWEEOkAzrbjmYQC2FoipCvCT4n8ZIByL5rH', 
  base_url = 'iad1.qualtrics.com',
  install = TRUE,
  overwrite = TRUE)

readRenviron("~/.Renviron")

s3.DF <- fetch_survey(surveyID = 'SV_1YQ3FmlbEHp1RIO',
                      force_request = T,
                      label = F,
                      convert = F) %>% 
  filter(lab == 'USA_02') %>% 
  filter(consent == 1,
         Progress > 95)
```

# Combine study 2 and 3
```{r}
# select relevant variables and add study identifier
s2.DF <- s2.DF %>% 
  select(
    # condition identifier
    condition, condition_type,
    
    # outcome variable
    grateful, thankful, appreciative) %>% 
  
  mutate(study = "study_2") %>% 
  mutate(condition_type = as.character(condition_type),
         condition_type = if_else(condition_type == 1,
                                  'control',
                                  'intervention'))
s3.DF <- s3.DF %>% 
  select(
    # condition identifier
    condition, condition_type,
    
    # outcome variable
    grateful, thankful, appreciative) %>% 
  
  mutate(study = "study_3")

# combine
DF <- rbind(s2.DF, s3.DF) %>% 
  mutate(study = factor(study),
         condition_type = factor(condition_type)) %>% 
  rowwise() %>% 
  mutate(grat = mean(c(grateful, thankful, appreciative),
                     na.rm = T)) %>% 
  ungroup()

#rm(s2.DF, s3.DF)
```

# Run moderator analysis
```{r}
m <- lm(grat ~ condition_type * study,
        data = DF)

anova(m)


library(emmeans)
emmeans(m,
        pairwise ~ condition_type | study)
```

