---
title: "Gratitude Interventions Study 2 Pairwise Analysis"
output:
  pdf_document: default
  word_document: default
  html_document: default
date: "2024-04-10"
---

#Libraries
```{r packages}

library(effsize)
library(compute.es)
library(ggplot2)
library(ggsignif)
library(knitr)
library(kableExtra)
library(here)
library(tidyverse)
library(qualtRics)

# specify directory structure
i_am("code/Study 2 Pairwise Analysis.Rmd")

```

#Categories

```{r setup}

# Dangs API credential at UCSD
qualtrics_api_credentials(
  api_key = 'urh7PtWEEOkAzrbjmYQC2FoipCvCT4n8ZIByL5rH', 
  base_url = 'iad1.qualtrics.com',
  install = TRUE,
  overwrite = TRUE)

readRenviron("~/.Renviron")

# open data
DF <- fetch_survey(surveyID = 'SV_0rIOXQcp62uVzsq',
                   force_request = T,
                   label = F,
                   convert = F)

# process data
data <- DF %>%
  # remove incomplete or test observations
  filter(Finished != "0")

data$gratitude_all <- rowMeans(data[, c("grateful", "thankful", "appreciative")], na.rm = TRUE)
data$happy_all <- rowMeans(data[, c("happy", "satisfied", "content", "joyful", "pleased")], na.rm = TRUE)
data$optimistic_all <- rowMeans(data[, c("optimistic", "hopeful")], na.rm = TRUE)
data$sad_all <- rowMeans(data[, c("sad", "depressed", "anxious", "nervous")], na.rm = TRUE)
data$indebted_all <- rowMeans(data[, c("indebted", "obligated")], na.rm = TRUE)
data$envy_all <- rowMeans(data[, c("envious", "bitter", "jealous")], na.rm = TRUE)

data$ls_total <- rowMeans(data[, c("ls_1", "ls_2", "ls_3", "ls_4", "ls_5")], na.rm = TRUE)
data$sc_total <- rowMeans(data[, c("sc_1", "sc_2", "sc_3")], na.rm = TRUE)
data$self_image_total <- rowMeans(data[, c("circle_task", "self_image", "signature")], na.rm = TRUE)

```


```{r categories}
#Conditions
control_conditions <- subset(data, condition_type == 1)
gratitude_conditions <- subset(data, condition_type == 2)

control <- subset(data, condition == 1)
control_events <- subset(data, condition == 2)
control_interesting <- subset(data, condition == 3)
control_hassles <- subset(data, condition == 4)

grat_list <- subset(data, condition == 5)
grat_letter <- subset(data, condition == 6)
grat_text <- subset(data, condition == 7)
grat_hk <- subset(data, condition == 8)
grat_sing <- subset(data, condition == 9)
grat_god_list <- subset(data, condition == 10)
grat_god_letter <- subset(data, condition == 11)

conditions_1 <- c("Control/List", "Control/Letter", "Control/Text", "Control/HK", "Control/Sing", "Control/God List", "Control/God Letter")
conditions_2 <- c("Events/List", "Events/Letter", "Events/Text", "Events/HK", "Events/Sing","Events/God List", "Events/God Letter")
conditions_3 <- c("Interesting Events/List", "Interesting Events/Letter", "Interesting Events/Text", "Interesting Events/HK", "Interesting Events/Sing","Interesting Events/God List", "Interesting Events/God Letter")
conditions_4 <- c("Hassles/List", "Hassles/Letter", "Hassles/Text", "Hassles/HK", "Hassles/Sing","Hassles/God List", "Hassles/God Letter")
conditions_5 <- c("List/Letter", "List/Text", "List/HK", "List/Sing", "List/God List", "List/God Letter", "Letter/Text", "Letter/HK", "Letter/Sing", "Letter/God List", "Letter/God Letter", "Text/HK", "Text/Sing", "Text/God List", "Text/God Letter","HK/Sing", "HK/God List", "HK/God Letter", "Sing/God List", "Sing/God Letter", "God List/God Letter")
conditions_6 <- c("Control/Events", "Control/Interesting Events", "Control/Hassles", "Events/Interesting Events", "Events/Hassles", "Interesting Events/Hassles")

```

#t-Tests (State Gratitude)

```{r control}

control_1 <- t.test(control$gratitude_all, grat_list$gratitude_all)
control_1_ef <- effsize::cohen.d(control$gratitude_all, grat_list$gratitude_all, hedges.correction = TRUE)

control_2 <- t.test(control$gratitude_all, grat_letter$gratitude_all)
control_2_ef <- effsize::cohen.d(control$gratitude_all, grat_letter$gratitude_all, hedges.correction = TRUE)

control_3 <- t.test(control$gratitude_all, grat_text$gratitude_all)
control_3_ef <- effsize::cohen.d(control$gratitude_all, grat_text$gratitude_all, hedges.correction = TRUE)

control_4 <- t.test(control$gratitude_all, grat_hk$gratitude_all)
control_4_ef <- effsize::cohen.d(control$gratitude_all, grat_hk$gratitude_all, hedges.correction = TRUE)

control_5 <- t.test(control$gratitude_all, grat_sing$gratitude_all)
control_5_ef <- effsize::cohen.d(control$gratitude_all, grat_sing$gratitude_all, hedges.correction = TRUE)

control_6 <- t.test(control$gratitude_all, grat_sing$gratitude_all)
control_6_ef <- effsize::cohen.d(control$gratitude_all, grat_god_list$gratitude_all, hedges.correction = TRUE)

control_7 <- t.test(control$gratitude_all, grat_god_letter$gratitude_all)
control_7_ef <- effsize::cohen.d(control$gratitude_all, grat_god_letter$gratitude_all, hedges.correction = TRUE)

#Control t-test Graph

#Dataframe
p_values_1 <- c(control_1$p.value, control_2$p.value, control_3$p.value, control_4$p.value, control_5$p.value, control_6$p.value, control_7$p.value)
estimate_1 <- c(control_1_ef$estimate, control_2_ef$estimate, control_3_ef$estimate, control_4_ef$estimate, control_5_ef$estimate, control_6_ef$estimate, control_7_ef$estimate)
statistic_1 <- c(control_1$statistic, control_2$statistic, control_3$statistic, control_4$statistic, control_5$statistic, control_6$statistic, control_7$statistic)
parameter_1 <- c(control_1$parameter, control_2$parameter, control_3$parameter, control_4$parameter, control_5$parameter, control_6$parameter, control_7$parameter)

#Table
table_data_1 <- data.frame(
  Condition = conditions_1,
  "t" = statistic_1,
  "df" = parameter_1,
  "p" = p_values_1, 
  "Hedges' g" = estimate_1)

print(table_data_1)
```

```{r events}

#Events

events_1 <- t.test(control_events$gratitude_all, grat_list$gratitude_all)
events_1_ef <- effsize::cohen.d(control_events$gratitude_all, grat_list$gratitude_all, hedges.correction = TRUE)

events_2 <- t.test(control_events$gratitude_all, grat_letter$gratitude_all)
events_2_ef <- effsize::cohen.d(control_events$gratitude_all, grat_letter$gratitude_all, hedges.correction = TRUE)

events_3 <- t.test(control_events$gratitude_all, grat_text$gratitude_all)
events_3_ef <- effsize::cohen.d(control_events$gratitude_all, grat_text$gratitude_all, hedges.correction = TRUE)

events_4 <- t.test(control_events$gratitude_all, grat_hk$gratitude_all)
events_4_ef <- effsize::cohen.d(control_events$gratitude_all, grat_hk$gratitude_all, hedges.correction = TRUE)

events_5 <- t.test(control_events$gratitude_all, grat_sing$gratitude_all)
events_5_ef <- effsize::cohen.d(control_events$gratitude_all, grat_sing$gratitude_all, hedges.correction = TRUE)

events_6 <- t.test(control_events$gratitude_all, grat_god_list$gratitude_all)
events_6_ef <- effsize::cohen.d(control_events$gratitude_all, grat_god_list$gratitude_all, hedges.correction = TRUE)

events_7 <- t.test(control_events$gratitude_all, grat_god_letter$gratitude_all)
events_7_ef <- effsize::cohen.d(control_events$gratitude_all, grat_god_letter$gratitude_all, hedges.correction = TRUE)

#Control t-test Graph
p_values_2 <- c(events_1$p.value, events_2$p.value, events_3$p.value, events_4$p.value, events_5$p.value, events_6$p.value, events_7$p.value)
estimate_2 <- c(events_1_ef$estimate, events_2_ef$estimate, events_3_ef$estimate, events_4_ef$estimate, events_5_ef$estimate, events_6_ef$estimate, events_7_ef$estimate)
statistic_2 <- c(events_1$statistic, events_2$statistic, events_3$statistic, events_4$statistic, events_5$statistic, events_6$statistic, events_7$statistic)
parameter_2 <- c(events_1$parameter, events_2$parameter, events_3$parameter, events_4$parameter, events_5$parameter, events_6$parameter, events_7$parameter)

#Table
table_data_2 <- data.frame(
  Condition = conditions_2,
  "t" = statistic_2,
  "df" = parameter_2,
  "p" = p_values_2, 
  "Hedges' g" = estimate_2)

print(table_data_2)
```

```{r interesting events}

#Interesting Events

int_1 <- t.test(control_interesting$gratitude_all, grat_list$gratitude_all)
int_1_ef <- effsize::cohen.d(control_interesting$gratitude_all, grat_list$gratitude_all, hedges.correction = TRUE)

int_2 <- t.test(control_interesting$gratitude_all, grat_letter$gratitude_all)
int_2_ef <- effsize::cohen.d(control_interesting$gratitude_all, grat_letter$gratitude_all, hedges.correction = TRUE)

int_3 <- t.test(control_interesting$gratitude_all, grat_text$gratitude_all)
int_3_ef <- effsize::cohen.d(control_interesting$gratitude_all, grat_text$gratitude_all, hedges.correction = TRUE)

int_4 <- t.test(control_interesting$gratitude_all, grat_hk$gratitude_all)
int_4_ef <- effsize::cohen.d(control_interesting$gratitude_all, grat_hk$gratitude_all, hedges.correction = TRUE)

int_5 <- t.test(control_interesting$gratitude_all, grat_sing$gratitude_all)
int_5_ef <- effsize::cohen.d(control_interesting$gratitude_all, grat_sing$gratitude_all, hedges.correction = TRUE)

int_6 <- t.test(control_interesting$gratitude_all, grat_god_list$gratitude_all)
int_6_ef <- effsize::cohen.d(control_interesting$gratitude_all, grat_god_list$gratitude_all, hedges.correction = TRUE)

int_7 <- t.test(control_interesting$gratitude_all, grat_god_letter$gratitude_all)
int_7_ef <- effsize::cohen.d(control_interesting$gratitude_all, grat_god_letter$gratitude_all, hedges.correction = TRUE)

#Control t-test Graph
p_values_3 <- c(int_1$p.value, int_2$p.value, int_3$p.value, int_4$p.value, int_5$p.value, int_6$p.value, int_7$p.value)
estimate_3 <- c(int_1_ef$estimate, int_2_ef$estimate, int_3_ef$estimate, int_4_ef$estimate, int_5_ef$estimate, int_6_ef$estimate, int_7_ef$estimate)
statistic_3 <- c(int_1$statistic, int_2$statistic, int_3$statistic, int_4$statistic, int_5$statistic, int_6$statistic, int_7$statistic)
parameter_3 <- c(int_1$parameter, int_2$parameter, int_3$parameter, int_4$parameter, int_5$parameter, int_6$parameter, int_7$parameter)

#Table
table_data_3 <- data.frame(
  Condition = conditions_3,
  "t" = statistic_3,
  "df" = parameter_3,
  "p" = p_values_3, 
  "Hedges' g" = estimate_3)

print(table_data_3)
```

```{r hassles}

#Hassles

hassles_1 <- t.test(control_hassles$gratitude_all, grat_list$gratitude_all)
hassles_1_ef <- effsize::cohen.d(control_hassles$gratitude_all, grat_list$gratitude_all, hedges.correction = TRUE)

hassles_2 <- t.test(control_hassles$gratitude_all, grat_letter$gratitude_all)
hassles_2_ef <- effsize::cohen.d(control_hassles$gratitude_all, grat_letter$gratitude_all, hedges.correction = TRUE)

hassles_3 <- t.test(control_hassles$gratitude_all, grat_text$gratitude_all)
hassles_3_ef <- effsize::cohen.d(control_hassles$gratitude_all, grat_text$gratitude_all, hedges.correction = TRUE)

hassles_4 <- t.test(control_hassles$gratitude_all, grat_hk$gratitude_all)
hassles_4_ef <- effsize::cohen.d(control_hassles$gratitude_all, grat_hk$gratitude_all, hedges.correction = TRUE)

hassles_5 <- t.test(control_hassles$gratitude_all, grat_sing$gratitude_all)
hassles_5_ef <- effsize::cohen.d(control_hassles$gratitude_all, grat_sing$gratitude_all, hedges.correction = TRUE)

hassles_6 <- t.test(control_hassles$gratitude_all, grat_god_list$gratitude_all)
hassles_6_ef <- effsize::cohen.d(control_hassles$gratitude_all, grat_god_list$gratitude_all, hedges.correction = TRUE)

hassles_7 <- t.test(control_hassles$gratitude_all, grat_god_letter$gratitude_all)
hassles_7_ef <- effsize::cohen.d(control_hassles$gratitude_all, grat_god_letter$gratitude_all, hedges.correction = TRUE)

#Control t-test Graph

p_values_4 <- c(hassles_1$p.value, hassles_2$p.value, hassles_3$p.value, hassles_4$p.value, hassles_5$p.value, hassles_6$p.value, hassles_7$p.value)
estimate_4 <- c(hassles_1_ef$estimate, hassles_2_ef$estimate, hassles_3_ef$estimate, hassles_4_ef$estimate, hassles_5_ef$estimate, hassles_6_ef$estimate, hassles_7_ef$estimate)
statistic_4 <- c(hassles_1$statistic, hassles_2$statistic, hassles_3$statistic, hassles_4$statistic, hassles_5$statistic, hassles_6$statistic, hassles_7$statistic)
parameter_4 <- c(hassles_1$parameter, hassles_2$parameter, hassles_3$parameter, hassles_4$parameter, hassles_5$parameter, hassles_6$parameter, hassles_7$parameter)

#Table
table_data_4 <- data.frame(
  Condition = conditions_4,
  "t" = statistic_4,
  "df" = parameter_4,
  "p" = p_values_4, 
  "Hedges' g" = estimate_4)

print(table_data_4)
```

```{r gratitude conditions}

#Comparing Across Gratitude Conditions

#Gratitude List

grat_1 <- t.test(grat_list$gratitude_all, grat_letter$gratitude_all)
grat_1_ef <- effsize::cohen.d(grat_list$gratitude_all, grat_letter$gratitude_all, hedges.correction = TRUE)

grat_2 <- t.test(grat_list$gratitude_all, grat_text$gratitude_all)
grat_2_ef <- effsize::cohen.d(grat_list$gratitude_all, grat_text$gratitude_all, hedges.correction = TRUE)

grat_3 <- t.test(grat_list$gratitude_all, grat_hk$gratitude_all)
grat_3_ef <- effsize::cohen.d(grat_list$gratitude_all, grat_hk$gratitude_all, hedges.correction = TRUE)

grat_4 <- t.test(grat_list$gratitude_all, grat_sing$gratitude_all)
grat_4_ef <- effsize::cohen.d(grat_list$gratitude_all, grat_sing$gratitude_all, hedges.correction = TRUE)

grat_5 <- t.test(grat_list$gratitude_all, grat_god_list$gratitude_all)
grat_5_ef <- effsize::cohen.d(grat_list$gratitude_all, grat_list$gratitude_all, hedges.correction = TRUE)

grat_6 <- t.test(grat_list$gratitude_all, grat_god_letter$gratitude_all)
grat_6_ef <- effsize::cohen.d(grat_list$gratitude_all, grat_god_letter$gratitude_all, hedges.correction = TRUE)

#Gratitude Letter

grat_7 <- t.test(grat_letter$gratitude_all, grat_text$gratitude_all)
grat_7_ef <- effsize::cohen.d(grat_letter$gratitude_all, grat_text$gratitude_all, hedges.correction = TRUE)

grat_8 <- t.test(grat_letter$gratitude_all, grat_hk$gratitude_all)
grat_8_ef <- effsize::cohen.d(grat_letter$gratitude_all, grat_hk$gratitude_all, hedges.correction = TRUE)

grat_9 <- t.test(grat_letter$gratitude_all, grat_sing$gratitude_all)
grat_9_ef <- effsize::cohen.d(grat_letter$gratitude_all, grat_sing$gratitude_all, hedges.correction = TRUE)

grat_10 <- t.test(grat_letter$gratitude_all, grat_god_list$gratitude_all)
grat_10_ef <- effsize::cohen.d(grat_letter$gratitude_all, grat_god_list$gratitude_all, hedges.correction = TRUE)

grat_11 <- t.test(grat_letter$gratitude_all, grat_god_letter$gratitude_all)
grat_11_ef <- effsize::cohen.d(grat_letter$gratitude_all, grat_god_letter$gratitude_all, hedges.correction = TRUE)

#Gratitude Text

grat_12 <- t.test(grat_text$gratitude_all, grat_hk$gratitude_all)
grat_12_ef <- effsize::cohen.d(grat_text$gratitude_all, grat_hk$gratitude_all, hedges.correction = TRUE)

grat_13 <- t.test(grat_text$gratitude_all, grat_sing$gratitude_all)
grat_13_ef <- effsize::cohen.d(grat_text$gratitude_all, grat_sing$gratitude_all, hedges.correction = TRUE)

grat_14 <- t.test(grat_text$gratitude_all, grat_god_list$gratitude_all)
grat_14_ef <- effsize::cohen.d(grat_text$gratitude_all, grat_god_list$gratitude_all, hedges.correction = TRUE)

grat_15 <- t.test(grat_text$gratitude_all, grat_god_letter$gratitude_all)
grat_15_ef <- effsize::cohen.d(grat_text$gratitude_all, grat_god_letter$gratitude_all, hedges.correction = TRUE)

#Chan Gratitude List

grat_16 <- t.test(grat_hk$gratitude_all, grat_sing$gratitude_all)
grat_16_ef <- effsize::cohen.d(grat_hk$gratitude_all, grat_sing$gratitude_all, hedges.correction = TRUE)

grat_17 <- t.test(grat_hk$gratitude_all, grat_god_list$gratitude_all)
grat_17_ef <- effsize::cohen.d(grat_hk$gratitude_all, grat_god_list$gratitude_all, hedges.correction = TRUE)

grat_18 <- t.test(grat_hk$gratitude_all, grat_god_letter$gratitude_all)
grat_18_ef <- effsize::cohen.d(grat_hk$gratitude_all, grat_god_letter$gratitude_all, hedges.correction = TRUE)

#Singapore Gratitude Task

grat_19 <- t.test(grat_sing$gratitude_all, grat_god_list$gratitude_all)
grat_19_ef <- effsize::cohen.d(grat_sing$gratitude_all, grat_god_list$gratitude_all, hedges.correction = TRUE)

grat_20 <- t.test(grat_sing$gratitude_all, grat_god_letter$gratitude_all)
grat_20_ef <- effsize::cohen.d(grat_sing$gratitude_all, grat_god_letter$gratitude_all, hedges.correction = TRUE)

#Gratitude to God

grat_21 <- t.test(grat_god_list$gratitude_all, grat_god_letter$gratitude_all)
grat_21_ef <- effsize::cohen.d(grat_god_list$gratitude_all, grat_god_letter$gratitude_all, hedges.correction = TRUE)

#Gratitude Conditions Graph

p_values_5 <- c(grat_1$p.value, grat_2$p.value, grat_3$p.value, grat_4$p.value, grat_5$p.value, grat_6$p.value, grat_7$p.value, grat_8$p.value, grat_9$p.value, grat_10$p.value, grat_11$p.value, grat_12$p.value, grat_13$p.value, grat_14$p.value, grat_15$p.value,grat_16$p.value, grat_17$p.value, grat_18$p.value, grat_19$p.value, grat_20$p.value,grat_21$p.value)
estimate_5 <- c(grat_1_ef$estimate, grat_2_ef$estimate, grat_3_ef$estimate, grat_4_ef$estimate, grat_5_ef$estimate, grat_6_ef$estimate, grat_7_ef$estimate, grat_8_ef$estimate, grat_9_ef$estimate, grat_10_ef$estimate, grat_11_ef$estimate, grat_12_ef$estimate, grat_13_ef$estimate, grat_14_ef$estimate, grat_15_ef$estimate,grat_16_ef$estimate, grat_17_ef$estimate, grat_18_ef$estimate, grat_19_ef$estimate, grat_20_ef$estimate,grat_21_ef$estimate)
statistic_5 <- c(grat_1$statistic, grat_2$statistic, grat_3$statistic, grat_4$statistic, grat_5$statistic, grat_6$statistic, grat_7$statistic, grat_8$statistic, grat_9$statistic, grat_10$statistic, grat_11$statistic, grat_12$statistic, grat_13$statistic, grat_14$statistic, grat_15$statistic,grat_16$statistic, grat_17$statistic, grat_18$statistic, grat_19$statistic, grat_20$statistic,grat_21$statistic)
parameter_5 <- c(grat_1$parameter, grat_2$parameter, grat_3$parameter, grat_4$parameter, grat_5$parameter, grat_6$parameter, grat_7$parameter, grat_8$parameter, grat_9$parameter, grat_10$parameter, grat_11$parameter, grat_12$parameter, grat_13$parameter, grat_14$parameter, grat_15$parameter,grat_16$parameter, grat_17$parameter, grat_18$parameter, grat_19$parameter, grat_20$parameter,grat_21$parameter)

#Table
table_data_5 <- data.frame(
  Condition = conditions_5,
  "t" = statistic_5,
  "df" = parameter_5,
  "p" = p_values_5, 
  "Hedges' g" = estimate_5)

print(table_data_5)

```

```{r control conditions}

#Comparing Across Control Conditions

#Control

con_1 <- t.test(control$gratitude_all, control_events$gratitude_all)
con_1_ef <- effsize::cohen.d(control$gratitude_all, control_events$gratitude_all, hedges.correction = TRUE)

con_2 <- t.test(control$gratitude_all, control_interesting$gratitude_all)
con_2_ef <- effsize::cohen.d(control$gratitude_all, control_interesting$gratitude_all, hedges.correction = TRUE)

con_3 <- t.test(control$gratitude_all, control_hassles$gratitude_all)
con_3_ef <- effsize::cohen.d(control$gratitude_all, control_hassles$gratitude_all, hedges.correction = TRUE)

#Control Events

con_4 <- t.test(control_events$gratitude_all, control_interesting$gratitude_all)
con_4_ef <- effsize::cohen.d(control_events$gratitude_all, control_interesting$gratitude_all, hedges.correction = TRUE)

con_5 <- t.test(control_events$gratitude_all, control_hassles$gratitude_all)
con_5_ef <- effsize::cohen.d(control_events$gratitude_all, control_hassles$gratitude_all, hedges.correction = TRUE)

#Control Interesting Events

con_6 <- t.test(control_interesting$gratitude_all, control_hassles$gratitude_all)
con_6_ef <- effsize::cohen.d(control_interesting$gratitude_all, control_hassles$gratitude_all, hedges.correction = TRUE)

#Control t-test Graph
p_values_6 <- c(con_1$p.value, con_2$p.value, con_3$p.value, con_4$p.value, con_5$p.value, con_6$p.value)
estimate_6 <- c(con_1_ef$estimate, con_2_ef$estimate, con_3_ef$estimate, con_4_ef$estimate, con_5_ef$estimate, con_6_ef$estimate)
statistic_6 <- c(con_1$statistic, con_2$statistic, con_3$statistic, con_4$statistic, con_5$statistic, con_6$statistic)
parameter_6 <- c(con_1$parameter, con_2$parameter, con_3$parameter, con_4$parameter, con_5$parameter, con_6$parameter)

#Table
table_data_6 <- data.frame(
  Condition = conditions_6,
  "t" = statistic_6,
  "df" = parameter_6,
  "p" = p_values_6, 
  "Hedges' g" = estimate_6)

print(table_data_6)

```


#t-Tests (State Happiness)

```{r control}

control_1 <- t.test(control$happy_all, grat_list$happy_all)
control_1_ef <- effsize::cohen.d(control$happy_all, grat_list$happy_all, hedges.correction = TRUE)

control_2 <- t.test(control$happy_all, grat_letter$happy_all)
control_2_ef <- effsize::cohen.d(control$happy_all, grat_letter$happy_all, hedges.correction = TRUE)

control_3 <- t.test(control$happy_all, grat_text$happy_all)
control_3_ef <- effsize::cohen.d(control$happy_all, grat_text$happy_all, hedges.correction = TRUE)

control_4 <- t.test(control$happy_all, grat_hk$happy_all)
control_4_ef <- effsize::cohen.d(control$happy_all, grat_hk$happy_all, hedges.correction = TRUE)

control_5 <- t.test(control$happy_all, grat_sing$happy_all)
control_5_ef <- effsize::cohen.d(control$happy_all, grat_sing$happy_all, hedges.correction = TRUE)

control_6 <- t.test(control$happy_all, grat_sing$happy_all)
control_6_ef <- effsize::cohen.d(control$happy_all, grat_god_list$happy_all, hedges.correction = TRUE)

control_7 <- t.test(control$happy_all, grat_god_letter$happy_all)
control_7_ef <- effsize::cohen.d(control$happy_all, grat_god_letter$happy_all, hedges.correction = TRUE)

#Control t-test Graph

#Dataframe
p_values_1 <- c(control_1$p.value, control_2$p.value, control_3$p.value, control_4$p.value, control_5$p.value, control_6$p.value, control_7$p.value)
estimate_1 <- c(control_1_ef$estimate, control_2_ef$estimate, control_3_ef$estimate, control_4_ef$estimate, control_5_ef$estimate, control_6_ef$estimate, control_7_ef$estimate)
statistic_1 <- c(control_1$statistic, control_2$statistic, control_3$statistic, control_4$statistic, control_5$statistic, control_6$statistic, control_7$statistic)
parameter_1 <- c(control_1$parameter, control_2$parameter, control_3$parameter, control_4$parameter, control_5$parameter, control_6$parameter, control_7$parameter)

#Table
table_data_1 <- data.frame(
  Condition = conditions_1,
  "t" = statistic_1,
  "df" = parameter_1,
  "p" = p_values_1, 
  "Hedges' g" = estimate_1)

print(table_data_1)
```

```{r events}

#Events

events_1 <- t.test(control_events$happy_all, grat_list$happy_all)
events_1_ef <- effsize::cohen.d(control_events$happy_all, grat_list$happy_all, hedges.correction = TRUE)

events_2 <- t.test(control_events$happy_all, grat_letter$happy_all)
events_2_ef <- effsize::cohen.d(control_events$happy_all, grat_letter$happy_all, hedges.correction = TRUE)

events_3 <- t.test(control_events$happy_all, grat_text$happy_all)
events_3_ef <- effsize::cohen.d(control_events$happy_all, grat_text$happy_all, hedges.correction = TRUE)

events_4 <- t.test(control_events$happy_all, grat_hk$happy_all)
events_4_ef <- effsize::cohen.d(control_events$happy_all, grat_hk$happy_all, hedges.correction = TRUE)

events_5 <- t.test(control_events$happy_all, grat_sing$happy_all)
events_5_ef <- effsize::cohen.d(control_events$happy_all, grat_sing$happy_all, hedges.correction = TRUE)

events_6 <- t.test(control_events$happy_all, grat_god_list$happy_all)
events_6_ef <- effsize::cohen.d(control_events$happy_all, grat_god_list$happy_all, hedges.correction = TRUE)

events_7 <- t.test(control_events$happy_all, grat_god_letter$happy_all)
events_7_ef <- effsize::cohen.d(control_events$happy_all, grat_god_letter$happy_all, hedges.correction = TRUE)

#Control t-test Graph
p_values_2 <- c(events_1$p.value, events_2$p.value, events_3$p.value, events_4$p.value, events_5$p.value, events_6$p.value, events_7$p.value)
estimate_2 <- c(events_1_ef$estimate, events_2_ef$estimate, events_3_ef$estimate, events_4_ef$estimate, events_5_ef$estimate, events_6_ef$estimate, events_7_ef$estimate)
statistic_2 <- c(events_1$statistic, events_2$statistic, events_3$statistic, events_4$statistic, events_5$statistic, events_6$statistic, events_7$statistic)
parameter_2 <- c(events_1$parameter, events_2$parameter, events_3$parameter, events_4$parameter, events_5$parameter, events_6$parameter, events_7$parameter)

#Table
table_data_2 <- data.frame(
  Condition = conditions_2,
  "t" = statistic_2,
  "df" = parameter_2,
  "p" = p_values_2, 
  "Hedges' g" = estimate_2)

print(table_data_2)
```

```{r interesting events}

#Interesting Events

int_1 <- t.test(control_interesting$happy_all, grat_list$happy_all)
int_1_ef <- effsize::cohen.d(control_interesting$happy_all, grat_list$happy_all, hedges.correction = TRUE)

int_2 <- t.test(control_interesting$happy_all, grat_letter$happy_all)
int_2_ef <- effsize::cohen.d(control_interesting$happy_all, grat_letter$happy_all, hedges.correction = TRUE)

int_3 <- t.test(control_interesting$happy_all, grat_text$happy_all)
int_3_ef <- effsize::cohen.d(control_interesting$happy_all, grat_text$happy_all, hedges.correction = TRUE)

int_4 <- t.test(control_interesting$happy_all, grat_hk$happy_all)
int_4_ef <- effsize::cohen.d(control_interesting$happy_all, grat_hk$happy_all, hedges.correction = TRUE)

int_5 <- t.test(control_interesting$happy_all, grat_sing$happy_all)
int_5_ef <- effsize::cohen.d(control_interesting$happy_all, grat_sing$happy_all, hedges.correction = TRUE)

int_6 <- t.test(control_interesting$happy_all, grat_god_list$happy_all)
int_6_ef <- effsize::cohen.d(control_interesting$happy_all, grat_god_list$happy_all, hedges.correction = TRUE)

int_7 <- t.test(control_interesting$happy_all, grat_god_letter$happy_all)
int_7_ef <- effsize::cohen.d(control_interesting$happy_all, grat_god_letter$happy_all, hedges.correction = TRUE)

#Control t-test Graph
p_values_3 <- c(int_1$p.value, int_2$p.value, int_3$p.value, int_4$p.value, int_5$p.value, int_6$p.value, int_7$p.value)
estimate_3 <- c(int_1_ef$estimate, int_2_ef$estimate, int_3_ef$estimate, int_4_ef$estimate, int_5_ef$estimate, int_6_ef$estimate, int_7_ef$estimate)
statistic_3 <- c(int_1$statistic, int_2$statistic, int_3$statistic, int_4$statistic, int_5$statistic, int_6$statistic, int_7$statistic)
parameter_3 <- c(int_1$parameter, int_2$parameter, int_3$parameter, int_4$parameter, int_5$parameter, int_6$parameter, int_7$parameter)

#Table
table_data_3 <- data.frame(
  Condition = conditions_3,
  "t" = statistic_3,
  "df" = parameter_3,
  "p" = p_values_3, 
  "Hedges' g" = estimate_3)

print(table_data_3)
```

```{r hassles}

#Hassles

hassles_1 <- t.test(control_hassles$happy_all, grat_list$happy_all)
hassles_1_ef <- effsize::cohen.d(control_hassles$happy_all, grat_list$happy_all, hedges.correction = TRUE)

hassles_2 <- t.test(control_hassles$happy_all, grat_letter$happy_all)
hassles_2_ef <- effsize::cohen.d(control_hassles$happy_all, grat_letter$happy_all, hedges.correction = TRUE)

hassles_3 <- t.test(control_hassles$happy_all, grat_text$happy_all)
hassles_3_ef <- effsize::cohen.d(control_hassles$happy_all, grat_text$happy_all, hedges.correction = TRUE)

hassles_4 <- t.test(control_hassles$happy_all, grat_hk$happy_all)
hassles_4_ef <- effsize::cohen.d(control_hassles$happy_all, grat_hk$happy_all, hedges.correction = TRUE)

hassles_5 <- t.test(control_hassles$happy_all, grat_sing$happy_all)
hassles_5_ef <- effsize::cohen.d(control_hassles$happy_all, grat_sing$happy_all, hedges.correction = TRUE)

hassles_6 <- t.test(control_hassles$happy_all, grat_god_list$happy_all)
hassles_6_ef <- effsize::cohen.d(control_hassles$happy_all, grat_god_list$happy_all, hedges.correction = TRUE)

hassles_7 <- t.test(control_hassles$happy_all, grat_god_letter$happy_all)
hassles_7_ef <- effsize::cohen.d(control_hassles$happy_all, grat_god_letter$happy_all, hedges.correction = TRUE)

#Control t-test Graph

p_values_4 <- c(hassles_1$p.value, hassles_2$p.value, hassles_3$p.value, hassles_4$p.value, hassles_5$p.value, hassles_6$p.value, hassles_7$p.value)
estimate_4 <- c(hassles_1_ef$estimate, hassles_2_ef$estimate, hassles_3_ef$estimate, hassles_4_ef$estimate, hassles_5_ef$estimate, hassles_6_ef$estimate, hassles_7_ef$estimate)
statistic_4 <- c(hassles_1$statistic, hassles_2$statistic, hassles_3$statistic, hassles_4$statistic, hassles_5$statistic, hassles_6$statistic, hassles_7$statistic)
parameter_4 <- c(hassles_1$parameter, hassles_2$parameter, hassles_3$parameter, hassles_4$parameter, hassles_5$parameter, hassles_6$parameter, hassles_7$parameter)

#Table
table_data_4 <- data.frame(
  Condition = conditions_4,
  "t" = statistic_4,
  "df" = parameter_4,
  "p" = p_values_4, 
  "Hedges' g" = estimate_4)

print(table_data_4)
```

```{r gratitude conditions}

#Comparing Across Gratitude Conditions

#Gratitude List

grat_1 <- t.test(grat_list$happy_all, grat_letter$happy_all)
grat_1_ef <- effsize::cohen.d(grat_list$happy_all, grat_letter$happy_all, hedges.correction = TRUE)

grat_2 <- t.test(grat_list$happy_all, grat_text$happy_all)
grat_2_ef <- effsize::cohen.d(grat_list$happy_all, grat_text$happy_all, hedges.correction = TRUE)

grat_3 <- t.test(grat_list$happy_all, grat_hk$happy_all)
grat_3_ef <- effsize::cohen.d(grat_list$happy_all, grat_hk$happy_all, hedges.correction = TRUE)

grat_4 <- t.test(grat_list$happy_all, grat_sing$happy_all)
grat_4_ef <- effsize::cohen.d(grat_list$happy_all, grat_sing$happy_all, hedges.correction = TRUE)

grat_5 <- t.test(grat_list$happy_all, grat_god_list$happy_all)
grat_5_ef <- effsize::cohen.d(grat_list$happy_all, grat_list$happy_all, hedges.correction = TRUE)

grat_6 <- t.test(grat_list$happy_all, grat_god_letter$happy_all)
grat_6_ef <- effsize::cohen.d(grat_list$happy_all, grat_god_letter$happy_all, hedges.correction = TRUE)

#Gratitude Letter

grat_7 <- t.test(grat_letter$happy_all, grat_text$happy_all)
grat_7_ef <- effsize::cohen.d(grat_letter$happy_all, grat_text$happy_all, hedges.correction = TRUE)

grat_8 <- t.test(grat_letter$happy_all, grat_hk$happy_all)
grat_8_ef <- effsize::cohen.d(grat_letter$happy_all, grat_hk$happy_all, hedges.correction = TRUE)

grat_9 <- t.test(grat_letter$happy_all, grat_sing$happy_all)
grat_9_ef <- effsize::cohen.d(grat_letter$happy_all, grat_sing$happy_all, hedges.correction = TRUE)

grat_10 <- t.test(grat_letter$happy_all, grat_god_list$happy_all)
grat_10_ef <- effsize::cohen.d(grat_letter$happy_all, grat_god_list$happy_all, hedges.correction = TRUE)

grat_11 <- t.test(grat_letter$happy_all, grat_god_letter$happy_all)
grat_11_ef <- effsize::cohen.d(grat_letter$happy_all, grat_god_letter$happy_all, hedges.correction = TRUE)

#Gratitude Text

grat_12 <- t.test(grat_text$happy_all, grat_hk$happy_all)
grat_12_ef <- effsize::cohen.d(grat_text$happy_all, grat_hk$happy_all, hedges.correction = TRUE)

grat_13 <- t.test(grat_text$happy_all, grat_sing$happy_all)
grat_13_ef <- effsize::cohen.d(grat_text$happy_all, grat_sing$happy_all, hedges.correction = TRUE)

grat_14 <- t.test(grat_text$happy_all, grat_god_list$happy_all)
grat_14_ef <- effsize::cohen.d(grat_text$happy_all, grat_god_list$happy_all, hedges.correction = TRUE)

grat_15 <- t.test(grat_text$happy_all, grat_god_letter$happy_all)
grat_15_ef <- effsize::cohen.d(grat_text$happy_all, grat_god_letter$happy_all, hedges.correction = TRUE)

#Chan Gratitude List

grat_16 <- t.test(grat_hk$happy_all, grat_sing$happy_all)
grat_16_ef <- effsize::cohen.d(grat_hk$happy_all, grat_sing$happy_all, hedges.correction = TRUE)

grat_17 <- t.test(grat_hk$happy_all, grat_god_list$happy_all)
grat_17_ef <- effsize::cohen.d(grat_hk$happy_all, grat_god_list$happy_all, hedges.correction = TRUE)

grat_18 <- t.test(grat_hk$happy_all, grat_god_letter$happy_all)
grat_18_ef <- effsize::cohen.d(grat_hk$happy_all, grat_god_letter$happy_all, hedges.correction = TRUE)

#Singapore Gratitude Task

grat_19 <- t.test(grat_sing$happy_all, grat_god_list$happy_all)
grat_19_ef <- effsize::cohen.d(grat_sing$happy_all, grat_god_list$happy_all, hedges.correction = TRUE)

grat_20 <- t.test(grat_sing$happy_all, grat_god_letter$happy_all)
grat_20_ef <- effsize::cohen.d(grat_sing$happy_all, grat_god_letter$happy_all, hedges.correction = TRUE)

#Gratitude to God

grat_21 <- t.test(grat_god_list$happy_all, grat_god_letter$happy_all)
grat_21_ef <- effsize::cohen.d(grat_god_list$happy_all, grat_god_letter$happy_all, hedges.correction = TRUE)

#Gratitude Conditions Graph

p_values_5 <- c(grat_1$p.value, grat_2$p.value, grat_3$p.value, grat_4$p.value, grat_5$p.value, grat_6$p.value, grat_7$p.value, grat_8$p.value, grat_9$p.value, grat_10$p.value, grat_11$p.value, grat_12$p.value, grat_13$p.value, grat_14$p.value, grat_15$p.value,grat_16$p.value, grat_17$p.value, grat_18$p.value, grat_19$p.value, grat_20$p.value,grat_21$p.value)
estimate_5 <- c(grat_1_ef$estimate, grat_2_ef$estimate, grat_3_ef$estimate, grat_4_ef$estimate, grat_5_ef$estimate, grat_6_ef$estimate, grat_7_ef$estimate, grat_8_ef$estimate, grat_9_ef$estimate, grat_10_ef$estimate, grat_11_ef$estimate, grat_12_ef$estimate, grat_13_ef$estimate, grat_14_ef$estimate, grat_15_ef$estimate,grat_16_ef$estimate, grat_17_ef$estimate, grat_18_ef$estimate, grat_19_ef$estimate, grat_20_ef$estimate,grat_21_ef$estimate)
statistic_5 <- c(grat_1$statistic, grat_2$statistic, grat_3$statistic, grat_4$statistic, grat_5$statistic, grat_6$statistic, grat_7$statistic, grat_8$statistic, grat_9$statistic, grat_10$statistic, grat_11$statistic, grat_12$statistic, grat_13$statistic, grat_14$statistic, grat_15$statistic,grat_16$statistic, grat_17$statistic, grat_18$statistic, grat_19$statistic, grat_20$statistic,grat_21$statistic)
parameter_5 <- c(grat_1$parameter, grat_2$parameter, grat_3$parameter, grat_4$parameter, grat_5$parameter, grat_6$parameter, grat_7$parameter, grat_8$parameter, grat_9$parameter, grat_10$parameter, grat_11$parameter, grat_12$parameter, grat_13$parameter, grat_14$parameter, grat_15$parameter,grat_16$parameter, grat_17$parameter, grat_18$parameter, grat_19$parameter, grat_20$parameter,grat_21$parameter)

#Table
table_data_5 <- data.frame(
  Condition = conditions_5,
  "t" = statistic_5,
  "df" = parameter_5,
  "p" = p_values_5, 
  "Hedges' g" = estimate_5)

print(table_data_5)

```

```{r control conditions}

#Comparing Across Control Conditions

#Control

con_1 <- t.test(control$happy_all, control_events$happy_all)
con_1_ef <- effsize::cohen.d(control$happy_all, control_events$happy_all, hedges.correction = TRUE)

con_2 <- t.test(control$happy_all, control_interesting$happy_all)
con_2_ef <- effsize::cohen.d(control$happy_all, control_interesting$happy_all, hedges.correction = TRUE)

con_3 <- t.test(control$happy_all, control_hassles$happy_all)
con_3_ef <- effsize::cohen.d(control$happy_all, control_hassles$happy_all, hedges.correction = TRUE)

#Control Events

con_4 <- t.test(control_events$happy_all, control_interesting$happy_all)
con_4_ef <- effsize::cohen.d(control_events$happy_all, control_interesting$happy_all, hedges.correction = TRUE)

con_5 <- t.test(control_events$happy_all, control_hassles$happy_all)
con_5_ef <- effsize::cohen.d(control_events$happy_all, control_hassles$happy_all, hedges.correction = TRUE)

#Control Interesting Events

con_6 <- t.test(control_interesting$happy_all, control_hassles$happy_all)
con_6_ef <- effsize::cohen.d(control_interesting$happy_all, control_hassles$happy_all, hedges.correction = TRUE)

#Control t-test Graph
p_values_6 <- c(con_1$p.value, con_2$p.value, con_3$p.value, con_4$p.value, con_5$p.value, con_6$p.value)
estimate_6 <- c(con_1_ef$estimate, con_2_ef$estimate, con_3_ef$estimate, con_4_ef$estimate, con_5_ef$estimate, con_6_ef$estimate)
statistic_6 <- c(con_1$statistic, con_2$statistic, con_3$statistic, con_4$statistic, con_5$statistic, con_6$statistic)
parameter_6 <- c(con_1$parameter, con_2$parameter, con_3$parameter, con_4$parameter, con_5$parameter, con_6$parameter)

#Table
table_data_6 <- data.frame(
  Condition = conditions_6,
  "t" = statistic_6,
  "df" = parameter_6,
  "p" = p_values_6, 
  "Hedges' g" = estimate_6)

print(table_data_6)

```


#t-Tests (State Optimisim)

```{r control}

control_1 <- t.test(control$optimistic_all, grat_list$optimistic_all)
control_1_ef <- effsize::cohen.d(control$optimistic_all, grat_list$optimistic_all, hedges.correction = TRUE)

control_2 <- t.test(control$optimistic_all, grat_letter$optimistic_all)
control_2_ef <- effsize::cohen.d(control$optimistic_all, grat_letter$optimistic_all, hedges.correction = TRUE)

control_3 <- t.test(control$optimistic_all, grat_text$optimistic_all)
control_3_ef <- effsize::cohen.d(control$optimistic_all, grat_text$optimistic_all, hedges.correction = TRUE)

control_4 <- t.test(control$optimistic_all, grat_hk$optimistic_all)
control_4_ef <- effsize::cohen.d(control$optimistic_all, grat_hk$optimistic_all, hedges.correction = TRUE)

control_5 <- t.test(control$optimistic_all, grat_sing$optimistic_all)
control_5_ef <- effsize::cohen.d(control$optimistic_all, grat_sing$optimistic_all, hedges.correction = TRUE)

control_6 <- t.test(control$optimistic_all, grat_sing$optimistic_all)
control_6_ef <- effsize::cohen.d(control$optimistic_all, grat_god_list$optimistic_all, hedges.correction = TRUE)

control_7 <- t.test(control$optimistic_all, grat_god_letter$optimistic_all)
control_7_ef <- effsize::cohen.d(control$optimistic_all, grat_god_letter$optimistic_all, hedges.correction = TRUE)

#Control t-test Graph

#Dataframe
p_values_1 <- c(control_1$p.value, control_2$p.value, control_3$p.value, control_4$p.value, control_5$p.value, control_6$p.value, control_7$p.value)
estimate_1 <- c(control_1_ef$estimate, control_2_ef$estimate, control_3_ef$estimate, control_4_ef$estimate, control_5_ef$estimate, control_6_ef$estimate, control_7_ef$estimate)
statistic_1 <- c(control_1$statistic, control_2$statistic, control_3$statistic, control_4$statistic, control_5$statistic, control_6$statistic, control_7$statistic)
parameter_1 <- c(control_1$parameter, control_2$parameter, control_3$parameter, control_4$parameter, control_5$parameter, control_6$parameter, control_7$parameter)

#Table
table_data_1 <- data.frame(
  Condition = conditions_1,
  "t" = statistic_1,
  "df" = parameter_1,
  "p" = p_values_1, 
  "Hedges' g" = estimate_1)

print(table_data_1)
```

```{r events}

#Events

events_1 <- t.test(control_events$optimistic_all, grat_list$optimistic_all)
events_1_ef <- effsize::cohen.d(control_events$optimistic_all, grat_list$optimistic_all, hedges.correction = TRUE)

events_2 <- t.test(control_events$optimistic_all, grat_letter$optimistic_all)
events_2_ef <- effsize::cohen.d(control_events$optimistic_all, grat_letter$optimistic_all, hedges.correction = TRUE)

events_3 <- t.test(control_events$optimistic_all, grat_text$optimistic_all)
events_3_ef <- effsize::cohen.d(control_events$optimistic_all, grat_text$optimistic_all, hedges.correction = TRUE)

events_4 <- t.test(control_events$optimistic_all, grat_hk$optimistic_all)
events_4_ef <- effsize::cohen.d(control_events$optimistic_all, grat_hk$optimistic_all, hedges.correction = TRUE)

events_5 <- t.test(control_events$optimistic_all, grat_sing$optimistic_all)
events_5_ef <- effsize::cohen.d(control_events$optimistic_all, grat_sing$optimistic_all, hedges.correction = TRUE)

events_6 <- t.test(control_events$optimistic_all, grat_god_list$optimistic_all)
events_6_ef <- effsize::cohen.d(control_events$optimistic_all, grat_god_list$optimistic_all, hedges.correction = TRUE)

events_7 <- t.test(control_events$optimistic_all, grat_god_letter$optimistic_all)
events_7_ef <- effsize::cohen.d(control_events$optimistic_all, grat_god_letter$optimistic_all, hedges.correction = TRUE)

#Control t-test Graph
p_values_2 <- c(events_1$p.value, events_2$p.value, events_3$p.value, events_4$p.value, events_5$p.value, events_6$p.value, events_7$p.value)
estimate_2 <- c(events_1_ef$estimate, events_2_ef$estimate, events_3_ef$estimate, events_4_ef$estimate, events_5_ef$estimate, events_6_ef$estimate, events_7_ef$estimate)
statistic_2 <- c(events_1$statistic, events_2$statistic, events_3$statistic, events_4$statistic, events_5$statistic, events_6$statistic, events_7$statistic)
parameter_2 <- c(events_1$parameter, events_2$parameter, events_3$parameter, events_4$parameter, events_5$parameter, events_6$parameter, events_7$parameter)

#Table
table_data_2 <- data.frame(
  Condition = conditions_2,
  "t" = statistic_2,
  "df" = parameter_2,
  "p" = p_values_2, 
  "Hedges' g" = estimate_2)

print(table_data_2)
```

```{r interesting events}

#Interesting Events

int_1 <- t.test(control_interesting$optimistic_all, grat_list$optimistic_all)
int_1_ef <- effsize::cohen.d(control_interesting$optimistic_all, grat_list$optimistic_all, hedges.correction = TRUE)

int_2 <- t.test(control_interesting$optimistic_all, grat_letter$optimistic_all)
int_2_ef <- effsize::cohen.d(control_interesting$optimistic_all, grat_letter$optimistic_all, hedges.correction = TRUE)

int_3 <- t.test(control_interesting$optimistic_all, grat_text$optimistic_all)
int_3_ef <- effsize::cohen.d(control_interesting$optimistic_all, grat_text$optimistic_all, hedges.correction = TRUE)

int_4 <- t.test(control_interesting$optimistic_all, grat_hk$optimistic_all)
int_4_ef <- effsize::cohen.d(control_interesting$optimistic_all, grat_hk$optimistic_all, hedges.correction = TRUE)

int_5 <- t.test(control_interesting$optimistic_all, grat_sing$optimistic_all)
int_5_ef <- effsize::cohen.d(control_interesting$optimistic_all, grat_sing$optimistic_all, hedges.correction = TRUE)

int_6 <- t.test(control_interesting$optimistic_all, grat_god_list$optimistic_all)
int_6_ef <- effsize::cohen.d(control_interesting$optimistic_all, grat_god_list$optimistic_all, hedges.correction = TRUE)

int_7 <- t.test(control_interesting$optimistic_all, grat_god_letter$optimistic_all)
int_7_ef <- effsize::cohen.d(control_interesting$optimistic_all, grat_god_letter$optimistic_all, hedges.correction = TRUE)

#Control t-test Graph
p_values_3 <- c(int_1$p.value, int_2$p.value, int_3$p.value, int_4$p.value, int_5$p.value, int_6$p.value, int_7$p.value)
estimate_3 <- c(int_1_ef$estimate, int_2_ef$estimate, int_3_ef$estimate, int_4_ef$estimate, int_5_ef$estimate, int_6_ef$estimate, int_7_ef$estimate)
statistic_3 <- c(int_1$statistic, int_2$statistic, int_3$statistic, int_4$statistic, int_5$statistic, int_6$statistic, int_7$statistic)
parameter_3 <- c(int_1$parameter, int_2$parameter, int_3$parameter, int_4$parameter, int_5$parameter, int_6$parameter, int_7$parameter)

#Table
table_data_3 <- data.frame(
  Condition = conditions_3,
  "t" = statistic_3,
  "df" = parameter_3,
  "p" = p_values_3, 
  "Hedges' g" = estimate_3)

print(table_data_3)
```

```{r hassles}

#Hassles

hassles_1 <- t.test(control_hassles$optimistic_all, grat_list$optimistic_all)
hassles_1_ef <- effsize::cohen.d(control_hassles$optimistic_all, grat_list$optimistic_all, hedges.correction = TRUE)

hassles_2 <- t.test(control_hassles$optimistic_all, grat_letter$optimistic_all)
hassles_2_ef <- effsize::cohen.d(control_hassles$optimistic_all, grat_letter$optimistic_all, hedges.correction = TRUE)

hassles_3 <- t.test(control_hassles$optimistic_all, grat_text$optimistic_all)
hassles_3_ef <- effsize::cohen.d(control_hassles$optimistic_all, grat_text$optimistic_all, hedges.correction = TRUE)

hassles_4 <- t.test(control_hassles$optimistic_all, grat_hk$optimistic_all)
hassles_4_ef <- effsize::cohen.d(control_hassles$optimistic_all, grat_hk$optimistic_all, hedges.correction = TRUE)

hassles_5 <- t.test(control_hassles$optimistic_all, grat_sing$optimistic_all)
hassles_5_ef <- effsize::cohen.d(control_hassles$optimistic_all, grat_sing$optimistic_all, hedges.correction = TRUE)

hassles_6 <- t.test(control_hassles$optimistic_all, grat_god_list$optimistic_all)
hassles_6_ef <- effsize::cohen.d(control_hassles$optimistic_all, grat_god_list$optimistic_all, hedges.correction = TRUE)

hassles_7 <- t.test(control_hassles$optimistic_all, grat_god_letter$optimistic_all)
hassles_7_ef <- effsize::cohen.d(control_hassles$optimistic_all, grat_god_letter$optimistic_all, hedges.correction = TRUE)

#Control t-test Graph

p_values_4 <- c(hassles_1$p.value, hassles_2$p.value, hassles_3$p.value, hassles_4$p.value, hassles_5$p.value, hassles_6$p.value, hassles_7$p.value)
estimate_4 <- c(hassles_1_ef$estimate, hassles_2_ef$estimate, hassles_3_ef$estimate, hassles_4_ef$estimate, hassles_5_ef$estimate, hassles_6_ef$estimate, hassles_7_ef$estimate)
statistic_4 <- c(hassles_1$statistic, hassles_2$statistic, hassles_3$statistic, hassles_4$statistic, hassles_5$statistic, hassles_6$statistic, hassles_7$statistic)
parameter_4 <- c(hassles_1$parameter, hassles_2$parameter, hassles_3$parameter, hassles_4$parameter, hassles_5$parameter, hassles_6$parameter, hassles_7$parameter)

#Table
table_data_4 <- data.frame(
  Condition = conditions_4,
  "t" = statistic_4,
  "df" = parameter_4,
  "p" = p_values_4, 
  "Hedges' g" = estimate_4)

print(table_data_4)
```

```{r gratitude conditions}

#Comparing Across Gratitude Conditions

#Gratitude List

grat_1 <- t.test(grat_list$optimistic_all, grat_letter$optimistic_all)
grat_1_ef <- effsize::cohen.d(grat_list$optimistic_all, grat_letter$optimistic_all, hedges.correction = TRUE)

grat_2 <- t.test(grat_list$optimistic_all, grat_text$optimistic_all)
grat_2_ef <- effsize::cohen.d(grat_list$optimistic_all, grat_text$optimistic_all, hedges.correction = TRUE)

grat_3 <- t.test(grat_list$optimistic_all, grat_hk$optimistic_all)
grat_3_ef <- effsize::cohen.d(grat_list$optimistic_all, grat_hk$optimistic_all, hedges.correction = TRUE)

grat_4 <- t.test(grat_list$optimistic_all, grat_sing$optimistic_all)
grat_4_ef <- effsize::cohen.d(grat_list$optimistic_all, grat_sing$optimistic_all, hedges.correction = TRUE)

grat_5 <- t.test(grat_list$optimistic_all, grat_god_list$optimistic_all)
grat_5_ef <- effsize::cohen.d(grat_list$optimistic_all, grat_list$optimistic_all, hedges.correction = TRUE)

grat_6 <- t.test(grat_list$optimistic_all, grat_god_letter$optimistic_all)
grat_6_ef <- effsize::cohen.d(grat_list$optimistic_all, grat_god_letter$optimistic_all, hedges.correction = TRUE)

#Gratitude Letter

grat_7 <- t.test(grat_letter$optimistic_all, grat_text$optimistic_all)
grat_7_ef <- effsize::cohen.d(grat_letter$optimistic_all, grat_text$optimistic_all, hedges.correction = TRUE)

grat_8 <- t.test(grat_letter$optimistic_all, grat_hk$optimistic_all)
grat_8_ef <- effsize::cohen.d(grat_letter$optimistic_all, grat_hk$optimistic_all, hedges.correction = TRUE)

grat_9 <- t.test(grat_letter$optimistic_all, grat_sing$optimistic_all)
grat_9_ef <- effsize::cohen.d(grat_letter$optimistic_all, grat_sing$optimistic_all, hedges.correction = TRUE)

grat_10 <- t.test(grat_letter$optimistic_all, grat_god_list$optimistic_all)
grat_10_ef <- effsize::cohen.d(grat_letter$optimistic_all, grat_god_list$optimistic_all, hedges.correction = TRUE)

grat_11 <- t.test(grat_letter$optimistic_all, grat_god_letter$optimistic_all)
grat_11_ef <- effsize::cohen.d(grat_letter$optimistic_all, grat_god_letter$optimistic_all, hedges.correction = TRUE)

#Gratitude Text

grat_12 <- t.test(grat_text$optimistic_all, grat_hk$optimistic_all)
grat_12_ef <- effsize::cohen.d(grat_text$optimistic_all, grat_hk$optimistic_all, hedges.correction = TRUE)

grat_13 <- t.test(grat_text$optimistic_all, grat_sing$optimistic_all)
grat_13_ef <- effsize::cohen.d(grat_text$optimistic_all, grat_sing$optimistic_all, hedges.correction = TRUE)

grat_14 <- t.test(grat_text$optimistic_all, grat_god_list$optimistic_all)
grat_14_ef <- effsize::cohen.d(grat_text$optimistic_all, grat_god_list$optimistic_all, hedges.correction = TRUE)

grat_15 <- t.test(grat_text$optimistic_all, grat_god_letter$optimistic_all)
grat_15_ef <- effsize::cohen.d(grat_text$optimistic_all, grat_god_letter$optimistic_all, hedges.correction = TRUE)

#Chan Gratitude List

grat_16 <- t.test(grat_hk$optimistic_all, grat_sing$optimistic_all)
grat_16_ef <- effsize::cohen.d(grat_hk$optimistic_all, grat_sing$optimistic_all, hedges.correction = TRUE)

grat_17 <- t.test(grat_hk$optimistic_all, grat_god_list$optimistic_all)
grat_17_ef <- effsize::cohen.d(grat_hk$optimistic_all, grat_god_list$optimistic_all, hedges.correction = TRUE)

grat_18 <- t.test(grat_hk$optimistic_all, grat_god_letter$optimistic_all)
grat_18_ef <- effsize::cohen.d(grat_hk$optimistic_all, grat_god_letter$optimistic_all, hedges.correction = TRUE)

#Singapore Gratitude Task

grat_19 <- t.test(grat_sing$optimistic_all, grat_god_list$optimistic_all)
grat_19_ef <- effsize::cohen.d(grat_sing$optimistic_all, grat_god_list$optimistic_all, hedges.correction = TRUE)

grat_20 <- t.test(grat_sing$optimistic_all, grat_god_letter$optimistic_all)
grat_20_ef <- effsize::cohen.d(grat_sing$optimistic_all, grat_god_letter$optimistic_all, hedges.correction = TRUE)

#Gratitude to God

grat_21 <- t.test(grat_god_list$optimistic_all, grat_god_letter$optimistic_all)
grat_21_ef <- effsize::cohen.d(grat_god_list$optimistic_all, grat_god_letter$optimistic_all, hedges.correction = TRUE)

#Gratitude Conditions Graph

p_values_5 <- c(grat_1$p.value, grat_2$p.value, grat_3$p.value, grat_4$p.value, grat_5$p.value, grat_6$p.value, grat_7$p.value, grat_8$p.value, grat_9$p.value, grat_10$p.value, grat_11$p.value, grat_12$p.value, grat_13$p.value, grat_14$p.value, grat_15$p.value,grat_16$p.value, grat_17$p.value, grat_18$p.value, grat_19$p.value, grat_20$p.value,grat_21$p.value)
estimate_5 <- c(grat_1_ef$estimate, grat_2_ef$estimate, grat_3_ef$estimate, grat_4_ef$estimate, grat_5_ef$estimate, grat_6_ef$estimate, grat_7_ef$estimate, grat_8_ef$estimate, grat_9_ef$estimate, grat_10_ef$estimate, grat_11_ef$estimate, grat_12_ef$estimate, grat_13_ef$estimate, grat_14_ef$estimate, grat_15_ef$estimate,grat_16_ef$estimate, grat_17_ef$estimate, grat_18_ef$estimate, grat_19_ef$estimate, grat_20_ef$estimate,grat_21_ef$estimate)
statistic_5 <- c(grat_1$statistic, grat_2$statistic, grat_3$statistic, grat_4$statistic, grat_5$statistic, grat_6$statistic, grat_7$statistic, grat_8$statistic, grat_9$statistic, grat_10$statistic, grat_11$statistic, grat_12$statistic, grat_13$statistic, grat_14$statistic, grat_15$statistic,grat_16$statistic, grat_17$statistic, grat_18$statistic, grat_19$statistic, grat_20$statistic,grat_21$statistic)
parameter_5 <- c(grat_1$parameter, grat_2$parameter, grat_3$parameter, grat_4$parameter, grat_5$parameter, grat_6$parameter, grat_7$parameter, grat_8$parameter, grat_9$parameter, grat_10$parameter, grat_11$parameter, grat_12$parameter, grat_13$parameter, grat_14$parameter, grat_15$parameter,grat_16$parameter, grat_17$parameter, grat_18$parameter, grat_19$parameter, grat_20$parameter,grat_21$parameter)

#Table
table_data_5 <- data.frame(
  Condition = conditions_5,
  "t" = statistic_5,
  "df" = parameter_5,
  "p" = p_values_5, 
  "Hedges' g" = estimate_5)

print(table_data_5)

```

```{r control conditions}

#Comparing Across Control Conditions

#Control

con_1 <- t.test(control$optimistic_all, control_events$optimistic_all)
con_1_ef <- effsize::cohen.d(control$optimistic_all, control_events$optimistic_all, hedges.correction = TRUE)

con_2 <- t.test(control$optimistic_all, control_interesting$optimistic_all)
con_2_ef <- effsize::cohen.d(control$optimistic_all, control_interesting$optimistic_all, hedges.correction = TRUE)

con_3 <- t.test(control$optimistic_all, control_hassles$optimistic_all)
con_3_ef <- effsize::cohen.d(control$optimistic_all, control_hassles$optimistic_all, hedges.correction = TRUE)

#Control Events

con_4 <- t.test(control_events$optimistic_all, control_interesting$optimistic_all)
con_4_ef <- effsize::cohen.d(control_events$optimistic_all, control_interesting$optimistic_all, hedges.correction = TRUE)

con_5 <- t.test(control_events$optimistic_all, control_hassles$optimistic_all)
con_5_ef <- effsize::cohen.d(control_events$optimistic_all, control_hassles$optimistic_all, hedges.correction = TRUE)

#Control Interesting Events

con_6 <- t.test(control_interesting$optimistic_all, control_hassles$optimistic_all)
con_6_ef <- effsize::cohen.d(control_interesting$optimistic_all, control_hassles$optimistic_all, hedges.correction = TRUE)

#Control t-test Graph
p_values_6 <- c(con_1$p.value, con_2$p.value, con_3$p.value, con_4$p.value, con_5$p.value, con_6$p.value)
estimate_6 <- c(con_1_ef$estimate, con_2_ef$estimate, con_3_ef$estimate, con_4_ef$estimate, con_5_ef$estimate, con_6_ef$estimate)
statistic_6 <- c(con_1$statistic, con_2$statistic, con_3$statistic, con_4$statistic, con_5$statistic, con_6$statistic)
parameter_6 <- c(con_1$parameter, con_2$parameter, con_3$parameter, con_4$parameter, con_5$parameter, con_6$parameter)

#Table
table_data_6 <- data.frame(
  Condition = conditions_6,
  "t" = statistic_6,
  "df" = parameter_6,
  "p" = p_values_6, 
  "Hedges' g" = estimate_6)

print(table_data_6)

```


#t-Tests (State Sadness)

```{r control}

control_1 <- t.test(control$sad_all, grat_list$sad_all)
control_1_ef <- effsize::cohen.d(control$sad_all, grat_list$sad_all, hedges.correction = TRUE)

control_2 <- t.test(control$sad_all, grat_letter$sad_all)
control_2_ef <- effsize::cohen.d(control$sad_all, grat_letter$sad_all, hedges.correction = TRUE)

control_3 <- t.test(control$sad_all, grat_text$sad_all)
control_3_ef <- effsize::cohen.d(control$sad_all, grat_text$sad_all, hedges.correction = TRUE)

control_4 <- t.test(control$sad_all, grat_hk$sad_all)
control_4_ef <- effsize::cohen.d(control$sad_all, grat_hk$sad_all, hedges.correction = TRUE)

control_5 <- t.test(control$sad_all, grat_sing$sad_all)
control_5_ef <- effsize::cohen.d(control$sad_all, grat_sing$sad_all, hedges.correction = TRUE)

control_6 <- t.test(control$sad_all, grat_sing$sad_all)
control_6_ef <- effsize::cohen.d(control$sad_all, grat_god_list$sad_all, hedges.correction = TRUE)

control_7 <- t.test(control$sad_all, grat_god_letter$sad_all)
control_7_ef <- effsize::cohen.d(control$sad_all, grat_god_letter$sad_all, hedges.correction = TRUE)

#Control t-test Graph

#Dataframe
p_values_1 <- c(control_1$p.value, control_2$p.value, control_3$p.value, control_4$p.value, control_5$p.value, control_6$p.value, control_7$p.value)
estimate_1 <- c(control_1_ef$estimate, control_2_ef$estimate, control_3_ef$estimate, control_4_ef$estimate, control_5_ef$estimate, control_6_ef$estimate, control_7_ef$estimate)
statistic_1 <- c(control_1$statistic, control_2$statistic, control_3$statistic, control_4$statistic, control_5$statistic, control_6$statistic, control_7$statistic)
parameter_1 <- c(control_1$parameter, control_2$parameter, control_3$parameter, control_4$parameter, control_5$parameter, control_6$parameter, control_7$parameter)

#Table
table_data_1 <- data.frame(
  Condition = conditions_1,
  "t" = statistic_1,
  "df" = parameter_1,
  "p" = p_values_1, 
  "Hedges' g" = estimate_1)

print(table_data_1)
```

```{r events}

#Events

events_1 <- t.test(control_events$sad_all, grat_list$sad_all)
events_1_ef <- effsize::cohen.d(control_events$sad_all, grat_list$sad_all, hedges.correction = TRUE)

events_2 <- t.test(control_events$sad_all, grat_letter$sad_all)
events_2_ef <- effsize::cohen.d(control_events$sad_all, grat_letter$sad_all, hedges.correction = TRUE)

events_3 <- t.test(control_events$sad_all, grat_text$sad_all)
events_3_ef <- effsize::cohen.d(control_events$sad_all, grat_text$sad_all, hedges.correction = TRUE)

events_4 <- t.test(control_events$sad_all, grat_hk$sad_all)
events_4_ef <- effsize::cohen.d(control_events$sad_all, grat_hk$sad_all, hedges.correction = TRUE)

events_5 <- t.test(control_events$sad_all, grat_sing$sad_all)
events_5_ef <- effsize::cohen.d(control_events$sad_all, grat_sing$sad_all, hedges.correction = TRUE)

events_6 <- t.test(control_events$sad_all, grat_god_list$sad_all)
events_6_ef <- effsize::cohen.d(control_events$sad_all, grat_god_list$sad_all, hedges.correction = TRUE)

events_7 <- t.test(control_events$sad_all, grat_god_letter$sad_all)
events_7_ef <- effsize::cohen.d(control_events$sad_all, grat_god_letter$sad_all, hedges.correction = TRUE)

#Control t-test Graph
p_values_2 <- c(events_1$p.value, events_2$p.value, events_3$p.value, events_4$p.value, events_5$p.value, events_6$p.value, events_7$p.value)
estimate_2 <- c(events_1_ef$estimate, events_2_ef$estimate, events_3_ef$estimate, events_4_ef$estimate, events_5_ef$estimate, events_6_ef$estimate, events_7_ef$estimate)
statistic_2 <- c(events_1$statistic, events_2$statistic, events_3$statistic, events_4$statistic, events_5$statistic, events_6$statistic, events_7$statistic)
parameter_2 <- c(events_1$parameter, events_2$parameter, events_3$parameter, events_4$parameter, events_5$parameter, events_6$parameter, events_7$parameter)

#Table
table_data_2 <- data.frame(
  Condition = conditions_2,
  "t" = statistic_2,
  "df" = parameter_2,
  "p" = p_values_2, 
  "Hedges' g" = estimate_2)

print(table_data_2)
```

```{r interesting events}

#Interesting Events

int_1 <- t.test(control_interesting$sad_all, grat_list$sad_all)
int_1_ef <- effsize::cohen.d(control_interesting$sad_all, grat_list$sad_all, hedges.correction = TRUE)

int_2 <- t.test(control_interesting$sad_all, grat_letter$sad_all)
int_2_ef <- effsize::cohen.d(control_interesting$sad_all, grat_letter$sad_all, hedges.correction = TRUE)

int_3 <- t.test(control_interesting$sad_all, grat_text$sad_all)
int_3_ef <- effsize::cohen.d(control_interesting$sad_all, grat_text$sad_all, hedges.correction = TRUE)

int_4 <- t.test(control_interesting$sad_all, grat_hk$sad_all)
int_4_ef <- effsize::cohen.d(control_interesting$sad_all, grat_hk$sad_all, hedges.correction = TRUE)

int_5 <- t.test(control_interesting$sad_all, grat_sing$sad_all)
int_5_ef <- effsize::cohen.d(control_interesting$sad_all, grat_sing$sad_all, hedges.correction = TRUE)

int_6 <- t.test(control_interesting$sad_all, grat_god_list$sad_all)
int_6_ef <- effsize::cohen.d(control_interesting$sad_all, grat_god_list$sad_all, hedges.correction = TRUE)

int_7 <- t.test(control_interesting$sad_all, grat_god_letter$sad_all)
int_7_ef <- effsize::cohen.d(control_interesting$sad_all, grat_god_letter$sad_all, hedges.correction = TRUE)

#Control t-test Graph
p_values_3 <- c(int_1$p.value, int_2$p.value, int_3$p.value, int_4$p.value, int_5$p.value, int_6$p.value, int_7$p.value)
estimate_3 <- c(int_1_ef$estimate, int_2_ef$estimate, int_3_ef$estimate, int_4_ef$estimate, int_5_ef$estimate, int_6_ef$estimate, int_7_ef$estimate)
statistic_3 <- c(int_1$statistic, int_2$statistic, int_3$statistic, int_4$statistic, int_5$statistic, int_6$statistic, int_7$statistic)
parameter_3 <- c(int_1$parameter, int_2$parameter, int_3$parameter, int_4$parameter, int_5$parameter, int_6$parameter, int_7$parameter)

#Table
table_data_3 <- data.frame(
  Condition = conditions_3,
  "t" = statistic_3,
  "df" = parameter_3,
  "p" = p_values_3, 
  "Hedges' g" = estimate_3)

print(table_data_3)
```

```{r hassles}

#Hassles

hassles_1 <- t.test(control_hassles$sad_all, grat_list$sad_all)
hassles_1_ef <- effsize::cohen.d(control_hassles$sad_all, grat_list$sad_all, hedges.correction = TRUE)

hassles_2 <- t.test(control_hassles$sad_all, grat_letter$sad_all)
hassles_2_ef <- effsize::cohen.d(control_hassles$sad_all, grat_letter$sad_all, hedges.correction = TRUE)

hassles_3 <- t.test(control_hassles$sad_all, grat_text$sad_all)
hassles_3_ef <- effsize::cohen.d(control_hassles$sad_all, grat_text$sad_all, hedges.correction = TRUE)

hassles_4 <- t.test(control_hassles$sad_all, grat_hk$sad_all)
hassles_4_ef <- effsize::cohen.d(control_hassles$sad_all, grat_hk$sad_all, hedges.correction = TRUE)

hassles_5 <- t.test(control_hassles$sad_all, grat_sing$sad_all)
hassles_5_ef <- effsize::cohen.d(control_hassles$sad_all, grat_sing$sad_all, hedges.correction = TRUE)

hassles_6 <- t.test(control_hassles$sad_all, grat_god_list$sad_all)
hassles_6_ef <- effsize::cohen.d(control_hassles$sad_all, grat_god_list$sad_all, hedges.correction = TRUE)

hassles_7 <- t.test(control_hassles$sad_all, grat_god_letter$sad_all)
hassles_7_ef <- effsize::cohen.d(control_hassles$sad_all, grat_god_letter$sad_all, hedges.correction = TRUE)

#Control t-test Graph

p_values_4 <- c(hassles_1$p.value, hassles_2$p.value, hassles_3$p.value, hassles_4$p.value, hassles_5$p.value, hassles_6$p.value, hassles_7$p.value)
estimate_4 <- c(hassles_1_ef$estimate, hassles_2_ef$estimate, hassles_3_ef$estimate, hassles_4_ef$estimate, hassles_5_ef$estimate, hassles_6_ef$estimate, hassles_7_ef$estimate)
statistic_4 <- c(hassles_1$statistic, hassles_2$statistic, hassles_3$statistic, hassles_4$statistic, hassles_5$statistic, hassles_6$statistic, hassles_7$statistic)
parameter_4 <- c(hassles_1$parameter, hassles_2$parameter, hassles_3$parameter, hassles_4$parameter, hassles_5$parameter, hassles_6$parameter, hassles_7$parameter)

#Table
table_data_4 <- data.frame(
  Condition = conditions_4,
  "t" = statistic_4,
  "df" = parameter_4,
  "p" = p_values_4, 
  "Hedges' g" = estimate_4)

print(table_data_4)
```

```{r gratitude conditions}

#Comparing Across Gratitude Conditions

#Gratitude List

grat_1 <- t.test(grat_list$sad_all, grat_letter$sad_all)
grat_1_ef <- effsize::cohen.d(grat_list$sad_all, grat_letter$sad_all, hedges.correction = TRUE)

grat_2 <- t.test(grat_list$sad_all, grat_text$sad_all)
grat_2_ef <- effsize::cohen.d(grat_list$sad_all, grat_text$sad_all, hedges.correction = TRUE)

grat_3 <- t.test(grat_list$sad_all, grat_hk$sad_all)
grat_3_ef <- effsize::cohen.d(grat_list$sad_all, grat_hk$sad_all, hedges.correction = TRUE)

grat_4 <- t.test(grat_list$sad_all, grat_sing$sad_all)
grat_4_ef <- effsize::cohen.d(grat_list$sad_all, grat_sing$sad_all, hedges.correction = TRUE)

grat_5 <- t.test(grat_list$sad_all, grat_god_list$sad_all)
grat_5_ef <- effsize::cohen.d(grat_list$sad_all, grat_list$sad_all, hedges.correction = TRUE)

grat_6 <- t.test(grat_list$sad_all, grat_god_letter$sad_all)
grat_6_ef <- effsize::cohen.d(grat_list$sad_all, grat_god_letter$sad_all, hedges.correction = TRUE)

#Gratitude Letter

grat_7 <- t.test(grat_letter$sad_all, grat_text$sad_all)
grat_7_ef <- effsize::cohen.d(grat_letter$sad_all, grat_text$sad_all, hedges.correction = TRUE)

grat_8 <- t.test(grat_letter$sad_all, grat_hk$sad_all)
grat_8_ef <- effsize::cohen.d(grat_letter$sad_all, grat_hk$sad_all, hedges.correction = TRUE)

grat_9 <- t.test(grat_letter$sad_all, grat_sing$sad_all)
grat_9_ef <- effsize::cohen.d(grat_letter$sad_all, grat_sing$sad_all, hedges.correction = TRUE)

grat_10 <- t.test(grat_letter$sad_all, grat_god_list$sad_all)
grat_10_ef <- effsize::cohen.d(grat_letter$sad_all, grat_god_list$sad_all, hedges.correction = TRUE)

grat_11 <- t.test(grat_letter$sad_all, grat_god_letter$sad_all)
grat_11_ef <- effsize::cohen.d(grat_letter$sad_all, grat_god_letter$sad_all, hedges.correction = TRUE)

#Gratitude Text

grat_12 <- t.test(grat_text$sad_all, grat_hk$sad_all)
grat_12_ef <- effsize::cohen.d(grat_text$sad_all, grat_hk$sad_all, hedges.correction = TRUE)

grat_13 <- t.test(grat_text$sad_all, grat_sing$sad_all)
grat_13_ef <- effsize::cohen.d(grat_text$sad_all, grat_sing$sad_all, hedges.correction = TRUE)

grat_14 <- t.test(grat_text$sad_all, grat_god_list$sad_all)
grat_14_ef <- effsize::cohen.d(grat_text$sad_all, grat_god_list$sad_all, hedges.correction = TRUE)

grat_15 <- t.test(grat_text$sad_all, grat_god_letter$sad_all)
grat_15_ef <- effsize::cohen.d(grat_text$sad_all, grat_god_letter$sad_all, hedges.correction = TRUE)

#Chan Gratitude List

grat_16 <- t.test(grat_hk$sad_all, grat_sing$sad_all)
grat_16_ef <- effsize::cohen.d(grat_hk$sad_all, grat_sing$sad_all, hedges.correction = TRUE)

grat_17 <- t.test(grat_hk$sad_all, grat_god_list$sad_all)
grat_17_ef <- effsize::cohen.d(grat_hk$sad_all, grat_god_list$sad_all, hedges.correction = TRUE)

grat_18 <- t.test(grat_hk$sad_all, grat_god_letter$sad_all)
grat_18_ef <- effsize::cohen.d(grat_hk$sad_all, grat_god_letter$sad_all, hedges.correction = TRUE)

#Singapore Gratitude Task

grat_19 <- t.test(grat_sing$sad_all, grat_god_list$sad_all)
grat_19_ef <- effsize::cohen.d(grat_sing$sad_all, grat_god_list$sad_all, hedges.correction = TRUE)

grat_20 <- t.test(grat_sing$sad_all, grat_god_letter$sad_all)
grat_20_ef <- effsize::cohen.d(grat_sing$sad_all, grat_god_letter$sad_all, hedges.correction = TRUE)

#Gratitude to God

grat_21 <- t.test(grat_god_list$sad_all, grat_god_letter$sad_all)
grat_21_ef <- effsize::cohen.d(grat_god_list$sad_all, grat_god_letter$sad_all, hedges.correction = TRUE)

#Gratitude Conditions Graph

p_values_5 <- c(grat_1$p.value, grat_2$p.value, grat_3$p.value, grat_4$p.value, grat_5$p.value, grat_6$p.value, grat_7$p.value, grat_8$p.value, grat_9$p.value, grat_10$p.value, grat_11$p.value, grat_12$p.value, grat_13$p.value, grat_14$p.value, grat_15$p.value,grat_16$p.value, grat_17$p.value, grat_18$p.value, grat_19$p.value, grat_20$p.value,grat_21$p.value)
estimate_5 <- c(grat_1_ef$estimate, grat_2_ef$estimate, grat_3_ef$estimate, grat_4_ef$estimate, grat_5_ef$estimate, grat_6_ef$estimate, grat_7_ef$estimate, grat_8_ef$estimate, grat_9_ef$estimate, grat_10_ef$estimate, grat_11_ef$estimate, grat_12_ef$estimate, grat_13_ef$estimate, grat_14_ef$estimate, grat_15_ef$estimate,grat_16_ef$estimate, grat_17_ef$estimate, grat_18_ef$estimate, grat_19_ef$estimate, grat_20_ef$estimate,grat_21_ef$estimate)
statistic_5 <- c(grat_1$statistic, grat_2$statistic, grat_3$statistic, grat_4$statistic, grat_5$statistic, grat_6$statistic, grat_7$statistic, grat_8$statistic, grat_9$statistic, grat_10$statistic, grat_11$statistic, grat_12$statistic, grat_13$statistic, grat_14$statistic, grat_15$statistic,grat_16$statistic, grat_17$statistic, grat_18$statistic, grat_19$statistic, grat_20$statistic,grat_21$statistic)
parameter_5 <- c(grat_1$parameter, grat_2$parameter, grat_3$parameter, grat_4$parameter, grat_5$parameter, grat_6$parameter, grat_7$parameter, grat_8$parameter, grat_9$parameter, grat_10$parameter, grat_11$parameter, grat_12$parameter, grat_13$parameter, grat_14$parameter, grat_15$parameter,grat_16$parameter, grat_17$parameter, grat_18$parameter, grat_19$parameter, grat_20$parameter,grat_21$parameter)

#Table
table_data_5 <- data.frame(
  Condition = conditions_5,
  "t" = statistic_5,
  "df" = parameter_5,
  "p" = p_values_5, 
  "Hedges' g" = estimate_5)

print(table_data_5)

```

```{r control conditions}

#Comparing Across Control Conditions

#Control

con_1 <- t.test(control$sad_all, control_events$sad_all)
con_1_ef <- effsize::cohen.d(control$sad_all, control_events$sad_all, hedges.correction = TRUE)

con_2 <- t.test(control$sad_all, control_interesting$sad_all)
con_2_ef <- effsize::cohen.d(control$sad_all, control_interesting$sad_all, hedges.correction = TRUE)

con_3 <- t.test(control$sad_all, control_hassles$sad_all)
con_3_ef <- effsize::cohen.d(control$sad_all, control_hassles$sad_all, hedges.correction = TRUE)

#Control Events

con_4 <- t.test(control_events$sad_all, control_interesting$sad_all)
con_4_ef <- effsize::cohen.d(control_events$sad_all, control_interesting$sad_all, hedges.correction = TRUE)

con_5 <- t.test(control_events$sad_all, control_hassles$sad_all)
con_5_ef <- effsize::cohen.d(control_events$sad_all, control_hassles$sad_all, hedges.correction = TRUE)

#Control Interesting Events

con_6 <- t.test(control_interesting$sad_all, control_hassles$sad_all)
con_6_ef <- effsize::cohen.d(control_interesting$sad_all, control_hassles$sad_all, hedges.correction = TRUE)

#Control t-test Graph
p_values_6 <- c(con_1$p.value, con_2$p.value, con_3$p.value, con_4$p.value, con_5$p.value, con_6$p.value)
estimate_6 <- c(con_1_ef$estimate, con_2_ef$estimate, con_3_ef$estimate, con_4_ef$estimate, con_5_ef$estimate, con_6_ef$estimate)
statistic_6 <- c(con_1$statistic, con_2$statistic, con_3$statistic, con_4$statistic, con_5$statistic, con_6$statistic)
parameter_6 <- c(con_1$parameter, con_2$parameter, con_3$parameter, con_4$parameter, con_5$parameter, con_6$parameter)

#Table
table_data_6 <- data.frame(
  Condition = conditions_6,
  "t" = statistic_6,
  "df" = parameter_6,
  "p" = p_values_6, 
  "Hedges' g" = estimate_6)

print(table_data_6)

```

#t-Tests (State Indebtedness)

```{r control}

control_1 <- t.test(control$indebted_all, grat_list$indebted_all)
control_1_ef <- effsize::cohen.d(control$indebted_all, grat_list$indebted_all, hedges.correction = TRUE)

control_2 <- t.test(control$indebted_all, grat_letter$indebted_all)
control_2_ef <- effsize::cohen.d(control$indebted_all, grat_letter$indebted_all, hedges.correction = TRUE)

control_3 <- t.test(control$indebted_all, grat_text$indebted_all)
control_3_ef <- effsize::cohen.d(control$indebted_all, grat_text$indebted_all, hedges.correction = TRUE)

control_4 <- t.test(control$indebted_all, grat_hk$indebted_all)
control_4_ef <- effsize::cohen.d(control$indebted_all, grat_hk$indebted_all, hedges.correction = TRUE)

control_5 <- t.test(control$indebted_all, grat_sing$indebted_all)
control_5_ef <- effsize::cohen.d(control$indebted_all, grat_sing$indebted_all, hedges.correction = TRUE)

control_6 <- t.test(control$indebted_all, grat_sing$indebted_all)
control_6_ef <- effsize::cohen.d(control$indebted_all, grat_god_list$indebted_all, hedges.correction = TRUE)

control_7 <- t.test(control$indebted_all, grat_god_letter$indebted_all)
control_7_ef <- effsize::cohen.d(control$indebted_all, grat_god_letter$indebted_all, hedges.correction = TRUE)

#Control t-test Graph

#Dataframe
p_values_1 <- c(control_1$p.value, control_2$p.value, control_3$p.value, control_4$p.value, control_5$p.value, control_6$p.value, control_7$p.value)
estimate_1 <- c(control_1_ef$estimate, control_2_ef$estimate, control_3_ef$estimate, control_4_ef$estimate, control_5_ef$estimate, control_6_ef$estimate, control_7_ef$estimate)
statistic_1 <- c(control_1$statistic, control_2$statistic, control_3$statistic, control_4$statistic, control_5$statistic, control_6$statistic, control_7$statistic)
parameter_1 <- c(control_1$parameter, control_2$parameter, control_3$parameter, control_4$parameter, control_5$parameter, control_6$parameter, control_7$parameter)

#Table
table_data_1 <- data.frame(
  Condition = conditions_1,
  "t" = statistic_1,
  "df" = parameter_1,
  "p" = p_values_1, 
  "Hedges' g" = estimate_1)

print(table_data_1)
```

```{r events}

#Events

events_1 <- t.test(control_events$indebted_all, grat_list$indebted_all)
events_1_ef <- effsize::cohen.d(control_events$indebted_all, grat_list$indebted_all, hedges.correction = TRUE)

events_2 <- t.test(control_events$indebted_all, grat_letter$indebted_all)
events_2_ef <- effsize::cohen.d(control_events$indebted_all, grat_letter$indebted_all, hedges.correction = TRUE)

events_3 <- t.test(control_events$indebted_all, grat_text$indebted_all)
events_3_ef <- effsize::cohen.d(control_events$indebted_all, grat_text$indebted_all, hedges.correction = TRUE)

events_4 <- t.test(control_events$indebted_all, grat_hk$indebted_all)
events_4_ef <- effsize::cohen.d(control_events$indebted_all, grat_hk$indebted_all, hedges.correction = TRUE)

events_5 <- t.test(control_events$indebted_all, grat_sing$indebted_all)
events_5_ef <- effsize::cohen.d(control_events$indebted_all, grat_sing$indebted_all, hedges.correction = TRUE)

events_6 <- t.test(control_events$indebted_all, grat_god_list$indebted_all)
events_6_ef <- effsize::cohen.d(control_events$indebted_all, grat_god_list$indebted_all, hedges.correction = TRUE)

events_7 <- t.test(control_events$indebted_all, grat_god_letter$indebted_all)
events_7_ef <- effsize::cohen.d(control_events$indebted_all, grat_god_letter$indebted_all, hedges.correction = TRUE)

#Control t-test Graph
p_values_2 <- c(events_1$p.value, events_2$p.value, events_3$p.value, events_4$p.value, events_5$p.value, events_6$p.value, events_7$p.value)
estimate_2 <- c(events_1_ef$estimate, events_2_ef$estimate, events_3_ef$estimate, events_4_ef$estimate, events_5_ef$estimate, events_6_ef$estimate, events_7_ef$estimate)
statistic_2 <- c(events_1$statistic, events_2$statistic, events_3$statistic, events_4$statistic, events_5$statistic, events_6$statistic, events_7$statistic)
parameter_2 <- c(events_1$parameter, events_2$parameter, events_3$parameter, events_4$parameter, events_5$parameter, events_6$parameter, events_7$parameter)

#Table
table_data_2 <- data.frame(
  Condition = conditions_2,
  "t" = statistic_2,
  "df" = parameter_2,
  "p" = p_values_2, 
  "Hedges' g" = estimate_2)

print(table_data_2)
```

```{r interesting events}

#Interesting Events

int_1 <- t.test(control_interesting$indebted_all, grat_list$indebted_all)
int_1_ef <- effsize::cohen.d(control_interesting$indebted_all, grat_list$indebted_all, hedges.correction = TRUE)

int_2 <- t.test(control_interesting$indebted_all, grat_letter$indebted_all)
int_2_ef <- effsize::cohen.d(control_interesting$indebted_all, grat_letter$indebted_all, hedges.correction = TRUE)

int_3 <- t.test(control_interesting$indebted_all, grat_text$indebted_all)
int_3_ef <- effsize::cohen.d(control_interesting$indebted_all, grat_text$indebted_all, hedges.correction = TRUE)

int_4 <- t.test(control_interesting$indebted_all, grat_hk$indebted_all)
int_4_ef <- effsize::cohen.d(control_interesting$indebted_all, grat_hk$indebted_all, hedges.correction = TRUE)

int_5 <- t.test(control_interesting$indebted_all, grat_sing$indebted_all)
int_5_ef <- effsize::cohen.d(control_interesting$indebted_all, grat_sing$indebted_all, hedges.correction = TRUE)

int_6 <- t.test(control_interesting$indebted_all, grat_god_list$indebted_all)
int_6_ef <- effsize::cohen.d(control_interesting$indebted_all, grat_god_list$indebted_all, hedges.correction = TRUE)

int_7 <- t.test(control_interesting$indebted_all, grat_god_letter$indebted_all)
int_7_ef <- effsize::cohen.d(control_interesting$indebted_all, grat_god_letter$indebted_all, hedges.correction = TRUE)

#Control t-test Graph
p_values_3 <- c(int_1$p.value, int_2$p.value, int_3$p.value, int_4$p.value, int_5$p.value, int_6$p.value, int_7$p.value)
estimate_3 <- c(int_1_ef$estimate, int_2_ef$estimate, int_3_ef$estimate, int_4_ef$estimate, int_5_ef$estimate, int_6_ef$estimate, int_7_ef$estimate)
statistic_3 <- c(int_1$statistic, int_2$statistic, int_3$statistic, int_4$statistic, int_5$statistic, int_6$statistic, int_7$statistic)
parameter_3 <- c(int_1$parameter, int_2$parameter, int_3$parameter, int_4$parameter, int_5$parameter, int_6$parameter, int_7$parameter)

#Table
table_data_3 <- data.frame(
  Condition = conditions_3,
  "t" = statistic_3,
  "df" = parameter_3,
  "p" = p_values_3, 
  "Hedges' g" = estimate_3)

print(table_data_3)
```

```{r hassles}

#Hassles

hassles_1 <- t.test(control_hassles$indebted_all, grat_list$indebted_all)
hassles_1_ef <- effsize::cohen.d(control_hassles$indebted_all, grat_list$indebted_all, hedges.correction = TRUE)

hassles_2 <- t.test(control_hassles$indebted_all, grat_letter$indebted_all)
hassles_2_ef <- effsize::cohen.d(control_hassles$indebted_all, grat_letter$indebted_all, hedges.correction = TRUE)

hassles_3 <- t.test(control_hassles$indebted_all, grat_text$indebted_all)
hassles_3_ef <- effsize::cohen.d(control_hassles$indebted_all, grat_text$indebted_all, hedges.correction = TRUE)

hassles_4 <- t.test(control_hassles$indebted_all, grat_hk$indebted_all)
hassles_4_ef <- effsize::cohen.d(control_hassles$indebted_all, grat_hk$indebted_all, hedges.correction = TRUE)

hassles_5 <- t.test(control_hassles$indebted_all, grat_sing$indebted_all)
hassles_5_ef <- effsize::cohen.d(control_hassles$indebted_all, grat_sing$indebted_all, hedges.correction = TRUE)

hassles_6 <- t.test(control_hassles$indebted_all, grat_god_list$indebted_all)
hassles_6_ef <- effsize::cohen.d(control_hassles$indebted_all, grat_god_list$indebted_all, hedges.correction = TRUE)

hassles_7 <- t.test(control_hassles$indebted_all, grat_god_letter$indebted_all)
hassles_7_ef <- effsize::cohen.d(control_hassles$indebted_all, grat_god_letter$indebted_all, hedges.correction = TRUE)

#Control t-test Graph

p_values_4 <- c(hassles_1$p.value, hassles_2$p.value, hassles_3$p.value, hassles_4$p.value, hassles_5$p.value, hassles_6$p.value, hassles_7$p.value)
estimate_4 <- c(hassles_1_ef$estimate, hassles_2_ef$estimate, hassles_3_ef$estimate, hassles_4_ef$estimate, hassles_5_ef$estimate, hassles_6_ef$estimate, hassles_7_ef$estimate)
statistic_4 <- c(hassles_1$statistic, hassles_2$statistic, hassles_3$statistic, hassles_4$statistic, hassles_5$statistic, hassles_6$statistic, hassles_7$statistic)
parameter_4 <- c(hassles_1$parameter, hassles_2$parameter, hassles_3$parameter, hassles_4$parameter, hassles_5$parameter, hassles_6$parameter, hassles_7$parameter)

#Table
table_data_4 <- data.frame(
  Condition = conditions_4,
  "t" = statistic_4,
  "df" = parameter_4,
  "p" = p_values_4, 
  "Hedges' g" = estimate_4)

print(table_data_4)
```

```{r gratitude conditions}

#Comparing Across Gratitude Conditions

#Gratitude List

grat_1 <- t.test(grat_list$indebted_all, grat_letter$indebted_all)
grat_1_ef <- effsize::cohen.d(grat_list$indebted_all, grat_letter$indebted_all, hedges.correction = TRUE)

grat_2 <- t.test(grat_list$indebted_all, grat_text$indebted_all)
grat_2_ef <- effsize::cohen.d(grat_list$indebted_all, grat_text$indebted_all, hedges.correction = TRUE)

grat_3 <- t.test(grat_list$indebted_all, grat_hk$indebted_all)
grat_3_ef <- effsize::cohen.d(grat_list$indebted_all, grat_hk$indebted_all, hedges.correction = TRUE)

grat_4 <- t.test(grat_list$indebted_all, grat_sing$indebted_all)
grat_4_ef <- effsize::cohen.d(grat_list$indebted_all, grat_sing$indebted_all, hedges.correction = TRUE)

grat_5 <- t.test(grat_list$indebted_all, grat_god_list$indebted_all)
grat_5_ef <- effsize::cohen.d(grat_list$indebted_all, grat_list$indebted_all, hedges.correction = TRUE)

grat_6 <- t.test(grat_list$indebted_all, grat_god_letter$indebted_all)
grat_6_ef <- effsize::cohen.d(grat_list$indebted_all, grat_god_letter$indebted_all, hedges.correction = TRUE)

#Gratitude Letter

grat_7 <- t.test(grat_letter$indebted_all, grat_text$indebted_all)
grat_7_ef <- effsize::cohen.d(grat_letter$indebted_all, grat_text$indebted_all, hedges.correction = TRUE)

grat_8 <- t.test(grat_letter$indebted_all, grat_hk$indebted_all)
grat_8_ef <- effsize::cohen.d(grat_letter$indebted_all, grat_hk$indebted_all, hedges.correction = TRUE)

grat_9 <- t.test(grat_letter$indebted_all, grat_sing$indebted_all)
grat_9_ef <- effsize::cohen.d(grat_letter$indebted_all, grat_sing$indebted_all, hedges.correction = TRUE)

grat_10 <- t.test(grat_letter$indebted_all, grat_god_list$indebted_all)
grat_10_ef <- effsize::cohen.d(grat_letter$indebted_all, grat_god_list$indebted_all, hedges.correction = TRUE)

grat_11 <- t.test(grat_letter$indebted_all, grat_god_letter$indebted_all)
grat_11_ef <- effsize::cohen.d(grat_letter$indebted_all, grat_god_letter$indebted_all, hedges.correction = TRUE)

#Gratitude Text

grat_12 <- t.test(grat_text$indebted_all, grat_hk$indebted_all)
grat_12_ef <- effsize::cohen.d(grat_text$indebted_all, grat_hk$indebted_all, hedges.correction = TRUE)

grat_13 <- t.test(grat_text$indebted_all, grat_sing$indebted_all)
grat_13_ef <- effsize::cohen.d(grat_text$indebted_all, grat_sing$indebted_all, hedges.correction = TRUE)

grat_14 <- t.test(grat_text$indebted_all, grat_god_list$indebted_all)
grat_14_ef <- effsize::cohen.d(grat_text$indebted_all, grat_god_list$indebted_all, hedges.correction = TRUE)

grat_15 <- t.test(grat_text$indebted_all, grat_god_letter$indebted_all)
grat_15_ef <- effsize::cohen.d(grat_text$indebted_all, grat_god_letter$indebted_all, hedges.correction = TRUE)

#Chan Gratitude List

grat_16 <- t.test(grat_hk$indebted_all, grat_sing$indebted_all)
grat_16_ef <- effsize::cohen.d(grat_hk$indebted_all, grat_sing$indebted_all, hedges.correction = TRUE)

grat_17 <- t.test(grat_hk$indebted_all, grat_god_list$indebted_all)
grat_17_ef <- effsize::cohen.d(grat_hk$indebted_all, grat_god_list$indebted_all, hedges.correction = TRUE)

grat_18 <- t.test(grat_hk$indebted_all, grat_god_letter$indebted_all)
grat_18_ef <- effsize::cohen.d(grat_hk$indebted_all, grat_god_letter$indebted_all, hedges.correction = TRUE)

#Singapore Gratitude Task

grat_19 <- t.test(grat_sing$indebted_all, grat_god_list$indebted_all)
grat_19_ef <- effsize::cohen.d(grat_sing$indebted_all, grat_god_list$indebted_all, hedges.correction = TRUE)

grat_20 <- t.test(grat_sing$indebted_all, grat_god_letter$indebted_all)
grat_20_ef <- effsize::cohen.d(grat_sing$indebted_all, grat_god_letter$indebted_all, hedges.correction = TRUE)

#Gratitude to God

grat_21 <- t.test(grat_god_list$indebted_all, grat_god_letter$indebted_all)
grat_21_ef <- effsize::cohen.d(grat_god_list$indebted_all, grat_god_letter$indebted_all, hedges.correction = TRUE)

#Gratitude Conditions Graph

p_values_5 <- c(grat_1$p.value, grat_2$p.value, grat_3$p.value, grat_4$p.value, grat_5$p.value, grat_6$p.value, grat_7$p.value, grat_8$p.value, grat_9$p.value, grat_10$p.value, grat_11$p.value, grat_12$p.value, grat_13$p.value, grat_14$p.value, grat_15$p.value,grat_16$p.value, grat_17$p.value, grat_18$p.value, grat_19$p.value, grat_20$p.value,grat_21$p.value)
estimate_5 <- c(grat_1_ef$estimate, grat_2_ef$estimate, grat_3_ef$estimate, grat_4_ef$estimate, grat_5_ef$estimate, grat_6_ef$estimate, grat_7_ef$estimate, grat_8_ef$estimate, grat_9_ef$estimate, grat_10_ef$estimate, grat_11_ef$estimate, grat_12_ef$estimate, grat_13_ef$estimate, grat_14_ef$estimate, grat_15_ef$estimate,grat_16_ef$estimate, grat_17_ef$estimate, grat_18_ef$estimate, grat_19_ef$estimate, grat_20_ef$estimate,grat_21_ef$estimate)
statistic_5 <- c(grat_1$statistic, grat_2$statistic, grat_3$statistic, grat_4$statistic, grat_5$statistic, grat_6$statistic, grat_7$statistic, grat_8$statistic, grat_9$statistic, grat_10$statistic, grat_11$statistic, grat_12$statistic, grat_13$statistic, grat_14$statistic, grat_15$statistic,grat_16$statistic, grat_17$statistic, grat_18$statistic, grat_19$statistic, grat_20$statistic,grat_21$statistic)
parameter_5 <- c(grat_1$parameter, grat_2$parameter, grat_3$parameter, grat_4$parameter, grat_5$parameter, grat_6$parameter, grat_7$parameter, grat_8$parameter, grat_9$parameter, grat_10$parameter, grat_11$parameter, grat_12$parameter, grat_13$parameter, grat_14$parameter, grat_15$parameter,grat_16$parameter, grat_17$parameter, grat_18$parameter, grat_19$parameter, grat_20$parameter,grat_21$parameter)

#Table
table_data_5 <- data.frame(
  Condition = conditions_5,
  "t" = statistic_5,
  "df" = parameter_5,
  "p" = p_values_5, 
  "Hedges' g" = estimate_5)

print(table_data_5)

```

```{r control conditions}

#Comparing Across Control Conditions

#Control

con_1 <- t.test(control$indebted_all, control_events$indebted_all)
con_1_ef <- effsize::cohen.d(control$indebted_all, control_events$indebted_all, hedges.correction = TRUE)

con_2 <- t.test(control$indebted_all, control_interesting$indebted_all)
con_2_ef <- effsize::cohen.d(control$indebted_all, control_interesting$indebted_all, hedges.correction = TRUE)

con_3 <- t.test(control$indebted_all, control_hassles$indebted_all)
con_3_ef <- effsize::cohen.d(control$indebted_all, control_hassles$indebted_all, hedges.correction = TRUE)

#Control Events

con_4 <- t.test(control_events$indebted_all, control_interesting$indebted_all)
con_4_ef <- effsize::cohen.d(control_events$indebted_all, control_interesting$indebted_all, hedges.correction = TRUE)

con_5 <- t.test(control_events$indebted_all, control_hassles$indebted_all)
con_5_ef <- effsize::cohen.d(control_events$indebted_all, control_hassles$indebted_all, hedges.correction = TRUE)

#Control Interesting Events

con_6 <- t.test(control_interesting$indebted_all, control_hassles$indebted_all)
con_6_ef <- effsize::cohen.d(control_interesting$indebted_all, control_hassles$indebted_all, hedges.correction = TRUE)

#Control t-test Graph
p_values_6 <- c(con_1$p.value, con_2$p.value, con_3$p.value, con_4$p.value, con_5$p.value, con_6$p.value)
estimate_6 <- c(con_1_ef$estimate, con_2_ef$estimate, con_3_ef$estimate, con_4_ef$estimate, con_5_ef$estimate, con_6_ef$estimate)
statistic_6 <- c(con_1$statistic, con_2$statistic, con_3$statistic, con_4$statistic, con_5$statistic, con_6$statistic)
parameter_6 <- c(con_1$parameter, con_2$parameter, con_3$parameter, con_4$parameter, con_5$parameter, con_6$parameter)

#Table
table_data_6 <- data.frame(
  Condition = conditions_6,
  "t" = statistic_6,
  "df" = parameter_6,
  "p" = p_values_6, 
  "Hedges' g" = estimate_6)

print(table_data_6)

```

#t-Tests (State Guilt)

```{r control}

control_1 <- t.test(control$guilty, grat_list$guilty)
control_1_ef <- effsize::cohen.d(control$guilty, grat_list$guilty, hedges.correction = TRUE)

control_2 <- t.test(control$guilty, grat_letter$guilty)
control_2_ef <- effsize::cohen.d(control$guilty, grat_letter$guilty, hedges.correction = TRUE)

control_3 <- t.test(control$guilty, grat_text$guilty)
control_3_ef <- effsize::cohen.d(control$guilty, grat_text$guilty, hedges.correction = TRUE)

control_4 <- t.test(control$guilty, grat_hk$guilty)
control_4_ef <- effsize::cohen.d(control$guilty, grat_hk$guilty, hedges.correction = TRUE)

control_5 <- t.test(control$guilty, grat_sing$guilty)
control_5_ef <- effsize::cohen.d(control$guilty, grat_sing$guilty, hedges.correction = TRUE)

control_6 <- t.test(control$guilty, grat_sing$guilty)
control_6_ef <- effsize::cohen.d(control$guilty, grat_god_list$guilty, hedges.correction = TRUE)

control_7 <- t.test(control$guilty, grat_god_letter$guilty)
control_7_ef <- effsize::cohen.d(control$guilty, grat_god_letter$guilty, hedges.correction = TRUE)

#Control t-test Graph

#Dataframe
p_values_1 <- c(control_1$p.value, control_2$p.value, control_3$p.value, control_4$p.value, control_5$p.value, control_6$p.value, control_7$p.value)
estimate_1 <- c(control_1_ef$estimate, control_2_ef$estimate, control_3_ef$estimate, control_4_ef$estimate, control_5_ef$estimate, control_6_ef$estimate, control_7_ef$estimate)
statistic_1 <- c(control_1$statistic, control_2$statistic, control_3$statistic, control_4$statistic, control_5$statistic, control_6$statistic, control_7$statistic)
parameter_1 <- c(control_1$parameter, control_2$parameter, control_3$parameter, control_4$parameter, control_5$parameter, control_6$parameter, control_7$parameter)

#Table
table_data_1 <- data.frame(
  Condition = conditions_1,
  "t" = statistic_1,
  "df" = parameter_1,
  "p" = p_values_1, 
  "Hedges' g" = estimate_1)

print(table_data_1)
```

```{r events}

#Events

events_1 <- t.test(control_events$guilty, grat_list$guilty)
events_1_ef <- effsize::cohen.d(control_events$guilty, grat_list$guilty, hedges.correction = TRUE)

events_2 <- t.test(control_events$guilty, grat_letter$guilty)
events_2_ef <- effsize::cohen.d(control_events$guilty, grat_letter$guilty, hedges.correction = TRUE)

events_3 <- t.test(control_events$guilty, grat_text$guilty)
events_3_ef <- effsize::cohen.d(control_events$guilty, grat_text$guilty, hedges.correction = TRUE)

events_4 <- t.test(control_events$guilty, grat_hk$guilty)
events_4_ef <- effsize::cohen.d(control_events$guilty, grat_hk$guilty, hedges.correction = TRUE)

events_5 <- t.test(control_events$guilty, grat_sing$guilty)
events_5_ef <- effsize::cohen.d(control_events$guilty, grat_sing$guilty, hedges.correction = TRUE)

events_6 <- t.test(control_events$guilty, grat_god_list$guilty)
events_6_ef <- effsize::cohen.d(control_events$guilty, grat_god_list$guilty, hedges.correction = TRUE)

events_7 <- t.test(control_events$guilty, grat_god_letter$guilty)
events_7_ef <- effsize::cohen.d(control_events$guilty, grat_god_letter$guilty, hedges.correction = TRUE)

#Control t-test Graph
p_values_2 <- c(events_1$p.value, events_2$p.value, events_3$p.value, events_4$p.value, events_5$p.value, events_6$p.value, events_7$p.value)
estimate_2 <- c(events_1_ef$estimate, events_2_ef$estimate, events_3_ef$estimate, events_4_ef$estimate, events_5_ef$estimate, events_6_ef$estimate, events_7_ef$estimate)
statistic_2 <- c(events_1$statistic, events_2$statistic, events_3$statistic, events_4$statistic, events_5$statistic, events_6$statistic, events_7$statistic)
parameter_2 <- c(events_1$parameter, events_2$parameter, events_3$parameter, events_4$parameter, events_5$parameter, events_6$parameter, events_7$parameter)

#Table
table_data_2 <- data.frame(
  Condition = conditions_2,
  "t" = statistic_2,
  "df" = parameter_2,
  "p" = p_values_2, 
  "Hedges' g" = estimate_2)

print(table_data_2)
```

```{r interesting events}

#Interesting Events

int_1 <- t.test(control_interesting$guilty, grat_list$guilty)
int_1_ef <- effsize::cohen.d(control_interesting$guilty, grat_list$guilty, hedges.correction = TRUE)

int_2 <- t.test(control_interesting$guilty, grat_letter$guilty)
int_2_ef <- effsize::cohen.d(control_interesting$guilty, grat_letter$guilty, hedges.correction = TRUE)

int_3 <- t.test(control_interesting$guilty, grat_text$guilty)
int_3_ef <- effsize::cohen.d(control_interesting$guilty, grat_text$guilty, hedges.correction = TRUE)

int_4 <- t.test(control_interesting$guilty, grat_hk$guilty)
int_4_ef <- effsize::cohen.d(control_interesting$guilty, grat_hk$guilty, hedges.correction = TRUE)

int_5 <- t.test(control_interesting$guilty, grat_sing$guilty)
int_5_ef <- effsize::cohen.d(control_interesting$guilty, grat_sing$guilty, hedges.correction = TRUE)

int_6 <- t.test(control_interesting$guilty, grat_god_list$guilty)
int_6_ef <- effsize::cohen.d(control_interesting$guilty, grat_god_list$guilty, hedges.correction = TRUE)

int_7 <- t.test(control_interesting$guilty, grat_god_letter$guilty)
int_7_ef <- effsize::cohen.d(control_interesting$guilty, grat_god_letter$guilty, hedges.correction = TRUE)

#Control t-test Graph
p_values_3 <- c(int_1$p.value, int_2$p.value, int_3$p.value, int_4$p.value, int_5$p.value, int_6$p.value, int_7$p.value)
estimate_3 <- c(int_1_ef$estimate, int_2_ef$estimate, int_3_ef$estimate, int_4_ef$estimate, int_5_ef$estimate, int_6_ef$estimate, int_7_ef$estimate)
statistic_3 <- c(int_1$statistic, int_2$statistic, int_3$statistic, int_4$statistic, int_5$statistic, int_6$statistic, int_7$statistic)
parameter_3 <- c(int_1$parameter, int_2$parameter, int_3$parameter, int_4$parameter, int_5$parameter, int_6$parameter, int_7$parameter)

#Table
table_data_3 <- data.frame(
  Condition = conditions_3,
  "t" = statistic_3,
  "df" = parameter_3,
  "p" = p_values_3, 
  "Hedges' g" = estimate_3)

print(table_data_3)
```

```{r hassles}

#Hassles

hassles_1 <- t.test(control_hassles$guilty, grat_list$guilty)
hassles_1_ef <- effsize::cohen.d(control_hassles$guilty, grat_list$guilty, hedges.correction = TRUE)

hassles_2 <- t.test(control_hassles$guilty, grat_letter$guilty)
hassles_2_ef <- effsize::cohen.d(control_hassles$guilty, grat_letter$guilty, hedges.correction = TRUE)

hassles_3 <- t.test(control_hassles$guilty, grat_text$guilty)
hassles_3_ef <- effsize::cohen.d(control_hassles$guilty, grat_text$guilty, hedges.correction = TRUE)

hassles_4 <- t.test(control_hassles$guilty, grat_hk$guilty)
hassles_4_ef <- effsize::cohen.d(control_hassles$guilty, grat_hk$guilty, hedges.correction = TRUE)

hassles_5 <- t.test(control_hassles$guilty, grat_sing$guilty)
hassles_5_ef <- effsize::cohen.d(control_hassles$guilty, grat_sing$guilty, hedges.correction = TRUE)

hassles_6 <- t.test(control_hassles$guilty, grat_god_list$guilty)
hassles_6_ef <- effsize::cohen.d(control_hassles$guilty, grat_god_list$guilty, hedges.correction = TRUE)

hassles_7 <- t.test(control_hassles$guilty, grat_god_letter$guilty)
hassles_7_ef <- effsize::cohen.d(control_hassles$guilty, grat_god_letter$guilty, hedges.correction = TRUE)

#Control t-test Graph

p_values_4 <- c(hassles_1$p.value, hassles_2$p.value, hassles_3$p.value, hassles_4$p.value, hassles_5$p.value, hassles_6$p.value, hassles_7$p.value)
estimate_4 <- c(hassles_1_ef$estimate, hassles_2_ef$estimate, hassles_3_ef$estimate, hassles_4_ef$estimate, hassles_5_ef$estimate, hassles_6_ef$estimate, hassles_7_ef$estimate)
statistic_4 <- c(hassles_1$statistic, hassles_2$statistic, hassles_3$statistic, hassles_4$statistic, hassles_5$statistic, hassles_6$statistic, hassles_7$statistic)
parameter_4 <- c(hassles_1$parameter, hassles_2$parameter, hassles_3$parameter, hassles_4$parameter, hassles_5$parameter, hassles_6$parameter, hassles_7$parameter)

#Table
table_data_4 <- data.frame(
  Condition = conditions_4,
  "t" = statistic_4,
  "df" = parameter_4,
  "p" = p_values_4, 
  "Hedges' g" = estimate_4)

print(table_data_4)
```

```{r gratitude conditions}

#Comparing Across Gratitude Conditions

#Gratitude List

grat_1 <- t.test(grat_list$guilty, grat_letter$guilty)
grat_1_ef <- effsize::cohen.d(grat_list$guilty, grat_letter$guilty, hedges.correction = TRUE)

grat_2 <- t.test(grat_list$guilty, grat_text$guilty)
grat_2_ef <- effsize::cohen.d(grat_list$guilty, grat_text$guilty, hedges.correction = TRUE)

grat_3 <- t.test(grat_list$guilty, grat_hk$guilty)
grat_3_ef <- effsize::cohen.d(grat_list$guilty, grat_hk$guilty, hedges.correction = TRUE)

grat_4 <- t.test(grat_list$guilty, grat_sing$guilty)
grat_4_ef <- effsize::cohen.d(grat_list$guilty, grat_sing$guilty, hedges.correction = TRUE)

grat_5 <- t.test(grat_list$guilty, grat_god_list$guilty)
grat_5_ef <- effsize::cohen.d(grat_list$guilty, grat_list$guilty, hedges.correction = TRUE)

grat_6 <- t.test(grat_list$guilty, grat_god_letter$guilty)
grat_6_ef <- effsize::cohen.d(grat_list$guilty, grat_god_letter$guilty, hedges.correction = TRUE)

#Gratitude Letter

grat_7 <- t.test(grat_letter$guilty, grat_text$guilty)
grat_7_ef <- effsize::cohen.d(grat_letter$guilty, grat_text$guilty, hedges.correction = TRUE)

grat_8 <- t.test(grat_letter$guilty, grat_hk$guilty)
grat_8_ef <- effsize::cohen.d(grat_letter$guilty, grat_hk$guilty, hedges.correction = TRUE)

grat_9 <- t.test(grat_letter$guilty, grat_sing$guilty)
grat_9_ef <- effsize::cohen.d(grat_letter$guilty, grat_sing$guilty, hedges.correction = TRUE)

grat_10 <- t.test(grat_letter$guilty, grat_god_list$guilty)
grat_10_ef <- effsize::cohen.d(grat_letter$guilty, grat_god_list$guilty, hedges.correction = TRUE)

grat_11 <- t.test(grat_letter$guilty, grat_god_letter$guilty)
grat_11_ef <- effsize::cohen.d(grat_letter$guilty, grat_god_letter$guilty, hedges.correction = TRUE)

#Gratitude Text

grat_12 <- t.test(grat_text$guilty, grat_hk$guilty)
grat_12_ef <- effsize::cohen.d(grat_text$guilty, grat_hk$guilty, hedges.correction = TRUE)

grat_13 <- t.test(grat_text$guilty, grat_sing$guilty)
grat_13_ef <- effsize::cohen.d(grat_text$guilty, grat_sing$guilty, hedges.correction = TRUE)

grat_14 <- t.test(grat_text$guilty, grat_god_list$guilty)
grat_14_ef <- effsize::cohen.d(grat_text$guilty, grat_god_list$guilty, hedges.correction = TRUE)

grat_15 <- t.test(grat_text$guilty, grat_god_letter$guilty)
grat_15_ef <- effsize::cohen.d(grat_text$guilty, grat_god_letter$guilty, hedges.correction = TRUE)

#Chan Gratitude List

grat_16 <- t.test(grat_hk$guilty, grat_sing$guilty)
grat_16_ef <- effsize::cohen.d(grat_hk$guilty, grat_sing$guilty, hedges.correction = TRUE)

grat_17 <- t.test(grat_hk$guilty, grat_god_list$guilty)
grat_17_ef <- effsize::cohen.d(grat_hk$guilty, grat_god_list$guilty, hedges.correction = TRUE)

grat_18 <- t.test(grat_hk$guilty, grat_god_letter$guilty)
grat_18_ef <- effsize::cohen.d(grat_hk$guilty, grat_god_letter$guilty, hedges.correction = TRUE)

#Singapore Gratitude Task

grat_19 <- t.test(grat_sing$guilty, grat_god_list$guilty)
grat_19_ef <- effsize::cohen.d(grat_sing$guilty, grat_god_list$guilty, hedges.correction = TRUE)

grat_20 <- t.test(grat_sing$guilty, grat_god_letter$guilty)
grat_20_ef <- effsize::cohen.d(grat_sing$guilty, grat_god_letter$guilty, hedges.correction = TRUE)

#Gratitude to God

grat_21 <- t.test(grat_god_list$guilty, grat_god_letter$guilty)
grat_21_ef <- effsize::cohen.d(grat_god_list$guilty, grat_god_letter$guilty, hedges.correction = TRUE)

#Gratitude Conditions Graph

p_values_5 <- c(grat_1$p.value, grat_2$p.value, grat_3$p.value, grat_4$p.value, grat_5$p.value, grat_6$p.value, grat_7$p.value, grat_8$p.value, grat_9$p.value, grat_10$p.value, grat_11$p.value, grat_12$p.value, grat_13$p.value, grat_14$p.value, grat_15$p.value,grat_16$p.value, grat_17$p.value, grat_18$p.value, grat_19$p.value, grat_20$p.value,grat_21$p.value)
estimate_5 <- c(grat_1_ef$estimate, grat_2_ef$estimate, grat_3_ef$estimate, grat_4_ef$estimate, grat_5_ef$estimate, grat_6_ef$estimate, grat_7_ef$estimate, grat_8_ef$estimate, grat_9_ef$estimate, grat_10_ef$estimate, grat_11_ef$estimate, grat_12_ef$estimate, grat_13_ef$estimate, grat_14_ef$estimate, grat_15_ef$estimate,grat_16_ef$estimate, grat_17_ef$estimate, grat_18_ef$estimate, grat_19_ef$estimate, grat_20_ef$estimate,grat_21_ef$estimate)
statistic_5 <- c(grat_1$statistic, grat_2$statistic, grat_3$statistic, grat_4$statistic, grat_5$statistic, grat_6$statistic, grat_7$statistic, grat_8$statistic, grat_9$statistic, grat_10$statistic, grat_11$statistic, grat_12$statistic, grat_13$statistic, grat_14$statistic, grat_15$statistic,grat_16$statistic, grat_17$statistic, grat_18$statistic, grat_19$statistic, grat_20$statistic,grat_21$statistic)
parameter_5 <- c(grat_1$parameter, grat_2$parameter, grat_3$parameter, grat_4$parameter, grat_5$parameter, grat_6$parameter, grat_7$parameter, grat_8$parameter, grat_9$parameter, grat_10$parameter, grat_11$parameter, grat_12$parameter, grat_13$parameter, grat_14$parameter, grat_15$parameter,grat_16$parameter, grat_17$parameter, grat_18$parameter, grat_19$parameter, grat_20$parameter,grat_21$parameter)

#Table
table_data_5 <- data.frame(
  Condition = conditions_5,
  "t" = statistic_5,
  "df" = parameter_5,
  "p" = p_values_5, 
  "Hedges' g" = estimate_5)

print(table_data_5)

```

```{r control conditions}

#Comparing Across Control Conditions

#Control

con_1 <- t.test(control$guilty, control_events$guilty)
con_1_ef <- effsize::cohen.d(control$guilty, control_events$guilty, hedges.correction = TRUE)

con_2 <- t.test(control$guilty, control_interesting$guilty)
con_2_ef <- effsize::cohen.d(control$guilty, control_interesting$guilty, hedges.correction = TRUE)

con_3 <- t.test(control$guilty, control_hassles$guilty)
con_3_ef <- effsize::cohen.d(control$guilty, control_hassles$guilty, hedges.correction = TRUE)

#Control Events

con_4 <- t.test(control_events$guilty, control_interesting$guilty)
con_4_ef <- effsize::cohen.d(control_events$guilty, control_interesting$guilty, hedges.correction = TRUE)

con_5 <- t.test(control_events$guilty, control_hassles$guilty)
con_5_ef <- effsize::cohen.d(control_events$guilty, control_hassles$guilty, hedges.correction = TRUE)

#Control Interesting Events

con_6 <- t.test(control_interesting$guilty, control_hassles$guilty)
con_6_ef <- effsize::cohen.d(control_interesting$guilty, control_hassles$guilty, hedges.correction = TRUE)

#Control t-test Graph
p_values_6 <- c(con_1$p.value, con_2$p.value, con_3$p.value, con_4$p.value, con_5$p.value, con_6$p.value)
estimate_6 <- c(con_1_ef$estimate, con_2_ef$estimate, con_3_ef$estimate, con_4_ef$estimate, con_5_ef$estimate, con_6_ef$estimate)
statistic_6 <- c(con_1$statistic, con_2$statistic, con_3$statistic, con_4$statistic, con_5$statistic, con_6$statistic)
parameter_6 <- c(con_1$parameter, con_2$parameter, con_3$parameter, con_4$parameter, con_5$parameter, con_6$parameter)

#Table
table_data_6 <- data.frame(
  Condition = conditions_6,
  "t" = statistic_6,
  "df" = parameter_6,
  "p" = p_values_6, 
  "Hedges' g" = estimate_6)

print(table_data_6)

```

#t-Tests (State Envy)

```{r control}

control_1 <- t.test(control$envy_all, grat_list$envy_all)
control_1_ef <- effsize::cohen.d(control$envy_all, grat_list$envy_all, hedges.correction = TRUE)

control_2 <- t.test(control$envy_all, grat_letter$envy_all)
control_2_ef <- effsize::cohen.d(control$envy_all, grat_letter$envy_all, hedges.correction = TRUE)

control_3 <- t.test(control$envy_all, grat_text$envy_all)
control_3_ef <- effsize::cohen.d(control$envy_all, grat_text$envy_all, hedges.correction = TRUE)

control_4 <- t.test(control$envy_all, grat_hk$envy_all)
control_4_ef <- effsize::cohen.d(control$envy_all, grat_hk$envy_all, hedges.correction = TRUE)

control_5 <- t.test(control$envy_all, grat_sing$envy_all)
control_5_ef <- effsize::cohen.d(control$envy_all, grat_sing$envy_all, hedges.correction = TRUE)

control_6 <- t.test(control$envy_all, grat_sing$envy_all)
control_6_ef <- effsize::cohen.d(control$envy_all, grat_god_list$envy_all, hedges.correction = TRUE)

control_7 <- t.test(control$envy_all, grat_god_letter$envy_all)
control_7_ef <- effsize::cohen.d(control$envy_all, grat_god_letter$envy_all, hedges.correction = TRUE)

#Control t-test Graph

#Dataframe
p_values_1 <- c(control_1$p.value, control_2$p.value, control_3$p.value, control_4$p.value, control_5$p.value, control_6$p.value, control_7$p.value)
estimate_1 <- c(control_1_ef$estimate, control_2_ef$estimate, control_3_ef$estimate, control_4_ef$estimate, control_5_ef$estimate, control_6_ef$estimate, control_7_ef$estimate)
statistic_1 <- c(control_1$statistic, control_2$statistic, control_3$statistic, control_4$statistic, control_5$statistic, control_6$statistic, control_7$statistic)
parameter_1 <- c(control_1$parameter, control_2$parameter, control_3$parameter, control_4$parameter, control_5$parameter, control_6$parameter, control_7$parameter)

#Table
table_data_1 <- data.frame(
  Condition = conditions_1,
  "t" = statistic_1,
  "df" = parameter_1,
  "p" = p_values_1, 
  "Hedges' g" = estimate_1)

print(table_data_1)
```

```{r events}

#Events

events_1 <- t.test(control_events$envy_all, grat_list$envy_all)
events_1_ef <- effsize::cohen.d(control_events$envy_all, grat_list$envy_all, hedges.correction = TRUE)

events_2 <- t.test(control_events$envy_all, grat_letter$envy_all)
events_2_ef <- effsize::cohen.d(control_events$envy_all, grat_letter$envy_all, hedges.correction = TRUE)

events_3 <- t.test(control_events$envy_all, grat_text$envy_all)
events_3_ef <- effsize::cohen.d(control_events$envy_all, grat_text$envy_all, hedges.correction = TRUE)

events_4 <- t.test(control_events$envy_all, grat_hk$envy_all)
events_4_ef <- effsize::cohen.d(control_events$envy_all, grat_hk$envy_all, hedges.correction = TRUE)

events_5 <- t.test(control_events$envy_all, grat_sing$envy_all)
events_5_ef <- effsize::cohen.d(control_events$envy_all, grat_sing$envy_all, hedges.correction = TRUE)

events_6 <- t.test(control_events$envy_all, grat_god_list$envy_all)
events_6_ef <- effsize::cohen.d(control_events$envy_all, grat_god_list$envy_all, hedges.correction = TRUE)

events_7 <- t.test(control_events$envy_all, grat_god_letter$envy_all)
events_7_ef <- effsize::cohen.d(control_events$envy_all, grat_god_letter$envy_all, hedges.correction = TRUE)

#Control t-test Graph
p_values_2 <- c(events_1$p.value, events_2$p.value, events_3$p.value, events_4$p.value, events_5$p.value, events_6$p.value, events_7$p.value)
estimate_2 <- c(events_1_ef$estimate, events_2_ef$estimate, events_3_ef$estimate, events_4_ef$estimate, events_5_ef$estimate, events_6_ef$estimate, events_7_ef$estimate)
statistic_2 <- c(events_1$statistic, events_2$statistic, events_3$statistic, events_4$statistic, events_5$statistic, events_6$statistic, events_7$statistic)
parameter_2 <- c(events_1$parameter, events_2$parameter, events_3$parameter, events_4$parameter, events_5$parameter, events_6$parameter, events_7$parameter)

#Table
table_data_2 <- data.frame(
  Condition = conditions_2,
  "t" = statistic_2,
  "df" = parameter_2,
  "p" = p_values_2, 
  "Hedges' g" = estimate_2)

print(table_data_2)
```

```{r interesting events}

#Interesting Events

int_1 <- t.test(control_interesting$envy_all, grat_list$envy_all)
int_1_ef <- effsize::cohen.d(control_interesting$envy_all, grat_list$envy_all, hedges.correction = TRUE)

int_2 <- t.test(control_interesting$envy_all, grat_letter$envy_all)
int_2_ef <- effsize::cohen.d(control_interesting$envy_all, grat_letter$envy_all, hedges.correction = TRUE)

int_3 <- t.test(control_interesting$envy_all, grat_text$envy_all)
int_3_ef <- effsize::cohen.d(control_interesting$envy_all, grat_text$envy_all, hedges.correction = TRUE)

int_4 <- t.test(control_interesting$envy_all, grat_hk$envy_all)
int_4_ef <- effsize::cohen.d(control_interesting$envy_all, grat_hk$envy_all, hedges.correction = TRUE)

int_5 <- t.test(control_interesting$envy_all, grat_sing$envy_all)
int_5_ef <- effsize::cohen.d(control_interesting$envy_all, grat_sing$envy_all, hedges.correction = TRUE)

int_6 <- t.test(control_interesting$envy_all, grat_god_list$envy_all)
int_6_ef <- effsize::cohen.d(control_interesting$envy_all, grat_god_list$envy_all, hedges.correction = TRUE)

int_7 <- t.test(control_interesting$envy_all, grat_god_letter$envy_all)
int_7_ef <- effsize::cohen.d(control_interesting$envy_all, grat_god_letter$envy_all, hedges.correction = TRUE)

#Control t-test Graph
p_values_3 <- c(int_1$p.value, int_2$p.value, int_3$p.value, int_4$p.value, int_5$p.value, int_6$p.value, int_7$p.value)
estimate_3 <- c(int_1_ef$estimate, int_2_ef$estimate, int_3_ef$estimate, int_4_ef$estimate, int_5_ef$estimate, int_6_ef$estimate, int_7_ef$estimate)
statistic_3 <- c(int_1$statistic, int_2$statistic, int_3$statistic, int_4$statistic, int_5$statistic, int_6$statistic, int_7$statistic)
parameter_3 <- c(int_1$parameter, int_2$parameter, int_3$parameter, int_4$parameter, int_5$parameter, int_6$parameter, int_7$parameter)

#Table
table_data_3 <- data.frame(
  Condition = conditions_3,
  "t" = statistic_3,
  "df" = parameter_3,
  "p" = p_values_3, 
  "Hedges' g" = estimate_3)

print(table_data_3)
```

```{r hassles}

#Hassles

hassles_1 <- t.test(control_hassles$envy_all, grat_list$envy_all)
hassles_1_ef <- effsize::cohen.d(control_hassles$envy_all, grat_list$envy_all, hedges.correction = TRUE)

hassles_2 <- t.test(control_hassles$envy_all, grat_letter$envy_all)
hassles_2_ef <- effsize::cohen.d(control_hassles$envy_all, grat_letter$envy_all, hedges.correction = TRUE)

hassles_3 <- t.test(control_hassles$envy_all, grat_text$envy_all)
hassles_3_ef <- effsize::cohen.d(control_hassles$envy_all, grat_text$envy_all, hedges.correction = TRUE)

hassles_4 <- t.test(control_hassles$envy_all, grat_hk$envy_all)
hassles_4_ef <- effsize::cohen.d(control_hassles$envy_all, grat_hk$envy_all, hedges.correction = TRUE)

hassles_5 <- t.test(control_hassles$envy_all, grat_sing$envy_all)
hassles_5_ef <- effsize::cohen.d(control_hassles$envy_all, grat_sing$envy_all, hedges.correction = TRUE)

hassles_6 <- t.test(control_hassles$envy_all, grat_god_list$envy_all)
hassles_6_ef <- effsize::cohen.d(control_hassles$envy_all, grat_god_list$envy_all, hedges.correction = TRUE)

hassles_7 <- t.test(control_hassles$envy_all, grat_god_letter$envy_all)
hassles_7_ef <- effsize::cohen.d(control_hassles$envy_all, grat_god_letter$envy_all, hedges.correction = TRUE)

#Control t-test Graph

p_values_4 <- c(hassles_1$p.value, hassles_2$p.value, hassles_3$p.value, hassles_4$p.value, hassles_5$p.value, hassles_6$p.value, hassles_7$p.value)
estimate_4 <- c(hassles_1_ef$estimate, hassles_2_ef$estimate, hassles_3_ef$estimate, hassles_4_ef$estimate, hassles_5_ef$estimate, hassles_6_ef$estimate, hassles_7_ef$estimate)
statistic_4 <- c(hassles_1$statistic, hassles_2$statistic, hassles_3$statistic, hassles_4$statistic, hassles_5$statistic, hassles_6$statistic, hassles_7$statistic)
parameter_4 <- c(hassles_1$parameter, hassles_2$parameter, hassles_3$parameter, hassles_4$parameter, hassles_5$parameter, hassles_6$parameter, hassles_7$parameter)

#Table
table_data_4 <- data.frame(
  Condition = conditions_4,
  "t" = statistic_4,
  "df" = parameter_4,
  "p" = p_values_4, 
  "Hedges' g" = estimate_4)

print(table_data_4)
```

```{r gratitude conditions}

#Comparing Across Gratitude Conditions

#Gratitude List

grat_1 <- t.test(grat_list$envy_all, grat_letter$envy_all)
grat_1_ef <- effsize::cohen.d(grat_list$envy_all, grat_letter$envy_all, hedges.correction = TRUE)

grat_2 <- t.test(grat_list$envy_all, grat_text$envy_all)
grat_2_ef <- effsize::cohen.d(grat_list$envy_all, grat_text$envy_all, hedges.correction = TRUE)

grat_3 <- t.test(grat_list$envy_all, grat_hk$envy_all)
grat_3_ef <- effsize::cohen.d(grat_list$envy_all, grat_hk$envy_all, hedges.correction = TRUE)

grat_4 <- t.test(grat_list$envy_all, grat_sing$envy_all)
grat_4_ef <- effsize::cohen.d(grat_list$envy_all, grat_sing$envy_all, hedges.correction = TRUE)

grat_5 <- t.test(grat_list$envy_all, grat_god_list$envy_all)
grat_5_ef <- effsize::cohen.d(grat_list$envy_all, grat_list$envy_all, hedges.correction = TRUE)

grat_6 <- t.test(grat_list$envy_all, grat_god_letter$envy_all)
grat_6_ef <- effsize::cohen.d(grat_list$envy_all, grat_god_letter$envy_all, hedges.correction = TRUE)

#Gratitude Letter

grat_7 <- t.test(grat_letter$envy_all, grat_text$envy_all)
grat_7_ef <- effsize::cohen.d(grat_letter$envy_all, grat_text$envy_all, hedges.correction = TRUE)

grat_8 <- t.test(grat_letter$envy_all, grat_hk$envy_all)
grat_8_ef <- effsize::cohen.d(grat_letter$envy_all, grat_hk$envy_all, hedges.correction = TRUE)

grat_9 <- t.test(grat_letter$envy_all, grat_sing$envy_all)
grat_9_ef <- effsize::cohen.d(grat_letter$envy_all, grat_sing$envy_all, hedges.correction = TRUE)

grat_10 <- t.test(grat_letter$envy_all, grat_god_list$envy_all)
grat_10_ef <- effsize::cohen.d(grat_letter$envy_all, grat_god_list$envy_all, hedges.correction = TRUE)

grat_11 <- t.test(grat_letter$envy_all, grat_god_letter$envy_all)
grat_11_ef <- effsize::cohen.d(grat_letter$envy_all, grat_god_letter$envy_all, hedges.correction = TRUE)

#Gratitude Text

grat_12 <- t.test(grat_text$envy_all, grat_hk$envy_all)
grat_12_ef <- effsize::cohen.d(grat_text$envy_all, grat_hk$envy_all, hedges.correction = TRUE)

grat_13 <- t.test(grat_text$envy_all, grat_sing$envy_all)
grat_13_ef <- effsize::cohen.d(grat_text$envy_all, grat_sing$envy_all, hedges.correction = TRUE)

grat_14 <- t.test(grat_text$envy_all, grat_god_list$envy_all)
grat_14_ef <- effsize::cohen.d(grat_text$envy_all, grat_god_list$envy_all, hedges.correction = TRUE)

grat_15 <- t.test(grat_text$envy_all, grat_god_letter$envy_all)
grat_15_ef <- effsize::cohen.d(grat_text$envy_all, grat_god_letter$envy_all, hedges.correction = TRUE)

#Chan Gratitude List

grat_16 <- t.test(grat_hk$envy_all, grat_sing$envy_all)
grat_16_ef <- effsize::cohen.d(grat_hk$envy_all, grat_sing$envy_all, hedges.correction = TRUE)

grat_17 <- t.test(grat_hk$envy_all, grat_god_list$envy_all)
grat_17_ef <- effsize::cohen.d(grat_hk$envy_all, grat_god_list$envy_all, hedges.correction = TRUE)

grat_18 <- t.test(grat_hk$envy_all, grat_god_letter$envy_all)
grat_18_ef <- effsize::cohen.d(grat_hk$envy_all, grat_god_letter$envy_all, hedges.correction = TRUE)

#Singapore Gratitude Task

grat_19 <- t.test(grat_sing$envy_all, grat_god_list$envy_all)
grat_19_ef <- effsize::cohen.d(grat_sing$envy_all, grat_god_list$envy_all, hedges.correction = TRUE)

grat_20 <- t.test(grat_sing$envy_all, grat_god_letter$envy_all)
grat_20_ef <- effsize::cohen.d(grat_sing$envy_all, grat_god_letter$envy_all, hedges.correction = TRUE)

#Gratitude to God

grat_21 <- t.test(grat_god_list$envy_all, grat_god_letter$envy_all)
grat_21_ef <- effsize::cohen.d(grat_god_list$envy_all, grat_god_letter$envy_all, hedges.correction = TRUE)

#Gratitude Conditions Graph

p_values_5 <- c(grat_1$p.value, grat_2$p.value, grat_3$p.value, grat_4$p.value, grat_5$p.value, grat_6$p.value, grat_7$p.value, grat_8$p.value, grat_9$p.value, grat_10$p.value, grat_11$p.value, grat_12$p.value, grat_13$p.value, grat_14$p.value, grat_15$p.value,grat_16$p.value, grat_17$p.value, grat_18$p.value, grat_19$p.value, grat_20$p.value,grat_21$p.value)
estimate_5 <- c(grat_1_ef$estimate, grat_2_ef$estimate, grat_3_ef$estimate, grat_4_ef$estimate, grat_5_ef$estimate, grat_6_ef$estimate, grat_7_ef$estimate, grat_8_ef$estimate, grat_9_ef$estimate, grat_10_ef$estimate, grat_11_ef$estimate, grat_12_ef$estimate, grat_13_ef$estimate, grat_14_ef$estimate, grat_15_ef$estimate,grat_16_ef$estimate, grat_17_ef$estimate, grat_18_ef$estimate, grat_19_ef$estimate, grat_20_ef$estimate,grat_21_ef$estimate)
statistic_5 <- c(grat_1$statistic, grat_2$statistic, grat_3$statistic, grat_4$statistic, grat_5$statistic, grat_6$statistic, grat_7$statistic, grat_8$statistic, grat_9$statistic, grat_10$statistic, grat_11$statistic, grat_12$statistic, grat_13$statistic, grat_14$statistic, grat_15$statistic,grat_16$statistic, grat_17$statistic, grat_18$statistic, grat_19$statistic, grat_20$statistic,grat_21$statistic)
parameter_5 <- c(grat_1$parameter, grat_2$parameter, grat_3$parameter, grat_4$parameter, grat_5$parameter, grat_6$parameter, grat_7$parameter, grat_8$parameter, grat_9$parameter, grat_10$parameter, grat_11$parameter, grat_12$parameter, grat_13$parameter, grat_14$parameter, grat_15$parameter,grat_16$parameter, grat_17$parameter, grat_18$parameter, grat_19$parameter, grat_20$parameter,grat_21$parameter)

#Table
table_data_5 <- data.frame(
  Condition = conditions_5,
  "t" = statistic_5,
  "df" = parameter_5,
  "p" = p_values_5, 
  "Hedges' g" = estimate_5)

print(table_data_5)

```

```{r control conditions}

#Comparing Across Control Conditions

#Control

con_1 <- t.test(control$envy_all, control_events$envy_all)
con_1_ef <- effsize::cohen.d(control$envy_all, control_events$envy_all, hedges.correction = TRUE)

con_2 <- t.test(control$envy_all, control_interesting$envy_all)
con_2_ef <- effsize::cohen.d(control$envy_all, control_interesting$envy_all, hedges.correction = TRUE)

con_3 <- t.test(control$envy_all, control_hassles$envy_all)
con_3_ef <- effsize::cohen.d(control$envy_all, control_hassles$envy_all, hedges.correction = TRUE)

#Control Events

con_4 <- t.test(control_events$envy_all, control_interesting$envy_all)
con_4_ef <- effsize::cohen.d(control_events$envy_all, control_interesting$envy_all, hedges.correction = TRUE)

con_5 <- t.test(control_events$envy_all, control_hassles$envy_all)
con_5_ef <- effsize::cohen.d(control_events$envy_all, control_hassles$envy_all, hedges.correction = TRUE)

#Control Interesting Events

con_6 <- t.test(control_interesting$envy_all, control_hassles$envy_all)
con_6_ef <- effsize::cohen.d(control_interesting$envy_all, control_hassles$envy_all, hedges.correction = TRUE)

#Control t-test Graph
p_values_6 <- c(con_1$p.value, con_2$p.value, con_3$p.value, con_4$p.value, con_5$p.value, con_6$p.value)
estimate_6 <- c(con_1_ef$estimate, con_2_ef$estimate, con_3_ef$estimate, con_4_ef$estimate, con_5_ef$estimate, con_6_ef$estimate)
statistic_6 <- c(con_1$statistic, con_2$statistic, con_3$statistic, con_4$statistic, con_5$statistic, con_6$statistic)
parameter_6 <- c(con_1$parameter, con_2$parameter, con_3$parameter, con_4$parameter, con_5$parameter, con_6$parameter)

#Table
table_data_6 <- data.frame(
  Condition = conditions_6,
  "t" = statistic_6,
  "df" = parameter_6,
  "p" = p_values_6, 
  "Hedges' g" = estimate_6)

print(table_data_6)

```

#t-Tests (Life Satisfaction)

```{r control}

control_1 <- t.test(control$ls_total, grat_list$ls_total)
control_1_ef <- effsize::cohen.d(control$ls_total, grat_list$ls_total, hedges.correction = TRUE)

control_2 <- t.test(control$ls_total, grat_letter$ls_total)
control_2_ef <- effsize::cohen.d(control$ls_total, grat_letter$ls_total, hedges.correction = TRUE)

control_3 <- t.test(control$ls_total, grat_text$ls_total)
control_3_ef <- effsize::cohen.d(control$ls_total, grat_text$ls_total, hedges.correction = TRUE)

control_4 <- t.test(control$ls_total, grat_hk$ls_total)
control_4_ef <- effsize::cohen.d(control$ls_total, grat_hk$ls_total, hedges.correction = TRUE)

control_5 <- t.test(control$ls_total, grat_sing$ls_total)
control_5_ef <- effsize::cohen.d(control$ls_total, grat_sing$ls_total, hedges.correction = TRUE)

control_6 <- t.test(control$ls_total, grat_sing$ls_total)
control_6_ef <- effsize::cohen.d(control$ls_total, grat_god_list$ls_total, hedges.correction = TRUE)

control_7 <- t.test(control$ls_total, grat_god_letter$ls_total)
control_7_ef <- effsize::cohen.d(control$ls_total, grat_god_letter$ls_total, hedges.correction = TRUE)

#Control t-test Graph

#Dataframe
p_values_1 <- c(control_1$p.value, control_2$p.value, control_3$p.value, control_4$p.value, control_5$p.value, control_6$p.value, control_7$p.value)
estimate_1 <- c(control_1_ef$estimate, control_2_ef$estimate, control_3_ef$estimate, control_4_ef$estimate, control_5_ef$estimate, control_6_ef$estimate, control_7_ef$estimate)
statistic_1 <- c(control_1$statistic, control_2$statistic, control_3$statistic, control_4$statistic, control_5$statistic, control_6$statistic, control_7$statistic)
parameter_1 <- c(control_1$parameter, control_2$parameter, control_3$parameter, control_4$parameter, control_5$parameter, control_6$parameter, control_7$parameter)

#Table
table_data_1 <- data.frame(
  Condition = conditions_1,
  "t" = statistic_1,
  "df" = parameter_1,
  "p" = p_values_1, 
  "Hedges' g" = estimate_1)

print(table_data_1)
```

```{r events}

#Events

events_1 <- t.test(control_events$ls_total, grat_list$ls_total)
events_1_ef <- effsize::cohen.d(control_events$ls_total, grat_list$ls_total, hedges.correction = TRUE)

events_2 <- t.test(control_events$ls_total, grat_letter$ls_total)
events_2_ef <- effsize::cohen.d(control_events$ls_total, grat_letter$ls_total, hedges.correction = TRUE)

events_3 <- t.test(control_events$ls_total, grat_text$ls_total)
events_3_ef <- effsize::cohen.d(control_events$ls_total, grat_text$ls_total, hedges.correction = TRUE)

events_4 <- t.test(control_events$ls_total, grat_hk$ls_total)
events_4_ef <- effsize::cohen.d(control_events$ls_total, grat_hk$ls_total, hedges.correction = TRUE)

events_5 <- t.test(control_events$ls_total, grat_sing$ls_total)
events_5_ef <- effsize::cohen.d(control_events$ls_total, grat_sing$ls_total, hedges.correction = TRUE)

events_6 <- t.test(control_events$ls_total, grat_god_list$ls_total)
events_6_ef <- effsize::cohen.d(control_events$ls_total, grat_god_list$ls_total, hedges.correction = TRUE)

events_7 <- t.test(control_events$ls_total, grat_god_letter$ls_total)
events_7_ef <- effsize::cohen.d(control_events$ls_total, grat_god_letter$ls_total, hedges.correction = TRUE)

#Control t-test Graph
p_values_2 <- c(events_1$p.value, events_2$p.value, events_3$p.value, events_4$p.value, events_5$p.value, events_6$p.value, events_7$p.value)
estimate_2 <- c(events_1_ef$estimate, events_2_ef$estimate, events_3_ef$estimate, events_4_ef$estimate, events_5_ef$estimate, events_6_ef$estimate, events_7_ef$estimate)
statistic_2 <- c(events_1$statistic, events_2$statistic, events_3$statistic, events_4$statistic, events_5$statistic, events_6$statistic, events_7$statistic)
parameter_2 <- c(events_1$parameter, events_2$parameter, events_3$parameter, events_4$parameter, events_5$parameter, events_6$parameter, events_7$parameter)

#Table
table_data_2 <- data.frame(
  Condition = conditions_2,
  "t" = statistic_2,
  "df" = parameter_2,
  "p" = p_values_2, 
  "Hedges' g" = estimate_2)

print(table_data_2)
```

```{r interesting events}

#Interesting Events

int_1 <- t.test(control_interesting$ls_total, grat_list$ls_total)
int_1_ef <- effsize::cohen.d(control_interesting$ls_total, grat_list$ls_total, hedges.correction = TRUE)

int_2 <- t.test(control_interesting$ls_total, grat_letter$ls_total)
int_2_ef <- effsize::cohen.d(control_interesting$ls_total, grat_letter$ls_total, hedges.correction = TRUE)

int_3 <- t.test(control_interesting$ls_total, grat_text$ls_total)
int_3_ef <- effsize::cohen.d(control_interesting$ls_total, grat_text$ls_total, hedges.correction = TRUE)

int_4 <- t.test(control_interesting$ls_total, grat_hk$ls_total)
int_4_ef <- effsize::cohen.d(control_interesting$ls_total, grat_hk$ls_total, hedges.correction = TRUE)

int_5 <- t.test(control_interesting$ls_total, grat_sing$ls_total)
int_5_ef <- effsize::cohen.d(control_interesting$ls_total, grat_sing$ls_total, hedges.correction = TRUE)

int_6 <- t.test(control_interesting$ls_total, grat_god_list$ls_total)
int_6_ef <- effsize::cohen.d(control_interesting$ls_total, grat_god_list$ls_total, hedges.correction = TRUE)

int_7 <- t.test(control_interesting$ls_total, grat_god_letter$ls_total)
int_7_ef <- effsize::cohen.d(control_interesting$ls_total, grat_god_letter$ls_total, hedges.correction = TRUE)

#Control t-test Graph
p_values_3 <- c(int_1$p.value, int_2$p.value, int_3$p.value, int_4$p.value, int_5$p.value, int_6$p.value, int_7$p.value)
estimate_3 <- c(int_1_ef$estimate, int_2_ef$estimate, int_3_ef$estimate, int_4_ef$estimate, int_5_ef$estimate, int_6_ef$estimate, int_7_ef$estimate)
statistic_3 <- c(int_1$statistic, int_2$statistic, int_3$statistic, int_4$statistic, int_5$statistic, int_6$statistic, int_7$statistic)
parameter_3 <- c(int_1$parameter, int_2$parameter, int_3$parameter, int_4$parameter, int_5$parameter, int_6$parameter, int_7$parameter)

#Table
table_data_3 <- data.frame(
  Condition = conditions_3,
  "t" = statistic_3,
  "df" = parameter_3,
  "p" = p_values_3, 
  "Hedges' g" = estimate_3)

print(table_data_3)
```

```{r hassles}

#Hassles

hassles_1 <- t.test(control_hassles$ls_total, grat_list$ls_total)
hassles_1_ef <- effsize::cohen.d(control_hassles$ls_total, grat_list$ls_total, hedges.correction = TRUE)

hassles_2 <- t.test(control_hassles$ls_total, grat_letter$ls_total)
hassles_2_ef <- effsize::cohen.d(control_hassles$ls_total, grat_letter$ls_total, hedges.correction = TRUE)

hassles_3 <- t.test(control_hassles$ls_total, grat_text$ls_total)
hassles_3_ef <- effsize::cohen.d(control_hassles$ls_total, grat_text$ls_total, hedges.correction = TRUE)

hassles_4 <- t.test(control_hassles$ls_total, grat_hk$ls_total)
hassles_4_ef <- effsize::cohen.d(control_hassles$ls_total, grat_hk$ls_total, hedges.correction = TRUE)

hassles_5 <- t.test(control_hassles$ls_total, grat_sing$ls_total)
hassles_5_ef <- effsize::cohen.d(control_hassles$ls_total, grat_sing$ls_total, hedges.correction = TRUE)

hassles_6 <- t.test(control_hassles$ls_total, grat_god_list$ls_total)
hassles_6_ef <- effsize::cohen.d(control_hassles$ls_total, grat_god_list$ls_total, hedges.correction = TRUE)

hassles_7 <- t.test(control_hassles$ls_total, grat_god_letter$ls_total)
hassles_7_ef <- effsize::cohen.d(control_hassles$ls_total, grat_god_letter$ls_total, hedges.correction = TRUE)

#Control t-test Graph

p_values_4 <- c(hassles_1$p.value, hassles_2$p.value, hassles_3$p.value, hassles_4$p.value, hassles_5$p.value, hassles_6$p.value, hassles_7$p.value)
estimate_4 <- c(hassles_1_ef$estimate, hassles_2_ef$estimate, hassles_3_ef$estimate, hassles_4_ef$estimate, hassles_5_ef$estimate, hassles_6_ef$estimate, hassles_7_ef$estimate)
statistic_4 <- c(hassles_1$statistic, hassles_2$statistic, hassles_3$statistic, hassles_4$statistic, hassles_5$statistic, hassles_6$statistic, hassles_7$statistic)
parameter_4 <- c(hassles_1$parameter, hassles_2$parameter, hassles_3$parameter, hassles_4$parameter, hassles_5$parameter, hassles_6$parameter, hassles_7$parameter)

#Table
table_data_4 <- data.frame(
  Condition = conditions_4,
  "t" = statistic_4,
  "df" = parameter_4,
  "p" = p_values_4, 
  "Hedges' g" = estimate_4)

print(table_data_4)
```

```{r gratitude conditions}

#Comparing Across Gratitude Conditions

#Gratitude List

grat_1 <- t.test(grat_list$ls_total, grat_letter$ls_total)
grat_1_ef <- effsize::cohen.d(grat_list$ls_total, grat_letter$ls_total, hedges.correction = TRUE)

grat_2 <- t.test(grat_list$ls_total, grat_text$ls_total)
grat_2_ef <- effsize::cohen.d(grat_list$ls_total, grat_text$ls_total, hedges.correction = TRUE)

grat_3 <- t.test(grat_list$ls_total, grat_hk$ls_total)
grat_3_ef <- effsize::cohen.d(grat_list$ls_total, grat_hk$ls_total, hedges.correction = TRUE)

grat_4 <- t.test(grat_list$ls_total, grat_sing$ls_total)
grat_4_ef <- effsize::cohen.d(grat_list$ls_total, grat_sing$ls_total, hedges.correction = TRUE)

grat_5 <- t.test(grat_list$ls_total, grat_god_list$ls_total)
grat_5_ef <- effsize::cohen.d(grat_list$ls_total, grat_list$ls_total, hedges.correction = TRUE)

grat_6 <- t.test(grat_list$ls_total, grat_god_letter$ls_total)
grat_6_ef <- effsize::cohen.d(grat_list$ls_total, grat_god_letter$ls_total, hedges.correction = TRUE)

#Gratitude Letter

grat_7 <- t.test(grat_letter$ls_total, grat_text$ls_total)
grat_7_ef <- effsize::cohen.d(grat_letter$ls_total, grat_text$ls_total, hedges.correction = TRUE)

grat_8 <- t.test(grat_letter$ls_total, grat_hk$ls_total)
grat_8_ef <- effsize::cohen.d(grat_letter$ls_total, grat_hk$ls_total, hedges.correction = TRUE)

grat_9 <- t.test(grat_letter$ls_total, grat_sing$ls_total)
grat_9_ef <- effsize::cohen.d(grat_letter$ls_total, grat_sing$ls_total, hedges.correction = TRUE)

grat_10 <- t.test(grat_letter$ls_total, grat_god_list$ls_total)
grat_10_ef <- effsize::cohen.d(grat_letter$ls_total, grat_god_list$ls_total, hedges.correction = TRUE)

grat_11 <- t.test(grat_letter$ls_total, grat_god_letter$ls_total)
grat_11_ef <- effsize::cohen.d(grat_letter$ls_total, grat_god_letter$ls_total, hedges.correction = TRUE)

#Gratitude Text

grat_12 <- t.test(grat_text$ls_total, grat_hk$ls_total)
grat_12_ef <- effsize::cohen.d(grat_text$ls_total, grat_hk$ls_total, hedges.correction = TRUE)

grat_13 <- t.test(grat_text$ls_total, grat_sing$ls_total)
grat_13_ef <- effsize::cohen.d(grat_text$ls_total, grat_sing$ls_total, hedges.correction = TRUE)

grat_14 <- t.test(grat_text$ls_total, grat_god_list$ls_total)
grat_14_ef <- effsize::cohen.d(grat_text$ls_total, grat_god_list$ls_total, hedges.correction = TRUE)

grat_15 <- t.test(grat_text$ls_total, grat_god_letter$ls_total)
grat_15_ef <- effsize::cohen.d(grat_text$ls_total, grat_god_letter$ls_total, hedges.correction = TRUE)

#Chan Gratitude List

grat_16 <- t.test(grat_hk$ls_total, grat_sing$ls_total)
grat_16_ef <- effsize::cohen.d(grat_hk$ls_total, grat_sing$ls_total, hedges.correction = TRUE)

grat_17 <- t.test(grat_hk$ls_total, grat_god_list$ls_total)
grat_17_ef <- effsize::cohen.d(grat_hk$ls_total, grat_god_list$ls_total, hedges.correction = TRUE)

grat_18 <- t.test(grat_hk$ls_total, grat_god_letter$ls_total)
grat_18_ef <- effsize::cohen.d(grat_hk$ls_total, grat_god_letter$ls_total, hedges.correction = TRUE)

#Singapore Gratitude Task

grat_19 <- t.test(grat_sing$ls_total, grat_god_list$ls_total)
grat_19_ef <- effsize::cohen.d(grat_sing$ls_total, grat_god_list$ls_total, hedges.correction = TRUE)

grat_20 <- t.test(grat_sing$ls_total, grat_god_letter$ls_total)
grat_20_ef <- effsize::cohen.d(grat_sing$ls_total, grat_god_letter$ls_total, hedges.correction = TRUE)

#Gratitude to God

grat_21 <- t.test(grat_god_list$ls_total, grat_god_letter$ls_total)
grat_21_ef <- effsize::cohen.d(grat_god_list$ls_total, grat_god_letter$ls_total, hedges.correction = TRUE)

#Gratitude Conditions Graph

p_values_5 <- c(grat_1$p.value, grat_2$p.value, grat_3$p.value, grat_4$p.value, grat_5$p.value, grat_6$p.value, grat_7$p.value, grat_8$p.value, grat_9$p.value, grat_10$p.value, grat_11$p.value, grat_12$p.value, grat_13$p.value, grat_14$p.value, grat_15$p.value,grat_16$p.value, grat_17$p.value, grat_18$p.value, grat_19$p.value, grat_20$p.value,grat_21$p.value)
estimate_5 <- c(grat_1_ef$estimate, grat_2_ef$estimate, grat_3_ef$estimate, grat_4_ef$estimate, grat_5_ef$estimate, grat_6_ef$estimate, grat_7_ef$estimate, grat_8_ef$estimate, grat_9_ef$estimate, grat_10_ef$estimate, grat_11_ef$estimate, grat_12_ef$estimate, grat_13_ef$estimate, grat_14_ef$estimate, grat_15_ef$estimate,grat_16_ef$estimate, grat_17_ef$estimate, grat_18_ef$estimate, grat_19_ef$estimate, grat_20_ef$estimate,grat_21_ef$estimate)
statistic_5 <- c(grat_1$statistic, grat_2$statistic, grat_3$statistic, grat_4$statistic, grat_5$statistic, grat_6$statistic, grat_7$statistic, grat_8$statistic, grat_9$statistic, grat_10$statistic, grat_11$statistic, grat_12$statistic, grat_13$statistic, grat_14$statistic, grat_15$statistic,grat_16$statistic, grat_17$statistic, grat_18$statistic, grat_19$statistic, grat_20$statistic,grat_21$statistic)
parameter_5 <- c(grat_1$parameter, grat_2$parameter, grat_3$parameter, grat_4$parameter, grat_5$parameter, grat_6$parameter, grat_7$parameter, grat_8$parameter, grat_9$parameter, grat_10$parameter, grat_11$parameter, grat_12$parameter, grat_13$parameter, grat_14$parameter, grat_15$parameter,grat_16$parameter, grat_17$parameter, grat_18$parameter, grat_19$parameter, grat_20$parameter,grat_21$parameter)

#Table
table_data_5 <- data.frame(
  Condition = conditions_5,
  "t" = statistic_5,
  "df" = parameter_5,
  "p" = p_values_5, 
  "Hedges' g" = estimate_5)

print(table_data_5)

```

```{r control conditions}

#Comparing Across Control Conditions

#Control

con_1 <- t.test(control$ls_total, control_events$ls_total)
con_1_ef <- effsize::cohen.d(control$ls_total, control_events$ls_total, hedges.correction = TRUE)

con_2 <- t.test(control$ls_total, control_interesting$ls_total)
con_2_ef <- effsize::cohen.d(control$ls_total, control_interesting$ls_total, hedges.correction = TRUE)

con_3 <- t.test(control$ls_total, control_hassles$ls_total)
con_3_ef <- effsize::cohen.d(control$ls_total, control_hassles$ls_total, hedges.correction = TRUE)

#Control Events

con_4 <- t.test(control_events$ls_total, control_interesting$ls_total)
con_4_ef <- effsize::cohen.d(control_events$ls_total, control_interesting$ls_total, hedges.correction = TRUE)

con_5 <- t.test(control_events$ls_total, control_hassles$ls_total)
con_5_ef <- effsize::cohen.d(control_events$ls_total, control_hassles$ls_total, hedges.correction = TRUE)

#Control Interesting Events

con_6 <- t.test(control_interesting$ls_total, control_hassles$ls_total)
con_6_ef <- effsize::cohen.d(control_interesting$ls_total, control_hassles$ls_total, hedges.correction = TRUE)

#Control t-test Graph
p_values_6 <- c(con_1$p.value, con_2$p.value, con_3$p.value, con_4$p.value, con_5$p.value, con_6$p.value)
estimate_6 <- c(con_1_ef$estimate, con_2_ef$estimate, con_3_ef$estimate, con_4_ef$estimate, con_5_ef$estimate, con_6_ef$estimate)
statistic_6 <- c(con_1$statistic, con_2$statistic, con_3$statistic, con_4$statistic, con_5$statistic, con_6$statistic)
parameter_6 <- c(con_1$parameter, con_2$parameter, con_3$parameter, con_4$parameter, con_5$parameter, con_6$parameter)

#Table
table_data_6 <- data.frame(
  Condition = conditions_6,
  "t" = statistic_6,
  "df" = parameter_6,
  "p" = p_values_6, 
  "Hedges' g" = estimate_6)

print(table_data_6)

```

#t-Tests (Attitude Towards Life)

```{r control}

control_1 <- t.test(control$ladder, grat_list$ladder)
control_1_ef <- effsize::cohen.d(control$ladder, grat_list$ladder, hedges.correction = TRUE)

control_2 <- t.test(control$ladder, grat_letter$ladder)
control_2_ef <- effsize::cohen.d(control$ladder, grat_letter$ladder, hedges.correction = TRUE)

control_3 <- t.test(control$ladder, grat_text$ladder)
control_3_ef <- effsize::cohen.d(control$ladder, grat_text$ladder, hedges.correction = TRUE)

control_4 <- t.test(control$ladder, grat_hk$ladder)
control_4_ef <- effsize::cohen.d(control$ladder, grat_hk$ladder, hedges.correction = TRUE)

control_5 <- t.test(control$ladder, grat_sing$ladder)
control_5_ef <- effsize::cohen.d(control$ladder, grat_sing$ladder, hedges.correction = TRUE)

control_6 <- t.test(control$ladder, grat_sing$ladder)
control_6_ef <- effsize::cohen.d(control$ladder, grat_god_list$ladder, hedges.correction = TRUE)

control_7 <- t.test(control$ladder, grat_god_letter$ladder)
control_7_ef <- effsize::cohen.d(control$ladder, grat_god_letter$ladder, hedges.correction = TRUE)

#Control t-test Graph

#Dataframe
p_values_1 <- c(control_1$p.value, control_2$p.value, control_3$p.value, control_4$p.value, control_5$p.value, control_6$p.value, control_7$p.value)
estimate_1 <- c(control_1_ef$estimate, control_2_ef$estimate, control_3_ef$estimate, control_4_ef$estimate, control_5_ef$estimate, control_6_ef$estimate, control_7_ef$estimate)
statistic_1 <- c(control_1$statistic, control_2$statistic, control_3$statistic, control_4$statistic, control_5$statistic, control_6$statistic, control_7$statistic)
parameter_1 <- c(control_1$parameter, control_2$parameter, control_3$parameter, control_4$parameter, control_5$parameter, control_6$parameter, control_7$parameter)

#Table
table_data_1 <- data.frame(
  Condition = conditions_1,
  "t" = statistic_1,
  "df" = parameter_1,
  "p" = p_values_1, 
  "Hedges' g" = estimate_1)

print(table_data_1)
```

```{r events}

#Events

events_1 <- t.test(control_events$ladder, grat_list$ladder)
events_1_ef <- effsize::cohen.d(control_events$ladder, grat_list$ladder, hedges.correction = TRUE)

events_2 <- t.test(control_events$ladder, grat_letter$ladder)
events_2_ef <- effsize::cohen.d(control_events$ladder, grat_letter$ladder, hedges.correction = TRUE)

events_3 <- t.test(control_events$ladder, grat_text$ladder)
events_3_ef <- effsize::cohen.d(control_events$ladder, grat_text$ladder, hedges.correction = TRUE)

events_4 <- t.test(control_events$ladder, grat_hk$ladder)
events_4_ef <- effsize::cohen.d(control_events$ladder, grat_hk$ladder, hedges.correction = TRUE)

events_5 <- t.test(control_events$ladder, grat_sing$ladder)
events_5_ef <- effsize::cohen.d(control_events$ladder, grat_sing$ladder, hedges.correction = TRUE)

events_6 <- t.test(control_events$ladder, grat_god_list$ladder)
events_6_ef <- effsize::cohen.d(control_events$ladder, grat_god_list$ladder, hedges.correction = TRUE)

events_7 <- t.test(control_events$ladder, grat_god_letter$ladder)
events_7_ef <- effsize::cohen.d(control_events$ladder, grat_god_letter$ladder, hedges.correction = TRUE)

#Control t-test Graph
p_values_2 <- c(events_1$p.value, events_2$p.value, events_3$p.value, events_4$p.value, events_5$p.value, events_6$p.value, events_7$p.value)
estimate_2 <- c(events_1_ef$estimate, events_2_ef$estimate, events_3_ef$estimate, events_4_ef$estimate, events_5_ef$estimate, events_6_ef$estimate, events_7_ef$estimate)
statistic_2 <- c(events_1$statistic, events_2$statistic, events_3$statistic, events_4$statistic, events_5$statistic, events_6$statistic, events_7$statistic)
parameter_2 <- c(events_1$parameter, events_2$parameter, events_3$parameter, events_4$parameter, events_5$parameter, events_6$parameter, events_7$parameter)

#Table
table_data_2 <- data.frame(
  Condition = conditions_2,
  "t" = statistic_2,
  "df" = parameter_2,
  "p" = p_values_2, 
  "Hedges' g" = estimate_2)

print(table_data_2)
```

```{r interesting events}

#Interesting Events

int_1 <- t.test(control_interesting$ladder, grat_list$ladder)
int_1_ef <- effsize::cohen.d(control_interesting$ladder, grat_list$ladder, hedges.correction = TRUE)

int_2 <- t.test(control_interesting$ladder, grat_letter$ladder)
int_2_ef <- effsize::cohen.d(control_interesting$ladder, grat_letter$ladder, hedges.correction = TRUE)

int_3 <- t.test(control_interesting$ladder, grat_text$ladder)
int_3_ef <- effsize::cohen.d(control_interesting$ladder, grat_text$ladder, hedges.correction = TRUE)

int_4 <- t.test(control_interesting$ladder, grat_hk$ladder)
int_4_ef <- effsize::cohen.d(control_interesting$ladder, grat_hk$ladder, hedges.correction = TRUE)

int_5 <- t.test(control_interesting$ladder, grat_sing$ladder)
int_5_ef <- effsize::cohen.d(control_interesting$ladder, grat_sing$ladder, hedges.correction = TRUE)

int_6 <- t.test(control_interesting$ladder, grat_god_list$ladder)
int_6_ef <- effsize::cohen.d(control_interesting$ladder, grat_god_list$ladder, hedges.correction = TRUE)

int_7 <- t.test(control_interesting$ladder, grat_god_letter$ladder)
int_7_ef <- effsize::cohen.d(control_interesting$ladder, grat_god_letter$ladder, hedges.correction = TRUE)

#Control t-test Graph
p_values_3 <- c(int_1$p.value, int_2$p.value, int_3$p.value, int_4$p.value, int_5$p.value, int_6$p.value, int_7$p.value)
estimate_3 <- c(int_1_ef$estimate, int_2_ef$estimate, int_3_ef$estimate, int_4_ef$estimate, int_5_ef$estimate, int_6_ef$estimate, int_7_ef$estimate)
statistic_3 <- c(int_1$statistic, int_2$statistic, int_3$statistic, int_4$statistic, int_5$statistic, int_6$statistic, int_7$statistic)
parameter_3 <- c(int_1$parameter, int_2$parameter, int_3$parameter, int_4$parameter, int_5$parameter, int_6$parameter, int_7$parameter)

#Table
table_data_3 <- data.frame(
  Condition = conditions_3,
  "t" = statistic_3,
  "df" = parameter_3,
  "p" = p_values_3, 
  "Hedges' g" = estimate_3)

print(table_data_3)
```

```{r hassles}

#Hassles

hassles_1 <- t.test(control_hassles$ladder, grat_list$ladder)
hassles_1_ef <- effsize::cohen.d(control_hassles$ladder, grat_list$ladder, hedges.correction = TRUE)

hassles_2 <- t.test(control_hassles$ladder, grat_letter$ladder)
hassles_2_ef <- effsize::cohen.d(control_hassles$ladder, grat_letter$ladder, hedges.correction = TRUE)

hassles_3 <- t.test(control_hassles$ladder, grat_text$ladder)
hassles_3_ef <- effsize::cohen.d(control_hassles$ladder, grat_text$ladder, hedges.correction = TRUE)

hassles_4 <- t.test(control_hassles$ladder, grat_hk$ladder)
hassles_4_ef <- effsize::cohen.d(control_hassles$ladder, grat_hk$ladder, hedges.correction = TRUE)

hassles_5 <- t.test(control_hassles$ladder, grat_sing$ladder)
hassles_5_ef <- effsize::cohen.d(control_hassles$ladder, grat_sing$ladder, hedges.correction = TRUE)

hassles_6 <- t.test(control_hassles$ladder, grat_god_list$ladder)
hassles_6_ef <- effsize::cohen.d(control_hassles$ladder, grat_god_list$ladder, hedges.correction = TRUE)

hassles_7 <- t.test(control_hassles$ladder, grat_god_letter$ladder)
hassles_7_ef <- effsize::cohen.d(control_hassles$ladder, grat_god_letter$ladder, hedges.correction = TRUE)

#Control t-test Graph

p_values_4 <- c(hassles_1$p.value, hassles_2$p.value, hassles_3$p.value, hassles_4$p.value, hassles_5$p.value, hassles_6$p.value, hassles_7$p.value)
estimate_4 <- c(hassles_1_ef$estimate, hassles_2_ef$estimate, hassles_3_ef$estimate, hassles_4_ef$estimate, hassles_5_ef$estimate, hassles_6_ef$estimate, hassles_7_ef$estimate)
statistic_4 <- c(hassles_1$statistic, hassles_2$statistic, hassles_3$statistic, hassles_4$statistic, hassles_5$statistic, hassles_6$statistic, hassles_7$statistic)
parameter_4 <- c(hassles_1$parameter, hassles_2$parameter, hassles_3$parameter, hassles_4$parameter, hassles_5$parameter, hassles_6$parameter, hassles_7$parameter)

#Table
table_data_4 <- data.frame(
  Condition = conditions_4,
  "t" = statistic_4,
  "df" = parameter_4,
  "p" = p_values_4, 
  "Hedges' g" = estimate_4)

print(table_data_4)
```

```{r gratitude conditions}

#Comparing Across Gratitude Conditions

#Gratitude List

grat_1 <- t.test(grat_list$ladder, grat_letter$ladder)
grat_1_ef <- effsize::cohen.d(grat_list$ladder, grat_letter$ladder, hedges.correction = TRUE)

grat_2 <- t.test(grat_list$ladder, grat_text$ladder)
grat_2_ef <- effsize::cohen.d(grat_list$ladder, grat_text$ladder, hedges.correction = TRUE)

grat_3 <- t.test(grat_list$ladder, grat_hk$ladder)
grat_3_ef <- effsize::cohen.d(grat_list$ladder, grat_hk$ladder, hedges.correction = TRUE)

grat_4 <- t.test(grat_list$ladder, grat_sing$ladder)
grat_4_ef <- effsize::cohen.d(grat_list$ladder, grat_sing$ladder, hedges.correction = TRUE)

grat_5 <- t.test(grat_list$ladder, grat_god_list$ladder)
grat_5_ef <- effsize::cohen.d(grat_list$ladder, grat_list$ladder, hedges.correction = TRUE)

grat_6 <- t.test(grat_list$ladder, grat_god_letter$ladder)
grat_6_ef <- effsize::cohen.d(grat_list$ladder, grat_god_letter$ladder, hedges.correction = TRUE)

#Gratitude Letter

grat_7 <- t.test(grat_letter$ladder, grat_text$ladder)
grat_7_ef <- effsize::cohen.d(grat_letter$ladder, grat_text$ladder, hedges.correction = TRUE)

grat_8 <- t.test(grat_letter$ladder, grat_hk$ladder)
grat_8_ef <- effsize::cohen.d(grat_letter$ladder, grat_hk$ladder, hedges.correction = TRUE)

grat_9 <- t.test(grat_letter$ladder, grat_sing$ladder)
grat_9_ef <- effsize::cohen.d(grat_letter$ladder, grat_sing$ladder, hedges.correction = TRUE)

grat_10 <- t.test(grat_letter$ladder, grat_god_list$ladder)
grat_10_ef <- effsize::cohen.d(grat_letter$ladder, grat_god_list$ladder, hedges.correction = TRUE)

grat_11 <- t.test(grat_letter$ladder, grat_god_letter$ladder)
grat_11_ef <- effsize::cohen.d(grat_letter$ladder, grat_god_letter$ladder, hedges.correction = TRUE)

#Gratitude Text

grat_12 <- t.test(grat_text$ladder, grat_hk$ladder)
grat_12_ef <- effsize::cohen.d(grat_text$ladder, grat_hk$ladder, hedges.correction = TRUE)

grat_13 <- t.test(grat_text$ladder, grat_sing$ladder)
grat_13_ef <- effsize::cohen.d(grat_text$ladder, grat_sing$ladder, hedges.correction = TRUE)

grat_14 <- t.test(grat_text$ladder, grat_god_list$ladder)
grat_14_ef <- effsize::cohen.d(grat_text$ladder, grat_god_list$ladder, hedges.correction = TRUE)

grat_15 <- t.test(grat_text$ladder, grat_god_letter$ladder)
grat_15_ef <- effsize::cohen.d(grat_text$ladder, grat_god_letter$ladder, hedges.correction = TRUE)

#Chan Gratitude List

grat_16 <- t.test(grat_hk$ladder, grat_sing$ladder)
grat_16_ef <- effsize::cohen.d(grat_hk$ladder, grat_sing$ladder, hedges.correction = TRUE)

grat_17 <- t.test(grat_hk$ladder, grat_god_list$ladder)
grat_17_ef <- effsize::cohen.d(grat_hk$ladder, grat_god_list$ladder, hedges.correction = TRUE)

grat_18 <- t.test(grat_hk$ladder, grat_god_letter$ladder)
grat_18_ef <- effsize::cohen.d(grat_hk$ladder, grat_god_letter$ladder, hedges.correction = TRUE)

#Singapore Gratitude Task

grat_19 <- t.test(grat_sing$ladder, grat_god_list$ladder)
grat_19_ef <- effsize::cohen.d(grat_sing$ladder, grat_god_list$ladder, hedges.correction = TRUE)

grat_20 <- t.test(grat_sing$ladder, grat_god_letter$ladder)
grat_20_ef <- effsize::cohen.d(grat_sing$ladder, grat_god_letter$ladder, hedges.correction = TRUE)

#Gratitude to God

grat_21 <- t.test(grat_god_list$ladder, grat_god_letter$ladder)
grat_21_ef <- effsize::cohen.d(grat_god_list$ladder, grat_god_letter$ladder, hedges.correction = TRUE)

#Gratitude Conditions Graph

p_values_5 <- c(grat_1$p.value, grat_2$p.value, grat_3$p.value, grat_4$p.value, grat_5$p.value, grat_6$p.value, grat_7$p.value, grat_8$p.value, grat_9$p.value, grat_10$p.value, grat_11$p.value, grat_12$p.value, grat_13$p.value, grat_14$p.value, grat_15$p.value,grat_16$p.value, grat_17$p.value, grat_18$p.value, grat_19$p.value, grat_20$p.value,grat_21$p.value)
estimate_5 <- c(grat_1_ef$estimate, grat_2_ef$estimate, grat_3_ef$estimate, grat_4_ef$estimate, grat_5_ef$estimate, grat_6_ef$estimate, grat_7_ef$estimate, grat_8_ef$estimate, grat_9_ef$estimate, grat_10_ef$estimate, grat_11_ef$estimate, grat_12_ef$estimate, grat_13_ef$estimate, grat_14_ef$estimate, grat_15_ef$estimate,grat_16_ef$estimate, grat_17_ef$estimate, grat_18_ef$estimate, grat_19_ef$estimate, grat_20_ef$estimate,grat_21_ef$estimate)
statistic_5 <- c(grat_1$statistic, grat_2$statistic, grat_3$statistic, grat_4$statistic, grat_5$statistic, grat_6$statistic, grat_7$statistic, grat_8$statistic, grat_9$statistic, grat_10$statistic, grat_11$statistic, grat_12$statistic, grat_13$statistic, grat_14$statistic, grat_15$statistic,grat_16$statistic, grat_17$statistic, grat_18$statistic, grat_19$statistic, grat_20$statistic,grat_21$statistic)
parameter_5 <- c(grat_1$parameter, grat_2$parameter, grat_3$parameter, grat_4$parameter, grat_5$parameter, grat_6$parameter, grat_7$parameter, grat_8$parameter, grat_9$parameter, grat_10$parameter, grat_11$parameter, grat_12$parameter, grat_13$parameter, grat_14$parameter, grat_15$parameter,grat_16$parameter, grat_17$parameter, grat_18$parameter, grat_19$parameter, grat_20$parameter,grat_21$parameter)

#Table
table_data_5 <- data.frame(
  Condition = conditions_5,
  "t" = statistic_5,
  "df" = parameter_5,
  "p" = p_values_5, 
  "Hedges' g" = estimate_5)

print(table_data_5)

```

```{r control conditions}

#Comparing Across Control Conditions

#Control

con_1 <- t.test(control$ladder, control_events$ladder)
con_1_ef <- effsize::cohen.d(control$ladder, control_events$ladder, hedges.correction = TRUE)

con_2 <- t.test(control$ladder, control_interesting$ladder)
con_2_ef <- effsize::cohen.d(control$ladder, control_interesting$ladder, hedges.correction = TRUE)

con_3 <- t.test(control$ladder, control_hassles$ladder)
con_3_ef <- effsize::cohen.d(control$ladder, control_hassles$ladder, hedges.correction = TRUE)

#Control Events

con_4 <- t.test(control_events$ladder, control_interesting$ladder)
con_4_ef <- effsize::cohen.d(control_events$ladder, control_interesting$ladder, hedges.correction = TRUE)

con_5 <- t.test(control_events$ladder, control_hassles$ladder)
con_5_ef <- effsize::cohen.d(control_events$ladder, control_hassles$ladder, hedges.correction = TRUE)

#Control Interesting Events

con_6 <- t.test(control_interesting$ladder, control_hassles$ladder)
con_6_ef <- effsize::cohen.d(control_interesting$ladder, control_hassles$ladder, hedges.correction = TRUE)

#Control t-test Graph
p_values_6 <- c(con_1$p.value, con_2$p.value, con_3$p.value, con_4$p.value, con_5$p.value, con_6$p.value)
estimate_6 <- c(con_1_ef$estimate, con_2_ef$estimate, con_3_ef$estimate, con_4_ef$estimate, con_5_ef$estimate, con_6_ef$estimate)
statistic_6 <- c(con_1$statistic, con_2$statistic, con_3$statistic, con_4$statistic, con_5$statistic, con_6$statistic)
parameter_6 <- c(con_1$parameter, con_2$parameter, con_3$parameter, con_4$parameter, con_5$parameter, con_6$parameter)

#Table
table_data_6 <- data.frame(
  Condition = conditions_6,
  "t" = statistic_6,
  "df" = parameter_6,
  "p" = p_values_6, 
  "Hedges' g" = estimate_6)

print(table_data_6)

```

#t-Tests (Percieved Self-Size)

```{r control}

control_1 <- t.test(control$self_image_total, grat_list$self_image_total)
control_1_ef <- effsize::cohen.d(control$self_image_total, grat_list$self_image_total, hedges.correction = TRUE)

control_2 <- t.test(control$self_image_total, grat_letter$self_image_total)
control_2_ef <- effsize::cohen.d(control$self_image_total, grat_letter$self_image_total, hedges.correction = TRUE)

control_3 <- t.test(control$self_image_total, grat_text$self_image_total)
control_3_ef <- effsize::cohen.d(control$self_image_total, grat_text$self_image_total, hedges.correction = TRUE)

control_4 <- t.test(control$self_image_total, grat_hk$self_image_total)
control_4_ef <- effsize::cohen.d(control$self_image_total, grat_hk$self_image_total, hedges.correction = TRUE)

control_5 <- t.test(control$self_image_total, grat_sing$self_image_total)
control_5_ef <- effsize::cohen.d(control$self_image_total, grat_sing$self_image_total, hedges.correction = TRUE)

control_6 <- t.test(control$self_image_total, grat_sing$self_image_total)
control_6_ef <- effsize::cohen.d(control$self_image_total, grat_god_list$self_image_total, hedges.correction = TRUE)

control_7 <- t.test(control$self_image_total, grat_god_letter$self_image_total)
control_7_ef <- effsize::cohen.d(control$self_image_total, grat_god_letter$self_image_total, hedges.correction = TRUE)

#Control t-test Graph

#Dataframe
p_values_1 <- c(control_1$p.value, control_2$p.value, control_3$p.value, control_4$p.value, control_5$p.value, control_6$p.value, control_7$p.value)
estimate_1 <- c(control_1_ef$estimate, control_2_ef$estimate, control_3_ef$estimate, control_4_ef$estimate, control_5_ef$estimate, control_6_ef$estimate, control_7_ef$estimate)
statistic_1 <- c(control_1$statistic, control_2$statistic, control_3$statistic, control_4$statistic, control_5$statistic, control_6$statistic, control_7$statistic)
parameter_1 <- c(control_1$parameter, control_2$parameter, control_3$parameter, control_4$parameter, control_5$parameter, control_6$parameter, control_7$parameter)

#Table
table_data_1 <- data.frame(
  Condition = conditions_1,
  "t" = statistic_1,
  "df" = parameter_1,
  "p" = p_values_1, 
  "Hedges' g" = estimate_1)

print(table_data_1)
```

```{r events}

#Events

events_1 <- t.test(control_events$self_image_total, grat_list$self_image_total)
events_1_ef <- effsize::cohen.d(control_events$self_image_total, grat_list$self_image_total, hedges.correction = TRUE)

events_2 <- t.test(control_events$self_image_total, grat_letter$self_image_total)
events_2_ef <- effsize::cohen.d(control_events$self_image_total, grat_letter$self_image_total, hedges.correction = TRUE)

events_3 <- t.test(control_events$self_image_total, grat_text$self_image_total)
events_3_ef <- effsize::cohen.d(control_events$self_image_total, grat_text$self_image_total, hedges.correction = TRUE)

events_4 <- t.test(control_events$self_image_total, grat_hk$self_image_total)
events_4_ef <- effsize::cohen.d(control_events$self_image_total, grat_hk$self_image_total, hedges.correction = TRUE)

events_5 <- t.test(control_events$self_image_total, grat_sing$self_image_total)
events_5_ef <- effsize::cohen.d(control_events$self_image_total, grat_sing$self_image_total, hedges.correction = TRUE)

events_6 <- t.test(control_events$self_image_total, grat_god_list$self_image_total)
events_6_ef <- effsize::cohen.d(control_events$self_image_total, grat_god_list$self_image_total, hedges.correction = TRUE)

events_7 <- t.test(control_events$self_image_total, grat_god_letter$self_image_total)
events_7_ef <- effsize::cohen.d(control_events$self_image_total, grat_god_letter$self_image_total, hedges.correction = TRUE)

#Control t-test Graph
p_values_2 <- c(events_1$p.value, events_2$p.value, events_3$p.value, events_4$p.value, events_5$p.value, events_6$p.value, events_7$p.value)
estimate_2 <- c(events_1_ef$estimate, events_2_ef$estimate, events_3_ef$estimate, events_4_ef$estimate, events_5_ef$estimate, events_6_ef$estimate, events_7_ef$estimate)
statistic_2 <- c(events_1$statistic, events_2$statistic, events_3$statistic, events_4$statistic, events_5$statistic, events_6$statistic, events_7$statistic)
parameter_2 <- c(events_1$parameter, events_2$parameter, events_3$parameter, events_4$parameter, events_5$parameter, events_6$parameter, events_7$parameter)

#Table
table_data_2 <- data.frame(
  Condition = conditions_2,
  "t" = statistic_2,
  "df" = parameter_2,
  "p" = p_values_2, 
  "Hedges' g" = estimate_2)

print(table_data_2)
```

```{r interesting events}

#Interesting Events

int_1 <- t.test(control_interesting$self_image_total, grat_list$self_image_total)
int_1_ef <- effsize::cohen.d(control_interesting$self_image_total, grat_list$self_image_total, hedges.correction = TRUE)

int_2 <- t.test(control_interesting$self_image_total, grat_letter$self_image_total)
int_2_ef <- effsize::cohen.d(control_interesting$self_image_total, grat_letter$self_image_total, hedges.correction = TRUE)

int_3 <- t.test(control_interesting$self_image_total, grat_text$self_image_total)
int_3_ef <- effsize::cohen.d(control_interesting$self_image_total, grat_text$self_image_total, hedges.correction = TRUE)

int_4 <- t.test(control_interesting$self_image_total, grat_hk$self_image_total)
int_4_ef <- effsize::cohen.d(control_interesting$self_image_total, grat_hk$self_image_total, hedges.correction = TRUE)

int_5 <- t.test(control_interesting$self_image_total, grat_sing$self_image_total)
int_5_ef <- effsize::cohen.d(control_interesting$self_image_total, grat_sing$self_image_total, hedges.correction = TRUE)

int_6 <- t.test(control_interesting$self_image_total, grat_god_list$self_image_total)
int_6_ef <- effsize::cohen.d(control_interesting$self_image_total, grat_god_list$self_image_total, hedges.correction = TRUE)

int_7 <- t.test(control_interesting$self_image_total, grat_god_letter$self_image_total)
int_7_ef <- effsize::cohen.d(control_interesting$self_image_total, grat_god_letter$self_image_total, hedges.correction = TRUE)

#Control t-test Graph
p_values_3 <- c(int_1$p.value, int_2$p.value, int_3$p.value, int_4$p.value, int_5$p.value, int_6$p.value, int_7$p.value)
estimate_3 <- c(int_1_ef$estimate, int_2_ef$estimate, int_3_ef$estimate, int_4_ef$estimate, int_5_ef$estimate, int_6_ef$estimate, int_7_ef$estimate)
statistic_3 <- c(int_1$statistic, int_2$statistic, int_3$statistic, int_4$statistic, int_5$statistic, int_6$statistic, int_7$statistic)
parameter_3 <- c(int_1$parameter, int_2$parameter, int_3$parameter, int_4$parameter, int_5$parameter, int_6$parameter, int_7$parameter)

#Table
table_data_3 <- data.frame(
  Condition = conditions_3,
  "t" = statistic_3,
  "df" = parameter_3,
  "p" = p_values_3, 
  "Hedges' g" = estimate_3)

print(table_data_3)
```

```{r hassles}

#Hassles

hassles_1 <- t.test(control_hassles$self_image_total, grat_list$self_image_total)
hassles_1_ef <- effsize::cohen.d(control_hassles$self_image_total, grat_list$self_image_total, hedges.correction = TRUE)

hassles_2 <- t.test(control_hassles$self_image_total, grat_letter$self_image_total)
hassles_2_ef <- effsize::cohen.d(control_hassles$self_image_total, grat_letter$self_image_total, hedges.correction = TRUE)

hassles_3 <- t.test(control_hassles$self_image_total, grat_text$self_image_total)
hassles_3_ef <- effsize::cohen.d(control_hassles$self_image_total, grat_text$self_image_total, hedges.correction = TRUE)

hassles_4 <- t.test(control_hassles$self_image_total, grat_hk$self_image_total)
hassles_4_ef <- effsize::cohen.d(control_hassles$self_image_total, grat_hk$self_image_total, hedges.correction = TRUE)

hassles_5 <- t.test(control_hassles$self_image_total, grat_sing$self_image_total)
hassles_5_ef <- effsize::cohen.d(control_hassles$self_image_total, grat_sing$self_image_total, hedges.correction = TRUE)

hassles_6 <- t.test(control_hassles$self_image_total, grat_god_list$self_image_total)
hassles_6_ef <- effsize::cohen.d(control_hassles$self_image_total, grat_god_list$self_image_total, hedges.correction = TRUE)

hassles_7 <- t.test(control_hassles$self_image_total, grat_god_letter$self_image_total)
hassles_7_ef <- effsize::cohen.d(control_hassles$self_image_total, grat_god_letter$self_image_total, hedges.correction = TRUE)

#Control t-test Graph

p_values_4 <- c(hassles_1$p.value, hassles_2$p.value, hassles_3$p.value, hassles_4$p.value, hassles_5$p.value, hassles_6$p.value, hassles_7$p.value)
estimate_4 <- c(hassles_1_ef$estimate, hassles_2_ef$estimate, hassles_3_ef$estimate, hassles_4_ef$estimate, hassles_5_ef$estimate, hassles_6_ef$estimate, hassles_7_ef$estimate)
statistic_4 <- c(hassles_1$statistic, hassles_2$statistic, hassles_3$statistic, hassles_4$statistic, hassles_5$statistic, hassles_6$statistic, hassles_7$statistic)
parameter_4 <- c(hassles_1$parameter, hassles_2$parameter, hassles_3$parameter, hassles_4$parameter, hassles_5$parameter, hassles_6$parameter, hassles_7$parameter)

#Table
table_data_4 <- data.frame(
  Condition = conditions_4,
  "t" = statistic_4,
  "df" = parameter_4,
  "p" = p_values_4, 
  "Hedges' g" = estimate_4)

print(table_data_4)
```

```{r gratitude conditions}

#Comparing Across Gratitude Conditions

#Gratitude List

grat_1 <- t.test(grat_list$self_image_total, grat_letter$self_image_total)
grat_1_ef <- effsize::cohen.d(grat_list$self_image_total, grat_letter$self_image_total, hedges.correction = TRUE)

grat_2 <- t.test(grat_list$self_image_total, grat_text$self_image_total)
grat_2_ef <- effsize::cohen.d(grat_list$self_image_total, grat_text$self_image_total, hedges.correction = TRUE)

grat_3 <- t.test(grat_list$self_image_total, grat_hk$self_image_total)
grat_3_ef <- effsize::cohen.d(grat_list$self_image_total, grat_hk$self_image_total, hedges.correction = TRUE)

grat_4 <- t.test(grat_list$self_image_total, grat_sing$self_image_total)
grat_4_ef <- effsize::cohen.d(grat_list$self_image_total, grat_sing$self_image_total, hedges.correction = TRUE)

grat_5 <- t.test(grat_list$self_image_total, grat_god_list$self_image_total)
grat_5_ef <- effsize::cohen.d(grat_list$self_image_total, grat_list$self_image_total, hedges.correction = TRUE)

grat_6 <- t.test(grat_list$self_image_total, grat_god_letter$self_image_total)
grat_6_ef <- effsize::cohen.d(grat_list$self_image_total, grat_god_letter$self_image_total, hedges.correction = TRUE)

#Gratitude Letter

grat_7 <- t.test(grat_letter$self_image_total, grat_text$self_image_total)
grat_7_ef <- effsize::cohen.d(grat_letter$self_image_total, grat_text$self_image_total, hedges.correction = TRUE)

grat_8 <- t.test(grat_letter$self_image_total, grat_hk$self_image_total)
grat_8_ef <- effsize::cohen.d(grat_letter$self_image_total, grat_hk$self_image_total, hedges.correction = TRUE)

grat_9 <- t.test(grat_letter$self_image_total, grat_sing$self_image_total)
grat_9_ef <- effsize::cohen.d(grat_letter$self_image_total, grat_sing$self_image_total, hedges.correction = TRUE)

grat_10 <- t.test(grat_letter$self_image_total, grat_god_list$self_image_total)
grat_10_ef <- effsize::cohen.d(grat_letter$self_image_total, grat_god_list$self_image_total, hedges.correction = TRUE)

grat_11 <- t.test(grat_letter$self_image_total, grat_god_letter$self_image_total)
grat_11_ef <- effsize::cohen.d(grat_letter$self_image_total, grat_god_letter$self_image_total, hedges.correction = TRUE)

#Gratitude Text

grat_12 <- t.test(grat_text$self_image_total, grat_hk$self_image_total)
grat_12_ef <- effsize::cohen.d(grat_text$self_image_total, grat_hk$self_image_total, hedges.correction = TRUE)

grat_13 <- t.test(grat_text$self_image_total, grat_sing$self_image_total)
grat_13_ef <- effsize::cohen.d(grat_text$self_image_total, grat_sing$self_image_total, hedges.correction = TRUE)

grat_14 <- t.test(grat_text$self_image_total, grat_god_list$self_image_total)
grat_14_ef <- effsize::cohen.d(grat_text$self_image_total, grat_god_list$self_image_total, hedges.correction = TRUE)

grat_15 <- t.test(grat_text$self_image_total, grat_god_letter$self_image_total)
grat_15_ef <- effsize::cohen.d(grat_text$self_image_total, grat_god_letter$self_image_total, hedges.correction = TRUE)

#Chan Gratitude List

grat_16 <- t.test(grat_hk$self_image_total, grat_sing$self_image_total)
grat_16_ef <- effsize::cohen.d(grat_hk$self_image_total, grat_sing$self_image_total, hedges.correction = TRUE)

grat_17 <- t.test(grat_hk$self_image_total, grat_god_list$self_image_total)
grat_17_ef <- effsize::cohen.d(grat_hk$self_image_total, grat_god_list$self_image_total, hedges.correction = TRUE)

grat_18 <- t.test(grat_hk$self_image_total, grat_god_letter$self_image_total)
grat_18_ef <- effsize::cohen.d(grat_hk$self_image_total, grat_god_letter$self_image_total, hedges.correction = TRUE)

#Singapore Gratitude Task

grat_19 <- t.test(grat_sing$self_image_total, grat_god_list$self_image_total)
grat_19_ef <- effsize::cohen.d(grat_sing$self_image_total, grat_god_list$self_image_total, hedges.correction = TRUE)

grat_20 <- t.test(grat_sing$self_image_total, grat_god_letter$self_image_total)
grat_20_ef <- effsize::cohen.d(grat_sing$self_image_total, grat_god_letter$self_image_total, hedges.correction = TRUE)

#Gratitude to God

grat_21 <- t.test(grat_god_list$self_image_total, grat_god_letter$self_image_total)
grat_21_ef <- effsize::cohen.d(grat_god_list$self_image_total, grat_god_letter$self_image_total, hedges.correction = TRUE)

#Gratitude Conditions Graph

p_values_5 <- c(grat_1$p.value, grat_2$p.value, grat_3$p.value, grat_4$p.value, grat_5$p.value, grat_6$p.value, grat_7$p.value, grat_8$p.value, grat_9$p.value, grat_10$p.value, grat_11$p.value, grat_12$p.value, grat_13$p.value, grat_14$p.value, grat_15$p.value,grat_16$p.value, grat_17$p.value, grat_18$p.value, grat_19$p.value, grat_20$p.value,grat_21$p.value)
estimate_5 <- c(grat_1_ef$estimate, grat_2_ef$estimate, grat_3_ef$estimate, grat_4_ef$estimate, grat_5_ef$estimate, grat_6_ef$estimate, grat_7_ef$estimate, grat_8_ef$estimate, grat_9_ef$estimate, grat_10_ef$estimate, grat_11_ef$estimate, grat_12_ef$estimate, grat_13_ef$estimate, grat_14_ef$estimate, grat_15_ef$estimate,grat_16_ef$estimate, grat_17_ef$estimate, grat_18_ef$estimate, grat_19_ef$estimate, grat_20_ef$estimate,grat_21_ef$estimate)
statistic_5 <- c(grat_1$statistic, grat_2$statistic, grat_3$statistic, grat_4$statistic, grat_5$statistic, grat_6$statistic, grat_7$statistic, grat_8$statistic, grat_9$statistic, grat_10$statistic, grat_11$statistic, grat_12$statistic, grat_13$statistic, grat_14$statistic, grat_15$statistic,grat_16$statistic, grat_17$statistic, grat_18$statistic, grat_19$statistic, grat_20$statistic,grat_21$statistic)
parameter_5 <- c(grat_1$parameter, grat_2$parameter, grat_3$parameter, grat_4$parameter, grat_5$parameter, grat_6$parameter, grat_7$parameter, grat_8$parameter, grat_9$parameter, grat_10$parameter, grat_11$parameter, grat_12$parameter, grat_13$parameter, grat_14$parameter, grat_15$parameter,grat_16$parameter, grat_17$parameter, grat_18$parameter, grat_19$parameter, grat_20$parameter,grat_21$parameter)

#Table
table_data_5 <- data.frame(
  Condition = conditions_5,
  "t" = statistic_5,
  "df" = parameter_5,
  "p" = p_values_5, 
  "Hedges' g" = estimate_5)

print(table_data_5)

```

```{r control conditions}

#Comparing Across Control Conditions

#Control

con_1 <- t.test(control$self_image_total, control_events$self_image_total)
con_1_ef <- effsize::cohen.d(control$self_image_total, control_events$self_image_total, hedges.correction = TRUE)

con_2 <- t.test(control$self_image_total, control_interesting$self_image_total)
con_2_ef <- effsize::cohen.d(control$self_image_total, control_interesting$self_image_total, hedges.correction = TRUE)

con_3 <- t.test(control$self_image_total, control_hassles$self_image_total)
con_3_ef <- effsize::cohen.d(control$self_image_total, control_hassles$self_image_total, hedges.correction = TRUE)

#Control Events

con_4 <- t.test(control_events$self_image_total, control_interesting$self_image_total)
con_4_ef <- effsize::cohen.d(control_events$self_image_total, control_interesting$self_image_total, hedges.correction = TRUE)

con_5 <- t.test(control_events$self_image_total, control_hassles$self_image_total)
con_5_ef <- effsize::cohen.d(control_events$self_image_total, control_hassles$self_image_total, hedges.correction = TRUE)

#Control Interesting Events

con_6 <- t.test(control_interesting$self_image_total, control_hassles$self_image_total)
con_6_ef <- effsize::cohen.d(control_interesting$self_image_total, control_hassles$self_image_total, hedges.correction = TRUE)

#Control t-test Graph
p_values_6 <- c(con_1$p.value, con_2$p.value, con_3$p.value, con_4$p.value, con_5$p.value, con_6$p.value)
estimate_6 <- c(con_1_ef$estimate, con_2_ef$estimate, con_3_ef$estimate, con_4_ef$estimate, con_5_ef$estimate, con_6_ef$estimate)
statistic_6 <- c(con_1$statistic, con_2$statistic, con_3$statistic, con_4$statistic, con_5$statistic, con_6$statistic)
parameter_6 <- c(con_1$parameter, con_2$parameter, con_3$parameter, con_4$parameter, con_5$parameter, con_6$parameter)

#Table
table_data_6 <- data.frame(
  Condition = conditions_6,
  "t" = statistic_6,
  "df" = parameter_6,
  "p" = p_values_6, 
  "Hedges' g" = estimate_6)

print(table_data_6)

```

