---
title: " Study 2 Dosage Graphs"
output:
  pdf_document: default
  word_document: default
  html_document: default
date: "2024-04-10"
---

```{r setup, include=FALSE}

library(ggplot2)
library(dplyr)
library(patchwork)
library(scales)
library(qualtRics)

```

```{r setup}
# Dangs API credential at UCSD
qualtrics_api_credentials(
  api_key = 'urh7PtWEEOkAzrbjmYQC2FoipCvCT4n8ZIByL5rH', 
  base_url = 'iad1.qualtrics.com',
  install = TRUE,
  overwrite = TRUE)

readRenviron("~/.Renviron")

# open data
DF <- fetch_survey(surveyID = 'SV_0rIOXQcp62uVzsq',
                   force_request = T,
                   label = F,
                   convert = F)

# process data
data <- DF %>%
  # remove incomplete or test observations
  filter(Finished != "0", condition !="NA")

data$gratitude_all <- rowMeans(data[, c("grateful", "thankful", "appreciative")], na.rm = TRUE)
data$happy_all <- rowMeans(data[, c("happy", "satisfied", "content", "joyful", "pleased")], na.rm = TRUE)
data$optimistic_all <- rowMeans(data[, c("optimistic", "hopeful")], na.rm = TRUE)
data$sad_all <- rowMeans(data[, c("sad", "depressed", "anxious", "nervous")], na.rm = TRUE)
data$indebted_all <- rowMeans(data[, c("indebted", "obligated")], na.rm = TRUE)
data$envy_all <- rowMeans(data[, c("envious", "bitter", "jealous")], na.rm = TRUE)

data$ls_total <- rowMeans(data[, c("ls_1", "ls_2", "ls_3", "ls_4", "ls_5")], na.rm = TRUE)
data$sc_total <- rowMeans(data[, c("sc_1", "sc_2", "sc_3")], na.rm = TRUE)
data$self_image_total <- rowMeans(data[, c("circle_task", "self_image", "signature")], na.rm = TRUE)
```

```{r participant statistics}

data <- data %>%
  mutate(sex_name = case_when(
    sex == 1 ~ "male",
    sex == 2 ~ "female",
    sex == 3 ~ "other"
  ))

data %>%
  group_by(sex_name) %>%
  summarise(sex_count = n())

mean(data$age)
sd(data$age)

```

```{r categories}
#Condition

condition_color <- c(
    "1" = "indianred",
    "2" = "lightsalmon",
    "3" = "lightgoldenrod",
    "4" = "palegreen2",
    "5" = "deepskyblue2",
    "6" = "orchid",
    "7" = "tan",
    "8" = "lightblue",
    "9" = "lightpink",
    "10" = "darkgray",
    "11" = "aquamarine")

condition_name <- c(
    "1" = "Measurement Only",
    "2" = "Events List",
    "3" = "Interesting Events List",
    "4" = "Hassles List",
    "5" = "Gratitude List",
    "6" = "Gratitude Letter",
    "7" = "Gratitude Text",
    "8" = "Chan Gratitude List",
    "9" = "Mental Subtraction Task",
    "10" = "Gratitude to God List",
    "11" = "Gratitude to God Letter")

calculate_std_error <- function(condition_data)
  return(sd(condition_data) / sqrt(length(condition_data)))

```

```{r gratitude}

cond.means_1 <-data%>%group_by(condition)%>%summarize(Mean=mean(gratitude_all)) 
print(cond.means_1)

# Calculate mean for 'gratitude_all' by 'condition' and subtract a value
cond.means_1 <- data %>%
  group_by(condition) %>%
  summarize(Mean = mean(gratitude_all)) %>%
  mutate(Mean = Mean - 4.502193)

```
```{r optimism}

optimistic_mean<-data%>%group_by(condition)%>%summarize(Mean=mean(optimistic_all)) 
print(optimistic_mean)

# Calculate mean for 'optimistic_all' by 'condition' and subtract a value
cond.means_2 <- data %>%
  group_by(condition) %>%
  summarize(Mean = mean(optimistic_all)) %>%
  mutate(Mean = Mean - 4.266447)

# Calculate standard error for 'optimistic_all' by 'condition'
std_errors <- data %>%
  group_by(condition) %>%
  summarize(Standard_Error = sd(optimistic_all) / sqrt(n()))

# Combine the dataframes
dosage_data <- data.frame(
  condition = cond.means_1$condition,
  gratitude_mean = cond.means_1$Mean,
  optimistic_mean = cond.means_2$Mean,
  optimistic_se = std_errors$Standard_Error
)

dosage_data$condition <- factor(dosage_data$condition)

# Create scatter plot with linear regression line
optimistic_plot_2 <- ggplot(dosage_data, aes(x = gratitude_mean, y = optimistic_mean, color = condition)) +
  geom_point(size = 2) +
  geom_smooth(method = "lm", se = FALSE, color = "red", size = 0.5) +
  geom_errorbar(aes(ymin = optimistic_mean - optimistic_se, ymax = optimistic_mean + optimistic_se), width = 0.1) +
  scale_color_manual(values = condition_color, labels = condition_name, 
                     name = "Condition") +  # Assign specific colors
  labs(title = "Optimism",
       x = "Mean Gratitude",
       y = "Mean Optimism") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),  # Center the plot title
    legend.title = element_text(face = "bold"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()# Set background color to white
  )

# Print the plot
print(optimistic_plot_2)
```
```{r indebted}
indebted_mean<-data%>%group_by(condition)%>%summarize(Mean=mean(indebted_all)) 
print(indebted_mean)

# Calculate mean for 'indebted_all' by 'condition' and subtract a value
cond.means_2 <- data %>%
  group_by(condition) %>%
  summarize(Mean = mean(indebted_all)) %>%
  mutate(Mean = Mean - 3.036184)

# Calculate standard error for 'indebted_all' by 'condition'
std_errors <- data %>%
  group_by(condition) %>%
  summarize(Standard_Error = sd(indebted_all) / sqrt(n()))

# Combine the dataframes
dosage_data <- data.frame(
  condition = cond.means_1$condition,
  gratitude_mean = cond.means_1$Mean,
  indebted_mean = cond.means_2$Mean,
  indebted_se = std_errors$Standard_Error
)

dosage_data$condition <- factor(dosage_data$condition)

# Create scatter plot with linear regression line
indebted_plot_2 <- ggplot(dosage_data, aes(x = gratitude_mean, y = indebted_mean, color = condition)) +
  geom_point(size = 2) +
  geom_smooth(method = "lm", se = FALSE, color = "red", size = 0.5) +
  geom_errorbar(aes(ymin = indebted_mean - indebted_se, ymax = indebted_mean + indebted_se), width = 0.1) +
  scale_color_manual(values = condition_color, labels = condition_name, 
                     name = "Condition") +  # Assign specific colors
  labs(title = "Mean Gratitude vs. Mean Indebtedness",
       x = "Mean Gratitude",
       y = "Mean Indebtedness") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),  # Center the plot title
    legend.title = element_text(face = "bold"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )

# Print the plot
print(indebted_plot_2)
```
```{r guilt}

guilty_mean<-data%>%group_by(condition)%>%summarize(Mean=mean(guilty)) 
print(guilty_mean)

# Calculate mean for 'guilty' by 'condition' and subtract a value
cond.means_2 <- data %>%
  group_by(condition) %>%
  summarize(Mean = mean(guilty)) %>%
  mutate(Mean = Mean - 1.993421)

# Calculate standard error for 'guilty' by 'condition'
std_errors <- data %>%
  group_by(condition) %>%
  summarize(Standard_Error = sd(guilty) / sqrt(n()))

# Combine the dataframes
dosage_data <- data.frame(
  condition = cond.means_1$condition,
  gratitude_mean = cond.means_1$Mean,
  guilty_mean = cond.means_2$Mean,
  guilty_se = std_errors$Standard_Error
)

dosage_data$condition <- factor(dosage_data$condition)

# Create scatter plot with linear regression line
guilty_plot_2 <- ggplot(dosage_data, aes(x = gratitude_mean, y = guilty_mean, color = condition)) +
  geom_point(size = 2) +
  geom_smooth(method = "lm", se = FALSE, color = "red", size = 0.5) +
  geom_errorbar(aes(ymin = guilty_mean - guilty_se, ymax = guilty_mean + guilty_se), width = 0.1) +
  scale_color_manual(values = condition_color, labels = condition_name, 
                     name = "Condition") +  # Assign specific colors
  labs(title = "Mean Gratitude vs. Mean Guilt",
       x = "Mean Gratitude",
       y = "Mean Guilt") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),  # Center the plot title
    legend.title = element_text(face = "bold"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()# Set background color to white
  )

# Print the plot
print(guilty_plot_2)
```
```{r envy}

envy_mean<-data%>%group_by(condition)%>%summarize(Mean=mean(envy_all)) 
print(envy_mean)

# Calculate mean for 'envy_all' by 'condition' and subtract a value
cond.means_2 <- data %>%
  group_by(condition) %>%
  summarize(Mean = mean(envy_all)) %>%
  mutate(Mean = Mean - 2.010965)

# Calculate standard error for 'envy_all' by 'condition'
std_errors <- data %>%
  group_by(condition) %>%
  summarize(Standard_Error = sd(envy_all) / sqrt(n()))

# Combine the dataframes
dosage_data <- data.frame(
  condition = cond.means_1$condition,
  gratitude_mean = cond.means_1$Mean,
  envy_mean = cond.means_2$Mean,
  envy_se = std_errors$Standard_Error
)

dosage_data$condition <- factor(dosage_data$condition)

# Create scatter plot with linear regression line
envy_plot_2 <- ggplot(dosage_data, aes(x = gratitude_mean, y = envy_mean, color = condition)) +
  geom_point(size = 2) +
  geom_smooth(method = "lm", se = FALSE, color = "red", size = 0.5) +
  geom_errorbar(aes(ymin = envy_mean - envy_se, ymax = envy_mean + envy_se), width = 0.1) +
  scale_color_manual(values = condition_color, labels = condition_name, 
                     name = "Condition") +  # Assign specific colors
  labs(title = "Mean Gratitude vs. Mean Envy",
       x = "Mean Gratitude",
       y = "Mean Envy") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),  # Center the plot title
    legend.title = element_text(face = "bold"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()# Set background color to white
  )

# Print the plot
print(envy_plot_2)
```

```{r social connection}

sc_mean<-data%>%group_by(condition)%>%summarize(Mean=mean(sc_total)) 
print(sc_mean)

# Calculate mean for 'sc_total' by 'condition' and subtract a value
cond.means_2 <- data %>%
  group_by(condition) %>%
  summarize(Mean = mean(sc_total)) %>%
  mutate(Mean = Mean - 3.866228)

# Calculate standard error for 'sc_total' by 'condition'
std_errors <- data %>%
  group_by(condition) %>%
  summarize(Standard_Error = sd(sc_total) / sqrt(n()))

# Combine the dataframes
dosage_data <- data.frame(
  condition = cond.means_1$condition,
  gratitude_mean = cond.means_1$Mean,
  sc_mean = cond.means_2$Mean,
  sc_se = std_errors$Standard_Error
)

dosage_data$condition <- factor(dosage_data$condition)

# Create scatter plot with linear regression line
sc_plot_2 <- ggplot(dosage_data, aes(x = gratitude_mean, y = sc_mean, color = condition)) +
  geom_point(size = 2) +
  geom_smooth(method = "lm", se = FALSE, color = "red", size = 0.5) +
  geom_errorbar(aes(ymin = sc_mean - sc_se, ymax = sc_mean + sc_se), width = 0.1) +
  scale_color_manual(values = condition_color, labels = condition_name, 
                     name = "Condition") +  # Assign specific colors
  labs(title = "Mean Gratitude vs. Mean Social Connection",
       x = "Mean Gratitude",
       y = "Mean Social Connection") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),  # Center the plot title
    legend.title = element_text(face = "bold"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()# Set background color to white
  )

# Print the plot
print(sc_plot_2)
```
```{r percieved self image}

self_image_mean<-data%>%group_by(condition)%>%summarize(Mean=mean(self_image_total)) 
print(self_image_mean)

# Calculate mean for 'self_image_total' by 'condition' and subtract a value
cond.means_2 <- data %>%
  group_by(condition) %>%
  summarize(Mean = mean(self_image_total)) %>%
  mutate(Mean = Mean - 3.657895)

# Calculate standard error for 'self_image_total' by 'condition'
std_errors <- data %>%
  group_by(condition) %>%
  summarize(Standard_Error = sd(self_image_total) / sqrt(n()))

# Combine the dataframes
dosage_data <- data.frame(
  condition = cond.means_1$condition,
  gratitude_mean = cond.means_1$Mean,
  self_image_mean = cond.means_2$Mean,
  self_image_se = std_errors$Standard_Error
)

dosage_data$condition <- factor(dosage_data$condition)

# Create scatter plot with linear regression line
self_image_plot_2 <- ggplot(dosage_data, aes(x = gratitude_mean, y = self_image_mean, color = condition)) +
  geom_point(size = 2) +
  geom_smooth(method = "lm", se = FALSE, color = "red", size = 0.5) +
  geom_errorbar(aes(ymin = self_image_mean - self_image_se, ymax = self_image_mean + self_image_se), width = 0.1) +
  scale_color_manual(values = condition_color, labels = condition_name, 
                     name = "Condition") +  # Assign specific colors
  labs(title = "Mean Gratitude vs. Mean Percieved Self Image",
       x = "Mean Gratitude",
       y = "Mean Percieved Self Image") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),  # Center the plot title
    legend.title = element_text(face = "bold"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()# Set background color to white
  )

# Print the plot
print(self_image_plot_2)
```
```{r ladder}

ladder_mean<-data%>%group_by(condition)%>%summarize(Mean=mean(ladder)) 
print(ladder_mean)

# Calculate mean for 'ladder' by 'condition' and subtract a value
cond.means_2 <- data %>%
  group_by(condition) %>%
  summarize(Mean = mean(ladder)) %>%
  mutate(Mean = Mean - 5.782895)

# Calculate standard error for 'ladder' by 'condition'
std_errors <- data %>%
  group_by(condition) %>%
  summarize(Standard_Error = sd(ladder) / sqrt(n()))

# Combine the dataframes
dosage_data <- data.frame(
  condition = cond.means_1$condition,
  gratitude_mean = cond.means_1$Mean,
  ladder_mean = cond.means_2$Mean,
  ladder_se = std_errors$Standard_Error
)

dosage_data$condition <- factor(dosage_data$condition)

# Create scatter plot with linear regression line
ladder_plot_2 <- ggplot(dosage_data, aes(x = gratitude_mean, y = ladder_mean, color = condition)) +
  geom_point(size = 2) +
  geom_smooth(method = "lm", se = FALSE, color = "red", size = 0.5) +
  geom_errorbar(aes(ymin = ladder_mean - ladder_se, ymax = ladder_mean + ladder_se), width = 0.1) +
  scale_color_manual(values = condition_color, labels = condition_name, 
                     name = "Condition") +  # Assign specific colors
  labs(title = "Mean Gratitude vs. Mean Percieved Self Image",
       x = "Mean Gratitude",
       y = "Mean Percieved Self Image") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),  # Center the plot title
    legend.title = element_text(face = "bold"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()# Set background color to white
  )

# Print the plot
print(ladder_plot_2)
```

#Combined Graphs
```{r combined graph}
# Set theme settings
theme_settings <- list(
  plot.title = theme(text = element_text(size = 8, face = "bold")),
  axis.title = theme(text = element_text(size = 6)) 
)

# Combine the plots
combined_plots <- (
  (optimistic_plot_2 + theme_settings + theme(legend.position = "none")) +
  (indebted_plot_2 + theme_settings + theme(legend.position = "none")) +
  (guilty_plot_2 + theme_settings + theme(legend.position = "none")) +
    plot_layout(guides = "collect")

combined_plots_2 <- (
  (sc_plot_2 + theme_settings + theme(legend.position = "none")) +
  (ladder_plot_2 + theme_settings + theme(legend.position = "none")) +
  (self_image_plot_2 + theme_settings + theme(legend.position = "right"))
  + plot_layout(guides = "collect") 

# Set the size of the plot
options(repr.plot.width = 15, repr.plot.height = 13)

# Print the combined plot
print(combined_plots)
print(combined_plots_2)

```
